import {expect,test} from '@playwright/test';
async function mount(page,config,pickers=false){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-advance-vacuum-card'));await page.evaluate(async({config,pickers})=>{if(pickers)for(const tag of ['ha-entity-picker','ha-icon-picker'])if(!customElements.get(tag))customElements.define(tag,class extends HTMLElement{constructor(){super();this.value='';this.hass=null;}});const editor=await customElements.get('nodalia-advance-vacuum-card').getConfigElement();editor.hass=window.makeHass({'vacuum.one':{state:'docked'},'vacuum.two':{state:'idle'},'image.map':{state:'now'},'camera.map':{state:'idle'},'select.suction':{state:'high'},'sensor.calibration':{state:'0'},'input_text.session':{state:''},'light.one':{state:'on'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.advanceEditorFixture=editor;window.advanceEditorChanges=[];editor.addEventListener('config-changed',event=>window.advanceEditorChanges.push(event.detail.config));},{config,pickers});return page.locator('nodalia-advance-vacuum-card-editor');}
test('Advance Vacuum editor retains text and unfinished JSON drafts through HA updates without emitting each keystroke',async({page})=>{
 const editor=await mount(page,{entity:'vacuum.one',name:'Robot',routines:[{entity:'script.clean',label:'Clean',service_data:{flag:false,count:0}}],custom_extension:{flag:false,count:0}});
 const name=editor.locator('input[data-field="name"]');await name.fill('My robot');expect(await page.evaluate(()=>window.advanceEditorChanges.length)).toBe(0);expect(await page.evaluate(()=>Array.from(window.advanceEditorFixture._draftValues))).toEqual([['name','My robot']]);await page.evaluate(()=>{const e=window.advanceEditorFixture;e.hass={...e._hass,states:{...e._hass.states,'sensor.new':{entity_id:'sensor.new',state:'2',attributes:{}}}};});await expect(name).toBeFocused();await expect(name).toHaveValue('My robot');expect(await page.evaluate(()=>window.advanceEditorChanges.length)).toBe(0);await name.dispatchEvent('change');expect(await page.evaluate(()=>window.advanceEditorChanges.at(-1).name)).toBe('My robot');
 const routines=editor.locator('textarea[data-field="routines"]');const before=await page.evaluate(()=>JSON.stringify(window.advanceEditorFixture._config.routines));await routines.fill('[{"label":');await routines.dispatchEvent('change');await expect(routines).toHaveAttribute('aria-invalid','true');await page.evaluate(()=>{const e=window.advanceEditorFixture;e.hass={...e._hass,states:{...e._hass.states,'sensor.more':{entity_id:'sensor.more',state:'3',attributes:{}}}};});await expect(routines).toHaveValue('[{"label":');await expect(routines).toHaveAttribute('aria-invalid','true');expect(await page.evaluate(()=>JSON.stringify(window.advanceEditorFixture._config.routines))).toBe(before);
 await routines.fill('[{"entity":"script.clean","label":"Clean","service_data":{"flag":false,"count":0},"target":{"entity_id":"vacuum.one"}}]');await routines.dispatchEvent('change');await expect(routines).not.toHaveAttribute('aria-invalid','true');const config=await page.evaluate(()=>window.advanceEditorChanges.at(-1));expect(config.routines[0]).toMatchObject({entity:'script.clean',label:'Clean',service_data:{flag:false,count:0},target:{entity_id:'vacuum.one'}});expect(config.custom_extension).toEqual({flag:false,count:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Advance Vacuum editor retains missing selectors and scopes HA/native controls to robot, map and helper domains',async({page})=>{
 const editor=await mount(page,{entity:'vacuum.missing',map_source:{camera:'image.missing'},calibration_source:{entity:'sensor.missing'},shared_cleaning_session_entity:'input_text.missing',suction_select_entity:'select.missing',haptics:null,animations:42});
 for(const [field,value] of [['entity','vacuum.missing'],['map_source.camera','image.missing'],['calibration_source.entity','sensor.missing'],['shared_cleaning_session_entity','input_text.missing'],['suction_select_entity','select.missing']])await expect(editor.locator(`select[data-field="${field}"]`)).toHaveValue(value);
 await expect(editor.locator('select[data-field="entity"] option[value="light.one"]')).toHaveCount(0);await expect(editor.locator('datalist')).toHaveCount(0);await expect(editor.locator('input[data-field="animations.content_duration"]')).toHaveValue('520');
 await page.evaluate(()=>{for(const tag of ['ha-entity-picker','ha-icon-picker'])if(!customElements.get(tag))customElements.define(tag,class extends HTMLElement{constructor(){super();this.value='';this.hass=null;}});});await expect(editor.locator('ha-entity-picker[data-field="entity"]')).toHaveCount(1);
 expect(await page.evaluate(()=>{const p=window.advanceEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-field="map_source.camera"]');return {domains:p.includeDomains,image:p.entityFilter({entity_id:'image.map'}),light:p.entityFilter({entity_id:'light.one'})};})).toEqual({domains:['camera','image'],image:true,light:false});
 await page.evaluate(()=>{const e=window.advanceEditorFixture;for(const [field,value] of [['entity','vacuum.two'],['map_source.camera','image.map']]){const p=e.shadowRoot.querySelector(`ha-entity-picker[data-field="${field}"]`);p.dispatchEvent(new CustomEvent('value-changed',{detail:{value},bubbles:true,composed:true}));}});const config=await page.evaluate(()=>window.advanceEditorChanges.at(-1));expect(config).toMatchObject({entity:'vacuum.two',map_source:{camera:'image.map'},calibration_source:{entity:'sensor.missing'},suction_select_entity:'select.missing'});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Advance Vacuum editor validates JSON lists, keeps paired commands, restores cleared durations and releases drafts across robots',async({page})=>{
 const editor=await mount(page,{entity:'vacuum.one',language:'es',animations:{content_duration:0},styles:{card:{background:'rgba(10, 20, 30, 0.3)'}},custom_menu:{items:[{label:'Wash',icon:'mdi:waves',tap_action:{action:'call-service',service:'vacuum.send_command',service_data:{flag:false,count:0},target:{entity_id:'vacuum.one'}}}]}});
 const menu=editor.locator('textarea[data-field="custom_menu.items"]');const before=await page.evaluate(()=>JSON.stringify(window.advanceEditorFixture._config.custom_menu.items));for(const value of ['{','{}','null','42']){await menu.fill(value);await menu.dispatchEvent('change');await expect(menu).toHaveAttribute('aria-invalid','true');expect(await menu.evaluate(input=>input.validationMessage)).toBe('Introduce una lista JSON válida.');expect(await page.evaluate(()=>JSON.stringify(window.advanceEditorFixture._config.custom_menu.items))).toBe(before);}
 await menu.fill('[{"label":"Wash","icon":"mdi:waves","tap_action":{"action":"call-service","service":"vacuum.send_command","service_data":{"flag":false,"count":0},"target":{"entity_id":"vacuum.one"}}}]');await menu.dispatchEvent('change');let config=await page.evaluate(()=>window.advanceEditorChanges.at(-1));expect(config.custom_menu.items[0]).toMatchObject({label:'Wash',icon:'mdi:waves',tap_action:{service_data:{flag:false,count:0},target:{entity_id:'vacuum.one'}}});
 const duration=editor.locator('input[data-field="animations.content_duration"]');await expect(duration).toHaveValue('0');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('520');await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.background"]')).toHaveValue('rgba(10, 20, 30, 0.3)');const name=editor.locator('input[data-field="name"]');await name.fill('Unsaved robot');await page.evaluate(()=>window.advanceEditorFixture.setConfig({entity:'vacuum.two',name:'Second'}));await expect(name).toHaveValue('Second');await name.fill('Temporary');await page.evaluate(()=>window.advanceEditorFixture.remove());expect(await page.evaluate(()=>window.advanceEditorFixture._draftValues.size)).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
