import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-alarm-panel-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-alarm-panel-card').getConfigElement();editor.hass=window.makeHass({'alarm_control_panel.one':{state:'disarmed',attributes:{friendly_name:'Alarm'}},'input_text.pin':{state:'1234'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.alarmEditorFixture=editor;window.alarmEditorChanges=[];editor.addEventListener('config-changed',event=>window.alarmEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-alarm-panel-card-editor');}
test('Alarm editor guards nested settings and picker events while retaining missing alarm/PIN helpers, YAML and focus',async({page})=>{
 const editor=await mount(page,{entity:'alarm_control_panel.missing',code_entity:'input_text.missing',haptics:null,animations:42,custom_extension:{value:7}});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('alarm_control_panel.missing');await expect(editor.locator('select[data-field="code_entity"]')).toHaveValue('input_text.missing');
 await page.evaluate(()=>window.alarmEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['alarm_control_panel.bad']}})));expect(await page.evaluate(()=>window.alarmEditorChanges.at(-1))).toMatchObject({entity:'alarm_control_panel.missing',code_entity:'input_text.missing',custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Security');await page.evaluate(()=>window.alarmEditorFixture.hass=window.makeHass({'alarm_control_panel.two':{state:'armed_home'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Security');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Alarm editor restores cleared numeric defaults and preserves state tints, code visibility and PIN helpers',async({page})=>{
 const editor=await mount(page,{entity:'alarm_control_panel.one',code_entity:'input_text.pin',code:'9876',show_code_input:'always',wrong_code_feedback_ms:12000,animations:{content_duration:900},styles:{state_tints:{disarmed:'rgba(10, 20, 30, 0.3)'},control:{accent_background:'rgba(40, 50, 60, 0.25)'}}});const wait=editor.locator('input[data-field="wrong_code_feedback_ms"]');await wait.fill('');await wait.dispatchEvent('change');await expect(wait).toHaveValue('5000');
 await editor.locator('select[data-field="show_code_input"]').selectOption('never');await expect.poll(()=>page.evaluate(()=>window.alarmEditorChanges.at(-1)?.show_code_input)).toBe(false);await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.content_duration"]');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('420');
 const config=await page.evaluate(()=>window.alarmEditorChanges.at(-1));expect(config).toMatchObject({code_entity:'input_text.pin',code:'9876',show_code_input:false,styles:{state_tints:{disarmed:'rgba(10, 20, 30, 0.3)'},control:{accent_background:'rgba(40, 50, 60, 0.25)'}}});expect(config.wrong_code_feedback_ms).toBeUndefined();expect(config.animations?.content_duration).toBeUndefined();
 const tint=await page.evaluate(config=>{const card=document.createElement('nodalia-alarm-panel-card');card.setConfig(config);return card._config.styles.state_tints.disarmed;},config);expect(tint).toBe('rgba(10, 20, 30, 0.3)');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Alarm editor cancels queued emissions on replacement/disconnect and keyboard toggles survive an abandoned pointer sequence',async({page})=>{
 const editor=await mount(page,{entity:'alarm_control_panel.one'});await page.evaluate(()=>{const editor=window.alarmEditorFixture;editor._scheduleEmitConfig();editor.setConfig({entity:'alarm_control_panel.one',name:'Replacement'});});expect(await page.evaluate(()=>window.alarmEditorFixture._emitConfigTimer)).toBe(0);await page.waitForTimeout(20);expect(await page.evaluate(()=>window.alarmEditorChanges)).toEqual([]);
 await page.evaluate(()=>{const editor=window.alarmEditorFixture;editor.shadowRoot.querySelector('[data-editor-toggle="styles"]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:8,button:0}));});await expect(editor.locator('[data-editor-toggle="styles"]')).toHaveAttribute('aria-expanded','true');await editor.locator('[data-editor-toggle="styles"]').press('Enter');await expect(editor.locator('[data-editor-toggle="styles"]')).toHaveAttribute('aria-expanded','false');
 const state=await page.evaluate(()=>{const editor=window.alarmEditorFixture;editor._scheduleEmitConfig();editor._suppressEditorToggleClickFor='styles';editor.remove();const state={timer:editor._emitConfigTimer,suppressed:editor._suppressEditorToggleClickFor};document.querySelector('#fixture').append(editor);return state;});expect(state).toEqual({timer:0,suppressed:null});await editor.locator('[data-editor-toggle="styles"]').press('Enter');await expect(editor.locator('[data-editor-toggle="styles"]')).toHaveAttribute('aria-expanded','true');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
