import {expect,test} from '@playwright/test';
async function mount(page,config={},state='disarmed'){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-alarm-panel-card'));await page.evaluate(({config,state})=>{window.alarmServiceCalls=[];const card=document.createElement('nodalia-alarm-panel-card');card.setConfig({entity:'alarm_control_panel.one',language:'en',show_code_input:true,animations:{content_duration:140},...config});const hass=window.makeHass({'alarm_control_panel.one':{state,last_changed:'2026-10-01T10:00:00Z',attributes:{friendly_name:'Alarm',supported_features:63,code_format:'number',delay:60}},'alarm_control_panel.two':{state:'disarmed',attributes:{friendly_name:'Other',supported_features:63,code_format:'number'}}});hass.callService=(...args)=>{window.alarmServiceCalls.push(args);return Promise.resolve(true);};card.hass=hass;document.querySelector('#fixture').append(card);window.alarmLifecycleCard=card;},{config,state});return page.locator('nodalia-alarm-panel-card');}
test('Alarm refreshes pending modes when arm attributes change and preserves PIN focus during updates',async({page})=>{
 const card=await mount(page,{show_arm_night:true},'pending');await page.evaluate(()=>{const card=window.alarmLifecycleCard;card._hass.states['alarm_control_panel.one'].attributes.arm_mode='armed_away';card.hass=card._hass;});await expect(card.locator('[data-alarm-action="alarm_arm_away"]')).toHaveCount(0);await expect(card.locator('[data-alarm-action="alarm_arm_night"]')).toHaveCount(1);
 const pin=card.locator('input[data-alarm-field="code"]');await pin.fill('1234');await page.evaluate(()=>{const card=window.alarmLifecycleCard;card._hass.states['alarm_control_panel.one'].attributes.arm_mode='armed_night';card.hass=card._hass;});await expect(pin).toBeFocused();await expect(pin).toHaveValue('1234');await pin.blur();await expect(card.locator('[data-alarm-action="alarm_arm_away"]')).toHaveCount(1);await expect(card.locator('[data-alarm-action="alarm_arm_night"]')).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Alarm exposes synchronous service failure immediately and ignores failures from replaced entities',async({page})=>{
 const card=await mount(page,{haptics:{enabled:true,fallback_vibrate:true}});await card.locator('input[data-alarm-field="code"]').fill('1234');await page.evaluate(()=>{const card=window.alarmLifecycleCard;card._hass.callService=()=>{throw new Error('offline');};Object.defineProperty(navigator,'vibrate',{configurable:true,value:()=>{throw new Error('unsupported');}});});await card.locator('[data-alarm-action="alarm_arm_away"]').click();await expect(card.locator('.alarm-card__chip--pin-error')).toHaveText('Wrong code');expect(await page.evaluate(()=>window.alarmLifecycleCard._pinVerifyWatch)).toBeNull();
 await page.evaluate(()=>{const card=window.alarmLifecycleCard;card.setConfig({entity:'alarm_control_panel.one',show_code_input:true});card._hass.callService=()=>new Promise((_,reject)=>window.rejectOldAlarmRequest=reject);});await card.locator('input[data-alarm-field="code"]').fill('5678');await card.locator('[data-alarm-action="alarm_arm_away"]').click();await page.evaluate(async()=>{const card=window.alarmLifecycleCard;card.setConfig({entity:'alarm_control_panel.two',show_code_input:true});window.rejectOldAlarmRequest(new Error('old failure'));await Promise.resolve();await Promise.resolve();});await expect(card.locator('input[data-alarm-field="code"]')).toHaveValue('');await expect(card.locator('.alarm-card__chip--pin-error')).toHaveCount(0);expect(await page.evaluate(()=>window.alarmLifecycleCard._pinVerifyWatch)).toBeNull();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Alarm resolved service retains PIN verification and superseded requests cannot clear a later watch',async({page})=>{
 const card=await mount(page);await card.locator('input[data-alarm-field="code"]').fill('1234');await card.locator('[data-alarm-action="alarm_arm_away"]').click();expect(await page.evaluate(()=>Boolean(window.alarmLifecycleCard._pinVerifyWatch))).toBe(true);expect(await page.evaluate(()=>window.alarmServiceCalls)).toEqual([['alarm_control_panel','alarm_arm_away',{entity_id:'alarm_control_panel.one',code:'1234'}]]);
 await page.evaluate(()=>window.alarmLifecycleCard._hass.callService=()=>new Promise((_,reject)=>window.rejectEarlierAlarmRequest=reject));await card.locator('[data-alarm-action="alarm_arm_home"]').click();await page.evaluate(()=>window.alarmLifecycleCard._hass.callService=()=>Promise.resolve(true));await card.locator('[data-alarm-action="alarm_arm_away"]').click();await page.evaluate(async()=>{window.rejectEarlierAlarmRequest(new Error('superseded'));await Promise.resolve();await Promise.resolve();});expect(await page.evaluate(()=>Boolean(window.alarmLifecycleCard._pinVerifyWatch))).toBe(true);await expect(card.locator('.alarm-card__chip--pin-error')).toHaveCount(0);
 await page.evaluate(()=>{const card=window.alarmLifecycleCard;card._hass.states['alarm_control_panel.one'].state='armed_away';card.hass=card._hass;});expect(await page.evaluate(()=>window.alarmLifecycleCard._pinVerifyWatch)).toBeNull();
 await page.evaluate(async()=>{const card=window.alarmLifecycleCard;card._hass.callService=()=>new Promise((_,reject)=>window.rejectChangedAlarmRequest=reject);card._runAlarmAction('alarm_disarm');card._hass.states['alarm_control_panel.one'].state='disarmed';card.hass=card._hass;window.rejectChangedAlarmRequest(new Error('late failure'));await Promise.resolve();await Promise.resolve();});await expect(card.locator('.alarm-card__chip--pin-error')).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Alarm owns countdown and animation timers, retains entrance deadline and clears PIN on removal or missing entity',async({page})=>{
 await mount(page,{},'arming');const result=await page.evaluate(()=>{const card=window.alarmLifecycleCard;const deadline=card._entranceAnimationResetTimer;for(const name of ['One','Two','Three']){card._hass.states['alarm_control_panel.one'].attributes.friendly_name=name;card.hass=card._hass;}const stable=deadline===card._entranceAnimationResetTimer;const countdown=card._countdownInterval!==null;const schedule=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerPressAnimation(card.shadowRoot.querySelector('.alarm-card__content'));window.NodaliaUtils.scheduleDeferTimer=schedule;const pending=card._fallbackAnimationTimers.size;card._codeInput='1234';card.remove();const detached={resize:card._resizeRenderFrame,countdown:card._countdownInterval,entrance:card._entranceAnimationResetTimer,fallback:card._fallbackAnimationTimers.size,code:card._codeInput};document.querySelector('#fixture').append(card);const remounted=card._countdownInterval!==null;card.setConfig({entity:'alarm_control_panel.missing'});return{stable,countdown,pending,detached,remounted,missing:{countdown:card._countdownInterval,entrance:card._entranceAnimationResetTimer,fallback:card._fallbackAnimationTimers.size}};});expect(result).toEqual({stable:true,countdown:true,pending:1,detached:{resize:0,countdown:null,entrance:0,fallback:0,code:''},remounted:true,missing:{countdown:null,entrance:0,fallback:0}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Alarm keeps a touched action button mounted through blur and queued HA renders until click',async({page})=>{
 const card=await mount(page);await card.locator('input[data-alarm-field="code"]').fill('1234');const retained=await page.evaluate(async()=>{const card=window.alarmLifecycleCard,button=card.shadowRoot.querySelector('[data-alarm-action="alarm_arm_away"]');button.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:7,isPrimary:true,button:0}));card._hass.states['alarm_control_panel.one'].attributes.friendly_name='Updated';card.hass=card._hass;card.shadowRoot.querySelector('input[data-alarm-field="code"]').blur();await new Promise(resolve=>setTimeout(resolve,0));const retained=button===card.shadowRoot.querySelector('[data-alarm-action="alarm_arm_away"]');button.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,composed:true,pointerId:7,isPrimary:true,button:0}));button.click();return retained;});expect(retained).toBe(true);expect(await page.evaluate(()=>window.alarmServiceCalls.length)).toBe(1);await expect(card.locator('.alarm-card__title')).toHaveText('Updated');expect(await page.evaluate(()=>window.alarmLifecycleCard._actionPointer)).toBeNull();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
