import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-calendar-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-calendar-card').getConfigElement();editor.hass=window.makeHass({'calendar.home':{state:'off',attributes:{friendly_name:'Home'}},'calendar.work':{state:'off',attributes:{friendly_name:'Work'}},'weather.one':{state:'sunny'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.calendarEditorFixture=editor;window.calendarEditorChanges=[];editor.addEventListener('config-changed',event=>window.calendarEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-calendar-card-editor');}
test('Calendar empty editor adds a real second draft row and retains missing selections, YAML and focus',async({page})=>{
 const editor=await mount(page,{calendars:[],weather_entity:'weather.missing',haptics:null,animations:42,security:false,custom_extension:{value:7}});await expect(editor.locator('input[data-field="weather_entity"]')).toHaveValue('weather.missing');await expect(editor.locator('input[data-field="calendars.0.entity"]')).toHaveValue('');await editor.locator('[data-editor-action="add-calendar"]').click();await expect(editor.locator('input[data-field="calendars.1.entity"]')).toHaveValue('');const label=editor.locator('input[data-field="calendars.1.label"]');await label.fill('Draft');await label.dispatchEvent('change');const entity=editor.locator('input[data-field="calendars.1.entity"]');await entity.fill('calendar.missing');await entity.dispatchEvent('change');const config=await page.evaluate(()=>window.calendarEditorChanges.at(-1));expect(config).toMatchObject({calendars:[{},{entity:'calendar.missing',label:'Draft'}],custom_extension:{value:7},weather_entity:'weather.missing'});
 await page.evaluate(()=>window.calendarEditorFixture.shadowRoot.querySelector('input[data-field="calendars.1.entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['calendar.bad']}})));expect(await page.evaluate(()=>window.calendarEditorChanges.at(-1))).toMatchObject({calendars:[{},{entity:'calendar.missing',label:'Draft'}]});const title=editor.locator('input[data-field="title"]');await title.fill('Agenda');await page.evaluate(()=>window.calendarEditorFixture.hass=window.makeHass({'calendar.other':{state:'off'}}));await expect(title).toBeFocused();await expect(title).toHaveValue('Agenda');await expect(entity).toHaveValue('calendar.missing');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Calendar reordering keeps labels and tints paired and rejects fractional, huge and unsafe row indices',async({page})=>{
 const editor=await mount(page,{calendars:[{entity:'calendar.home',label:'Home',tint:'rgba(10, 20, 30, 0.3)'},{entity:'calendar.work',label:'Work',tint:'#abcdef'}]});await editor.locator('[data-editor-action="move-calendar-up"][data-index="1"]').click();expect(await page.evaluate(()=>window.calendarEditorChanges.at(-1).calendars)).toEqual([{entity:'calendar.work',label:'Work',tint:'#abcdef'},{entity:'calendar.home',label:'Home',tint:'rgba(10, 20, 30, 0.3)'}]);const tint=editor.locator('input[type="color"][data-field="calendars.1.tint"]');await tint.fill('#00ff00');await tint.dispatchEvent('change');expect(await page.evaluate(()=>window.calendarEditorChanges.at(-1).calendars[1].tint)).toBe('rgba(0, 255, 0, 0.3)');
 const unchanged=await page.evaluate(()=>{const editor=window.calendarEditorFixture,before=JSON.stringify(editor._config);for(const [index,delta] of [[-1,1],[0.5,1],[2,-1],[100,-100]])editor._moveCalendar(index,delta);for(const field of ['calendars.1000000000.entity','calendars.0.5.entity','calendars..entity','calendars.-1.entity','calendars.0.__proto__','calendars.2.constructor'])editor._setFieldValue(editor._config,field,'bad');return before===JSON.stringify(editor._config);});expect(unchanged).toBe(true);await editor.locator('[data-editor-action="remove-calendar"][data-index="0"]').click();expect(await page.evaluate(()=>window.calendarEditorChanges.at(-1).calendars)).toEqual([{entity:'calendar.home',label:'Home',tint:'rgba(0, 255, 0, 0.3)'}]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Calendar cleared numeric overrides restore defaults and retain false security flags and translucent styles',async({page})=>{
 const editor=await mount(page,{calendars:['calendar.home'],max_visible_events:8,refresh_interval:900,allow_delete:false,tint_auto:false,animations:{content_duration:420},security:{allow_webhooks_for_non_admin:false,extension:0},styles:{icon:{background:'rgba(10, 20, 30, 0.3)'}},custom_extension:{flag:false,count:0}});for(const [field,value] of [['max_visible_events','2'],['refresh_interval','300']]){const input=editor.locator(`input[data-field="${field}"]`);await input.fill('');await input.dispatchEvent('change');await expect(input).toHaveValue(value);}await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.content_duration"]');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('260');const config=await page.evaluate(()=>window.calendarEditorChanges.at(-1));expect(config).toMatchObject({allow_delete:false,tint_auto:false,security:{extension:0},styles:{icon:{background:'rgba(10, 20, 30, 0.3)'}},custom_extension:{flag:false,count:0}});expect(config.max_visible_events).toBeUndefined();expect(config.refresh_interval).toBeUndefined();expect(config.animations?.content_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
