import {expect,test} from '@playwright/test';
test.use({hasTouch:true});
async function mount(page,{provider='home_assistant',deferred=false,hold='none',image=false}={}){
 await page.route('**/api/camera_proxy/**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="160" height="90"><rect width="160" height="90" fill="#567"/></svg>'}));
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-camera-card'));
 await page.evaluate(({provider,deferred,hold,image})=>{
  window.cameraRequests=[];window.cameraActions=[];window.cameraServices=[];window.cameraPlayers=[];
  const Player=customElements.get('nodalia-go2rtc-player');
  Player.prototype.configure=function(options){this.testOptions={...options};if(!window.cameraPlayers.includes(this))window.cameraPlayers.push(this);};
  Player.prototype.connectedCallback=function(){};Player.prototype.disconnect=function(){this.testDisconnected=true;};
  window.cameraConfig={entity:'camera.one',cameras:['camera.one'],hold_action:hold,animations:{enabled:false},camera_streams:[{camera:'camera.one',provider,stream:'one',base_url:'https://go2rtc.example',url:'https://player.example'}]};
  const hass=window.createHassFixture({entities:{'camera.one':{state:'idle',last_changed:'2026-10-01T10:00:00Z',attributes:{friendly_name:'Front',...(image?{access_token:'initial-token'}:{})}},'camera.two':{state:'idle',attributes:{friendly_name:'Back'}}},overrides:{connection:{},user:{id:'first',is_admin:true},callWS(message){const entry={message};window.cameraRequests.push(entry);return deferred?new Promise((resolve,reject)=>Object.assign(entry,{resolve,reject})):Promise.resolve({path:'/signed/one'});},callService(domain,service,data,target){window.cameraServices.push({domain,service,data,target});return Promise.resolve();}}});
  window.cameraHass=hass;const card=document.createElement('nodalia-camera-card');card.setConfig(window.cameraConfig);card.hass=hass;card.addEventListener('hass-more-info',event=>window.cameraActions.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.cameraCard=card;
 },{provider,deferred,hold,image});return page.locator('nodalia-camera-card');
}
const open=card=>card.locator('[data-camera-action="camera-tap"]').click();
test('Camera native keyboard activates once, restores focus and owns hold/cancel/reconnect actions',async({page})=>{
 const card=await mount(page,{hold:'more-info'});const button=card.locator('[data-camera-action="camera-tap"]');await button.focus();await button.press('Enter');await expect(card.locator('[role="dialog"]')).toBeVisible();await card.locator('.camera-card__expanded-close').press('Escape');await expect(button).toBeFocused();await button.press('Space');await expect(card.locator('[role="dialog"]')).toBeVisible();await card.locator('.camera-card__expanded-close').click();
 await button.dispatchEvent('pointerdown',{pointerId:1,button:0,clientX:30,clientY:30});await expect.poll(()=>page.evaluate(()=>window.cameraActions)).toEqual(['camera.one']);await button.dispatchEvent('pointerup',{pointerId:1});await button.dispatchEvent('click');await expect(card.locator('[role="dialog"]')).toHaveCount(0);
 for(const cancel of ['pointercancel','pointermove']){await button.dispatchEvent('pointerdown',{pointerId:2,button:0,clientX:30,clientY:30});await button.dispatchEvent(cancel,{pointerId:2,clientX:80,clientY:30});await page.waitForTimeout(550);}expect(await page.evaluate(()=>window.cameraActions.length)).toBe(1);
 await button.dispatchEvent('pointerdown',{pointerId:3,button:0});await page.evaluate(()=>{window.cameraCard.remove();document.querySelector('#fixture').append(window.cameraCard);});await page.waitForTimeout(550);expect(await page.evaluate(()=>window.cameraActions.length)).toBe(1);await button.dispatchEvent('pointerdown',{pointerId:4,button:0});await expect.poll(()=>page.evaluate(()=>window.cameraActions.length)).toBe(2);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera isolates old signed streams and player events after connection or configuration changes',async({page})=>{
 const card=await mount(page,{provider:'frigate_go2rtc',deferred:true,image:true});await expect.poll(()=>page.evaluate(()=>window.cameraRequests.length)).toBe(1);await open(card);await expect.poll(()=>page.evaluate(()=>window.cameraPlayers.length)).toBe(1);
 await page.evaluate(()=>{window.cameraOldPlayer=window.cameraPlayers[0];const hass={...window.cameraHass,connection:{},user:{id:'second',is_admin:true}};window.cameraHass=hass;window.cameraCard.hass=hass;});await expect(card.locator('[role="dialog"]')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>window.cameraRequests.length)).toBe(2);await open(card);await page.evaluate(()=>window.cameraRequests[0].reject(new Error('Old signing failure')));await page.waitForTimeout(400);expect(await page.evaluate(()=>window.cameraRequests.length)).toBe(2);expect(await page.evaluate(()=>window.cameraCard._go2rtcPrefetchSignature)).not.toBe('');
 await page.evaluate(()=>window.cameraRequests[1].resolve({path:'/signed/current'}));await expect.poll(()=>page.evaluate(()=>window.cameraPlayers.at(-1).testOptions.source)).toBe('/signed/current');
 await page.evaluate(()=>{window.cameraOldPlayer.dispatchEvent(new CustomEvent('nodalia-go2rtc-error',{detail:{message:'Obsolete error'}}));window.cameraOldPlayer.dispatchEvent(new Event('nodalia-go2rtc-loaded'));});await expect(card.locator('[data-camera-stream-status]')).not.toHaveClass(/is-error/);await expect(card.locator('[data-camera-poster]')).toBeVisible();
 await page.evaluate(()=>window.cameraPlayers.at(-1).dispatchEvent(new Event('nodalia-go2rtc-loaded')));await expect(card.locator('[data-camera-poster]')).toBeHidden();await expect(card.locator('[data-camera-stream-status]')).toBeHidden();
 const player=await page.evaluate(()=>window.cameraPlayers.length);await page.evaluate(()=>window.cameraCard.hass={...window.cameraHass});expect(await page.evaluate(()=>window.cameraPlayers.length)).toBe(player);await page.evaluate(()=>window.cameraCard.setConfig({...window.cameraConfig,cameras:['camera.two'],entity:'camera.two'}));await expect(card.locator('[role="dialog"]')).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera cancels owned signing retry and never starts a replacement request after detach',async({page})=>{
 const card=await mount(page,{provider:'frigate_go2rtc',deferred:true});await open(card);await page.evaluate(()=>window.cameraRequests[0].reject(new Error('Retryable signing failure')));await expect.poll(()=>page.evaluate(()=>window.cameraCard._retryTimers.size)).toBe(1);await page.evaluate(()=>window.cameraCard.remove());await expect.poll(()=>page.evaluate(()=>window.cameraCard._retryTimers.size)).toBe(0);await page.waitForTimeout(400);expect(await page.evaluate(()=>window.cameraRequests.length)).toBe(1);await page.evaluate(()=>document.querySelector('#fixture').append(window.cameraCard));await expect.poll(()=>page.evaluate(()=>window.cameraRequests.length)).toBe(2);expect(await page.evaluate(()=>window.cameraCard._expandedOpen)).toBe(false);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera ignores obsolete image errors, rotates failed tokens and bounds failed URL storage',async({page})=>{
 const card=await mount(page,{image:true});await expect(card.locator('[data-camera-image]')).toBeVisible();await page.evaluate(()=>{window.cameraOldImage=window.cameraCard.shadowRoot.querySelector('[data-camera-image]');window.cameraHass.states['camera.one'].attributes.access_token='rotated-token';window.cameraCard.hass={...window.cameraHass};window.cameraOldImage.dispatchEvent(new Event('error'));});await expect(card.locator('[data-camera-image]')).toHaveAttribute('src',/rotated-token/);expect(await page.evaluate(()=>window.cameraCard._failedCameraTokens.size)).toBe(0);
 await page.evaluate(()=>window.cameraCard.shadowRoot.querySelector('[data-camera-image]').dispatchEvent(new Event('error')));await expect(card.locator('[data-camera-image]')).toHaveCount(0);await page.evaluate(()=>{window.cameraHass.states['camera.one'].attributes.access_token='third-token';window.cameraCard.hass={...window.cameraHass};});await expect(card.locator('[data-camera-image]')).toHaveAttribute('src',/third-token/);
 await page.evaluate(()=>{for(let n=0;n<120;n++)window.cameraCard._rememberFailedImageUrl('/snapshot/'+n);});expect(await page.evaluate(()=>window.cameraCard._failedImageUrls.size)).toBeLessThanOrEqual(64);
 await page.evaluate(()=>{window.cameraHass.states['camera.one'].attributes.friendly_name='Renamed';window.cameraCard.hass={...window.cameraHass};});await expect(card.locator('[data-camera-action="camera-tap"]')).toHaveAttribute('aria-label',/Open camera/);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera owns asynchronous HA fallback creation and carries native player state',async({page})=>{
 const card=await mount(page);await page.evaluate(()=>{window.cameraHelpers=[];window.loadCardHelpers=()=>new Promise(resolve=>window.cameraHelpers.push(resolve));});await open(card);await expect.poll(()=>page.evaluate(()=>window.cameraHelpers.length)).toBe(1);await page.evaluate(()=>{window.cameraCard.setConfig({...window.cameraConfig,entity:'camera.two',cameras:['camera.two']});window.cameraHelpers[0]({createCardElement(){throw new Error('Obsolete helper must not run');}});});await expect(card.locator('[role="dialog"]')).toHaveCount(0);
 await page.evaluate(()=>{customElements.define('ha-camera-stream',class extends HTMLElement{});});await open(card);await expect(card.locator('ha-camera-stream')).toHaveCount(1);expect(await card.locator('ha-camera-stream').evaluate(node=>({entity:node.stateObj.entity_id,muted:node.muted,controls:node.controls,fit:node.fitMode}))).toEqual({entity:'camera.two',muted:true,controls:false,fit:'contain'});await page.evaluate(()=>{window.cameraHass.states['camera.two'].state='streaming';window.cameraCard.hass={...window.cameraHass};});expect(await card.locator('ha-camera-stream').evaluate(node=>node.stateObj.state)).toBe('streaming');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Camera retries a current signing failure once and isolates a mutated HA user',async({page})=>{
 const card=await mount(page,{provider:'frigate_go2rtc',deferred:true});await page.clock.install();await open(card);await expect.poll(()=>page.evaluate(()=>window.cameraPlayers.at(-1)?.testOptions.source)).toBe('');await page.evaluate(()=>window.cameraRequests[0].reject(new Error('Temporary signing failure')));await expect.poll(()=>page.evaluate(()=>window.cameraCard._retryTimers.size)).toBe(1);await page.clock.runFor(400);await expect.poll(()=>page.evaluate(()=>window.cameraRequests.length)).toBe(2);await page.evaluate(()=>window.cameraRequests[1].resolve({path:'/signed/retry'}));await expect.poll(()=>page.evaluate(()=>window.cameraPlayers.at(-1).testOptions.source)).toBe('/signed/retry');expect(await page.evaluate(()=>window.cameraCard._retryTimers.size)).toBe(0);
 await page.evaluate(()=>{window.cameraHass.user.id='changed-in-place';window.cameraCard.hass=window.cameraHass;});await expect(card.locator('[role="dialog"]')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>window.cameraRequests.length)).toBe(2);expect(await page.evaluate(()=>window.cameraPlayers[0].testDisconnected)).toBe(true);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera portal keeps readable styles, owns stream events and removes its host on detach',async({page})=>{
 const card=await mount(page,{provider:'go2rtc',image:true});await page.evaluate(()=>{const card=window.cameraCard;const container=document.createElement('nodalia-room-summary-card');container.setConfig({});document.querySelector('#fixture').append(container);container.shadowRoot.append(card);});await open(card);const portal=page.locator('[data-nodalia-overlay-portal="camera"]');await expect(portal.locator('[role="dialog"]')).toBeVisible();expect(await portal.locator('.camera-card__expanded-panel').evaluate(node=>({position:getComputedStyle(node).position,radius:getComputedStyle(node).borderRadius,display:getComputedStyle(node).display}))).toMatchObject({position:'absolute',display:'grid'});
 await page.evaluate(()=>window.cameraPlayers.at(-1).dispatchEvent(new Event('nodalia-go2rtc-loaded')));await expect(portal.locator('[data-camera-poster]')).toBeHidden();await portal.locator('.camera-card__expanded-close').click();await expect(portal).toHaveCount(0);await open(card);await expect(portal).toHaveCount(1);await page.evaluate(()=>window.cameraCard.remove());await expect(portal).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Camera remounts playback and related controls into the current Summary portal on rerender',async({page})=>{
 const card=await mount(page,{provider:'go2rtc',image:true});await page.evaluate(()=>{const container=document.createElement('nodalia-room-summary-card');container.setConfig({});document.querySelector('#fixture').append(container);container.shadowRoot.append(window.cameraCard);window.cameraCard.setConfig({...window.cameraConfig,camera_actions:[{camera:'camera.one',entity:'lock.front',name:'Door',tap_action:'more-info'}]});window.cameraHass.states['lock.front']={entity_id:'lock.front',state:'locked',attributes:{friendly_name:'Door'}};window.cameraCard.hass={...window.cameraHass};});await open(card);const portal=page.locator('[data-nodalia-overlay-portal="camera"]');await expect(portal.locator('nodalia-go2rtc-player')).toHaveCount(1);await expect(portal.locator('nodalia-entity-card')).toHaveCount(1);
 await page.evaluate(()=>{window.cameraPreviousPlayer=window.cameraPlayers.at(-1);window.cameraCard.setConfig({...window.cameraCard._config,name:'Renamed camera'});});await expect(portal.locator('.camera-card__expanded-title')).toHaveText('Renamed camera');await expect(portal.locator('nodalia-go2rtc-player')).toHaveCount(1);await expect(portal.locator('nodalia-entity-card')).toHaveCount(1);expect(await page.evaluate(()=>window.cameraPreviousPlayer.testDisconnected)).toBe(true);
 await page.evaluate(()=>{window.cameraPreviousPlayer=window.cameraPlayers.at(-1);window.cameraCard.shadowRoot.querySelector('[data-camera-image]').dispatchEvent(new Event('error'));});await expect(portal.locator('nodalia-go2rtc-player')).toHaveCount(1);await expect(portal.locator('nodalia-entity-card')).toHaveCount(1);await expect.poll(()=>page.evaluate(()=>window.cameraPlayers.at(-1).testOptions.source)).toBe('https://go2rtc.example/api/ws?src=one');expect(await page.evaluate(()=>window.cameraPreviousPlayer.testDisconnected)).toBe(true);await page.evaluate(()=>window.cameraPlayers.at(-1).dispatchEvent(new Event('nodalia-go2rtc-loaded')));await expect(portal.locator('[data-camera-stream-status]')).toBeHidden();await portal.locator('.camera-card__expanded-close').click();await expect(portal).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
