import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-camera-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-camera-card').getConfigElement();editor.hass=window.makeHass({'camera.one':{state:'idle',attributes:{friendly_name:'Front'}},'camera.two':{state:'idle'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.cameraEditorFixture=editor;window.cameraEditorChanges=[];editor.addEventListener('config-changed',event=>window.cameraEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-camera-card-editor');}
test('Camera editor guards malformed rows and picker events while preserving missing selections, YAML fields and focus',async({page})=>{
 const editor=await mount(page,{entity:'camera.missing',cameras:['camera.missing'],camera_actions:[null,42,{camera:'camera.missing',entity:'lock.front',name:'Entry'}],expanded_actions:[null],camera_streams:[null,{camera:'camera.missing',provider:'iframe',url:'https://ha.example/player'}],camera_tap_actions:[null,{camera:'camera.missing',tap_action:'more-info'}],custom_extension:{value:7}});
 expect(await editor.locator('ha-entity-picker[data-field="entity"]').evaluate(node=>node.value)).toBe('camera.missing');
 await page.evaluate(()=>window.cameraEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['camera.bad']}})));expect(await page.evaluate(()=>window.cameraEditorChanges.at(-1))).toMatchObject({entity:"camera.missing",custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Entrance');await page.evaluate(()=>window.cameraEditorFixture.hass=window.makeHass({'camera.new':{state:'idle'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Entrance');await name.dispatchEvent('change');
 expect(await page.evaluate(()=>window.cameraEditorChanges.at(-1))).toMatchObject({entity:'camera.missing',custom_extension:{value:7},camera_actions:[{entity:'lock.front',name:'Entry'}],camera_streams:[{provider:'iframe',url:'https://ha.example/player'}]});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera editor moves streams and actions with a renamed camera and removes only valid selected rows',async({page})=>{
 const editor=await mount(page,{entity:'camera.one',cameras:['camera.one','camera.two'],camera_streams:[{camera:'camera.one',provider:'go2rtc',stream:'one',base_url:'https://ha.example:1984'},{camera:'camera.two',provider:'iframe',url:'https://ha.example/two'}],camera_actions:[{camera:'camera.one',entity:'lock.front',name:'Entry'}],camera_tap_actions:[{camera:'camera.one',tap_action:'service',tap_service:'camera.turn_on',tap_service_data:{flag:false,count:0},tap_service_target:{area_id:'front'}},{camera:'camera.two',tap_action:'more-info'}]});
 await page.evaluate(()=>{const editor=window.cameraEditorFixture;const node=editor.shadowRoot.querySelector('ha-entity-picker[data-field="cameras.0"]');node.dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:'camera.new'}}));});
 let config=await page.evaluate(()=>window.cameraEditorChanges.at(-1));expect(config).toMatchObject({entity:'camera.new',cameras:['camera.new','camera.two'],camera_streams:[{camera:'camera.new',stream:'new'},{camera:'camera.two',url:'https://ha.example/two'}],camera_actions:[{camera:'camera.new',entity:'lock.front'}],camera_tap_actions:[{camera:'camera.new',tap_service_data:'{"flag":false,"count":0}',tap_service_target:'{"area_id":"front"}'},{camera:'camera.two'}]});
 const before=await page.evaluate(()=>JSON.stringify(window.cameraEditorFixture._config));await page.evaluate(()=>{const editor=window.cameraEditorFixture;for(const action of ['remove-camera','remove-camera-action','remove-expanded-action'])for(const index of ['-1','','99','0.5']){const button=document.createElement('button');button.dataset.editorAction=action;button.dataset.index=index;editor.shadowRoot.append(button);button.click();button.remove();}});expect(await page.evaluate(()=>JSON.stringify(window.cameraEditorFixture._config))).toBe(before);
 await editor.locator('[data-editor-action="remove-camera"][data-index="0"]').click();config=await page.evaluate(()=>window.cameraEditorChanges.at(-1));expect(config).toMatchObject({entity:'camera.two',cameras:['camera.two'],camera_streams:[{camera:'camera.two',url:'https://ha.example/two'}],camera_tap_actions:[{camera:'camera.two'}]});expect(config.camera_actions??[]).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Camera editor retains draft camera rows and expanded actions before an entity is selected',async({page})=>{
 const editor=await mount(page,{entity:'camera.one'});await editor.locator('[data-editor-action="add-camera"]').click();expect(await editor.locator('ha-entity-picker[data-field="cameras.0"]').evaluate(node=>node.value)).toBe('camera.one');expect(await editor.locator('ha-entity-picker[data-field="cameras.1"]').evaluate(node=>node.value)).toBe('');await editor.locator('[data-editor-action="add-camera-action"]').click();expect(await editor.locator('ha-entity-picker[data-field="camera_actions.0.entity"]').evaluate(node=>node.value)).toBe('');
 await page.evaluate(()=>{const node=window.cameraEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-field="camera_actions.0.entity"]');node.dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:'lock.front'}}));});expect(await page.evaluate(()=>window.cameraEditorChanges.at(-1))).toMatchObject({camera_actions:[{entity:'lock.front'}]});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
