import {expect,test} from '@playwright/test';
async function mount(page,config,pickers=false,engine=null){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-climate-card'));
 await page.evaluate(async({config,pickers,engine})=>{if(pickers)for(const tag of ['ha-entity-picker','ha-icon-picker'])if(!customElements.get(tag))customElements.define(tag,class extends HTMLElement{constructor(){super();this.value='';this.hass=null;}});if(engine)window.NodaliaBackend={...window.NodaliaBackend,getEditorEngineStatus:async()=>engine};const editor=await customElements.get('nodalia-climate-card').getConfigElement();editor.hass=window.createHassFixture({entities:{'climate.one':{state:'heat',attributes:{friendly_name:'Bedroom'}},'climate.two':{state:'off'},'light.one':{state:'on'}},overrides:{connection:{},user:{id:'one',is_admin:true}}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.climateEditorFixture=editor;window.climateEditorChanges=[];editor.addEventListener('config-changed',event=>window.climateEditorChanges.push(event.detail.config));},{config,pickers,engine});return page.locator('nodalia-climate-card-editor');
}
test('Climate editor retains missing entities, focused drafts, explicit zero durations and translucent styles',async({page})=>{
 const editor=await mount(page,{entity:'climate.missing',name:'Heating',animations:{dial_duration:0},styles:{card:{background:'rgba(10, 20, 30, 0.3)'}},custom_extension:{flag:false,count:0}});
 await expect(editor.locator('select[data-field="entity"]')).toHaveValue('climate.missing');await expect(editor.locator('select[data-field="entity"] option[value="light.one"]')).toHaveCount(0);
 const name=editor.locator('input[data-field="name"]');await name.fill('New heating');await page.evaluate(()=>{const e=window.climateEditorFixture;e.hass={...e._hass,states:{...e._hass.states,'climate.new':{entity_id:'climate.new',state:'off',attributes:{}}}};});await expect(name).toBeFocused();await expect(name).toHaveValue('New heating');await name.dispatchEvent('change');
 await editor.locator('[data-editor-toggle="animations"]').click();const dial=editor.locator('input[data-field="animations.dial_duration"]');await expect(dial).toHaveValue('0');await dial.fill('');await dial.dispatchEvent('change');await expect(dial).toHaveValue('220');const config=await page.evaluate(()=>window.climateEditorChanges.at(-1));expect(config.animations?.dial_duration).toBeUndefined();expect(config.custom_extension).toEqual({flag:false,count:0});expect(config.name).toBe('New heating');expect(config.styles.card.background).toBe('rgba(10, 20, 30, 0.3)');
 await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.background"][type="color"]')).toHaveAttribute('data-alpha','0.3');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Climate editor uses committed HA picker values and exposes full-width independent action and display controls',async({page})=>{
 const editor=await mount(page,{entity:'climate.one',name:'Custom',haptics:null,animations:42,custom_extension:{enabled:false}},true);
 expect(await page.evaluate(()=>{const p=window.climateEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-field="entity"]');return {domains:p.includeDomains,light:p.entityFilter({entity_id:'light.one'})};})).toEqual({domains:['climate'],light:false});
 await page.evaluate(()=>{const e=window.climateEditorFixture;for(const [tag,field,value] of [['ha-entity-picker','entity','climate.two'],['ha-icon-picker','icon','mdi:fire']]){const p=e.shadowRoot.querySelector(`${tag}[data-field="${field}"]`);p.dispatchEvent(new CustomEvent('value-changed',{detail:{value},bubbles:true,composed:true}));}});
 await editor.locator('[data-editor-toggle="tap_actions"]').click();for(const field of ['tap_action','hold_action','double_tap_action'])await expect(editor.locator(`label.editor-field--full select[data-field="${field}"]`)).toHaveCount(1);
 await editor.locator('select[data-field="tap_action"]').selectOption('none');await editor.locator('select[data-field="double_tap_action"]').selectOption('more-info');await editor.locator('select[data-field="display.main_temperature"]').selectOption('current');await editor.locator('label:has(input[data-field="haptics.scrolls.temperature_dial"])').click();const config=await page.evaluate(()=>window.climateEditorChanges.at(-1));expect(config).toMatchObject({entity:'climate.two',name:'Custom',icon:'mdi:fire',tap_action:'none',double_tap_action:'more-info',display:{main_temperature:'current'},haptics:{scrolls:{temperature_dial:false}},custom_extension:{enabled:false}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Climate editor delegates schedule UI to the Engine while retaining populated legacy fallback fields and week selection',async({page})=>{
 const editor=await mount(page,{entity:'climate.one',setpoint_schedule_webhook:'my_webhook',setpoint_schedule_helper:'input_text.schedule',setpoint_schedule_week_starts_on:'sunday',security:{allow_webhooks_for_non_admin:true}},false,{available:true,version:'2.0.2',caps:{climateSchedules:true,climateOverrides:true}});
 await expect(editor.locator('.editor-engine-banner')).toHaveCount(1);await expect(editor.locator('input[data-field="setpoint_schedule_webhook"]')).toHaveCount(0);await expect(editor.locator('select[data-field="setpoint_schedule_week_starts_on"]')).toHaveValue('sunday');await editor.locator('select[data-field="setpoint_schedule_week_starts_on"]').selectOption('monday');let config=await page.evaluate(()=>window.climateEditorChanges.at(-1));expect(config.setpoint_schedule_webhook).toBe('my_webhook');expect(config.setpoint_schedule_helper).toBe('input_text.schedule');expect(config.security.allow_webhooks_for_non_admin).toBe(true);
 await page.evaluate(async()=>{const e=window.climateEditorFixture;window.NodaliaBackend.getEditorEngineStatus=async()=>({available:false,version:'',caps:{climateSchedules:false}});e.hass={...e._hass,connection:{}};await Promise.resolve();await Promise.resolve();});await expect(editor.locator('input[data-field="setpoint_schedule_webhook"]')).toHaveValue('my_webhook');await expect(editor.locator('input[data-field="setpoint_schedule_helper"]')).toHaveValue('input_text.schedule');await expect(editor.locator('select[data-field="setpoint_schedule_week_starts_on"]')).toHaveValue('monday');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Climate editor ignores obsolete Engine replies and preserves controls for unchanged cached Engine status',async({page})=>{
 await mount(page,{entity:'climate.one'},false,{available:false,version:'cached',caps:{climateSchedules:false}});await expect.poll(()=>page.evaluate(()=>window.climateEditorFixture._engineStatusInFlight)).toBe(false);
 const result=await page.evaluate(async()=>{const e=window.climateEditorFixture,control=e.shadowRoot.querySelector('input[data-field="name"]');e.hass={...e._hass};await Promise.resolve();await Promise.resolve();const unchanged=control===e.shadowRoot.querySelector('input[data-field="name"]');const replies=[];window.NodaliaBackend.getEditorEngineStatus=()=>new Promise(resolve=>replies.push(resolve));e.hass={...e._hass,connection:{}};e.hass={...e._hass,connection:{}};replies[0]({available:true,version:'obsolete',caps:{climateSchedules:true}});await Promise.resolve();const abandoned=e._engineStatus;replies[1]({available:false,version:'current',caps:{climateSchedules:false}});await Promise.resolve();await Promise.resolve();e.hass={...e._hass};e.remove();replies[2]({available:true,version:'detached',caps:{climateSchedules:true}});await Promise.resolve();await Promise.resolve();return {unchanged,abandoned,version:e._engineStatus?.version,inFlight:e._engineStatusInFlight};});expect(result).toEqual({unchanged:true,abandoned:null,version:'current',inFlight:false});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
