import {expect,test} from '@playwright/test';
async function mount(page,extra={},attributes={},state='heat') {
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-climate-card'));
 await page.evaluate(({extra,attributes,state})=>{
  window.ccCalls=[];window.ccDefer=false;
  window.ccConfig={entity:'climate.one',language:'en',animations:{enabled:false},haptics:{enabled:false},setpoint_schedule:{enabled:true,slots:[{id:'s',day:'mon',start:'08:00',end:'10:00',temperature:21,enabled:true}]},...extra};
  window.NodaliaBackend={...window.NodaliaBackend,status:async()=>({available:false,capabilities:[]})};
  window.ccHass=window.createHassFixture({entities:{'climate.one':{state,attributes:{friendly_name:'Heating',current_temperature:20,temperature:21,min_temp:7,max_temp:35,target_temp_step:.5,hvac_modes:['off','heat','cool','heat_cool'],supported_features:411,...attributes}},'climate.two':{state:'heat',attributes:{friendly_name:'Second',temperature:22,current_temperature:19,min_temp:7,max_temp:35,target_temp_step:.5,hvac_modes:['off','heat','cool']}}},overrides:{connection:{},user:{id:'one',is_admin:true},callService(domain,service,data,target){const row={domain,service,data,target};window.ccCalls.push(row);return window.ccDefer?new Promise((resolve,reject)=>Object.assign(row,{resolve,reject})):Promise.resolve();}}});
  const card=document.createElement('nodalia-climate-card');card.setConfig(window.ccConfig);card.hass=window.ccHass;document.querySelector('#fixture').append(card);window.ccCard=card;
 },{extra,attributes,state});return page.locator('nodalia-climate-card');
}
const calls=page=>page.evaluate(()=>window.ccCalls.map(({domain,service,data,target})=>({domain,service,data,target})));
const clean=async page=>expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
test('Climate native step keyboard focus survives HA updates with real zero and changing capability attributes',async({page})=>{
 const card=await mount(page,{layout:'compact'},{temperature:0,current_temperature:0});const increase=card.locator('[data-climate-action="increase"]');await increase.focus();await page.evaluate(()=>{window.ccHass.states['climate.one'].attributes.current_temperature=1;window.ccCard.hass={...window.ccHass};});await expect(increase).toBeFocused();await increase.press('Enter');await expect.poll(()=>page.evaluate(()=>window.ccCalls.length)).toBe(1);expect((await calls(page))[0].data).toMatchObject({entity_id:'climate.one',temperature:7});await page.evaluate(()=>{window.ccHass.states['climate.one'].attributes.target_temp_step=1;window.ccHass.states['climate.one'].attributes.max_temp=40;window.ccCard.hass=window.ccHass;});await expect(card.locator('[data-climate-compact-field="temperature"]')).toHaveAttribute('max','40');await clean(page);
});
test('Climate cancels single and dual dial previews on pointer cancellation and blur without committing',async({page})=>{
 const card=await mount(page);const hit=card.locator('[data-climate-control="dial-hit"]').first();await hit.dispatchEvent('pointerdown',{pointerId:51,clientX:250,clientY:160,button:0,isPrimary:true});expect(await page.evaluate(()=>window.ccCard._activeDialDrag!==null)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:51})));expect(await page.evaluate(()=>window.ccCard._draftTemperature.size)).toBe(0);expect(await calls(page)).toEqual([]);
 await page.evaluate(()=>{window.ccHass.states['climate.one'].state='heat_cool';Object.assign(window.ccHass.states['climate.one'].attributes,{temperature:null,hvac_mode:'heat_cool',target_temp_low:18,target_temp_high:24});window.ccCard.hass={...window.ccHass};});await card.locator('[data-climate-control="dial-range-low"]').dispatchEvent('pointerdown',{pointerId:52,clientX:200,clientY:170,button:0,isPrimary:true});await page.evaluate(()=>{window.dispatchEvent(new PointerEvent('pointermove',{pointerId:52,clientX:250,clientY:200}));window.dispatchEvent(new Event('blur'));});expect(await page.evaluate(()=>({drag:window.ccCard._activeDialDrag,drafts:window.ccCard._draftTempRange.size,frame:window.ccCard._dialDragFrame}))).toEqual({drag:null,drafts:0,frame:0});expect(await calls(page)).toEqual([]);await clean(page);
});
test('Climate schedule native drag retains pointer capture and cancellation restores the original slot',async({page})=>{
 const card=await mount(page);await card.locator('[data-climate-action="schedule-open"]').press('Enter');const block=card.locator('[data-schedule-block-id="s"]');await expect(block).toBeVisible();const box=await block.boundingBox();await page.evaluate(()=>{window.ccOriginal=JSON.stringify(window.ccCard._scheduleComposerDraft.slots);const track=window.ccCard.shadowRoot.querySelector('[data-schedule-day-track="mon"]');window.ccTrack=track;track.addEventListener('pointerdown',event=>window.ccPointerId=event.pointerId,{once:true});});await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2,{steps:5});expect(await page.evaluate(()=>window.ccTrack.hasPointerCapture(window.ccPointerId))).toBe(true);expect(await page.evaluate(()=>JSON.stringify(window.ccCard._scheduleComposerDraft.slots)!==window.ccOriginal)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:window.ccPointerId})));await page.mouse.up();expect(await page.evaluate(()=>JSON.stringify(window.ccCard._scheduleComposerDraft.slots)===window.ccOriginal)).toBe(true);expect(await calls(page)).toEqual([]);await clean(page);
});
test('Climate composer focused fields keep unfinished values and caret through HA refreshes',async({page})=>{
 const card=await mount(page);await card.locator('[data-climate-action="schedule-open"]').press('Enter');await card.locator('[data-schedule-block-id="s"]').click();const input=card.locator('input[data-climate-schedule-field="temperature"][data-schedule-slot-id="s"]');await input.fill('22.5');await page.evaluate(()=>{window.ccHass.states['climate.one'].attributes.current_temperature=23;window.ccCard.hass={...window.ccHass};});await expect(input).toBeFocused();await expect(input).toHaveValue('22.5');await input.dispatchEvent('change');expect(await page.evaluate(()=>window.ccCard._scheduleComposerDraft.slots.find(slot=>slot.id==='s').temperature)).toBe(22.5);await clean(page);
});
test('Climate rejects retired Engine status before issuing a schedule read on a replacement user',async({page})=>{
 const card=await mount(page);await page.evaluate(()=>{window.ccStatus=[];window.ccReads=[];window.NodaliaBackend.status=hass=>new Promise(resolve=>window.ccStatus.push({hass,resolve}));window.NodaliaBackend.getClimateSchedule=(hass,entity)=>{window.ccReads.push({hass,entity});return Promise.resolve({schedule:{slots:[]}});};window.ccCard._openScheduleComposer();window.ccHass.user.id='second';window.ccCard.hass=window.ccHass;window.ccStatus[0].resolve({available:true,capabilities:['climate_schedules']});});await expect.poll(()=>page.evaluate(()=>window.ccCard._scheduleComposerOpen)).toBe(false);expect(await page.evaluate(()=>window.ccReads.length)).toBe(0);await expect(card.locator('.climate-schedule-expanded')).toHaveAttribute('aria-hidden','true');await clean(page);
});
test('Climate retired native save cannot close a replacement composer or trigger legacy helper writes',async({page})=>{
 const card=await mount(page,{setpoint_schedule_webhook:'save',setpoint_schedule_helper:'input_text.schedule'});await page.evaluate(()=>{window.NodaliaBackend.status=async()=>({available:true,capabilities:['climate_schedules']});window.NodaliaBackend.setClimateSchedule=()=>new Promise((resolve,reject)=>{window.ccSave={resolve,reject};});});await card.locator('[data-climate-action="schedule-open"]').press('Enter');await card.locator('[data-climate-action="schedule-save"]').press('Enter');await expect.poll(()=>page.evaluate(()=>Boolean(window.ccSave))).toBe(true);await page.evaluate(()=>{window.ccCard.setConfig({...window.ccConfig,entity:'climate.two'});window.NodaliaBackend.status=async()=>({available:false,capabilities:[]});window.ccCard._openScheduleComposer();window.ccCard._scheduleComposerError='replacement';window.ccSave.reject(new Error('retired save'));});await expect.poll(()=>page.evaluate(()=>window.ccCard._scheduleComposerSaving)).toBe(false);expect(await page.evaluate(()=>({open:window.ccCard._scheduleComposerOpen,error:window.ccCard._scheduleComposerError}))).toEqual({open:true,error:'replacement'});expect(await calls(page)).toEqual([]);await clean(page);
});
test('Climate retires deferred HVAC wake before sending a temperature to a different entity or user',async({page})=>{
 const card=await mount(page,{}, {temperature:null,target_temp_low:null,target_temp_high:null},'off');await page.evaluate(()=>window.ccDefer=true);await card.locator('[data-climate-action="increase"]').press('Enter');await expect.poll(()=>page.evaluate(()=>window.ccCalls.length)).toBe(1);expect((await calls(page))[0].service).toBe('set_hvac_mode');await page.evaluate(()=>{window.ccCard.setConfig({...window.ccConfig,entity:'climate.two'});window.ccHass.user.id='second';window.ccCard.hass=window.ccHass;window.ccCalls[0].resolve();});expect((await calls(page)).map(row=>row.service)).toEqual(['set_hvac_mode']);expect(await page.evaluate(()=>({drafts:window.ccCard._draftTemperature.size,inFlight:window.ccCard._temperatureCommitInFlight,timers:window.ccCard._timers.size}))).toEqual({drafts:0,inFlight:false,timers:0});await clean(page);
});
test('Climate old range rejection cannot overwrite the replacement temperature queue',async({page})=>{
 await mount(page,{}, {temperature:null,hvac_mode:'heat_cool',target_temp_low:18,target_temp_high:24},'heat_cool');await page.evaluate(()=>{window.ccDefer=true;window.ccCard._queueRangeCommit({low:19,high:25},{immediate:true,render:false});window.ccCard.setConfig({...window.ccConfig,entity:'climate.two'});window.ccCard._queueTemperatureCommit(23,{immediate:true,render:false});window.ccCalls[0].reject(new Error('old range'));});expect(await page.evaluate(()=>({inFlight:window.ccCard._temperatureCommitInFlight,range:window.ccCard._rangeCommitQueuedValue,draft:window.ccCard._draftTemperature.get('climate.two')}))).toEqual({inFlight:true,range:null,draft:23});await page.evaluate(()=>window.ccCalls[1].resolve());await clean(page);
});
test('Climate retired webhook reply cannot write the shared helper in a new HA context',async({page})=>{
 const card=await mount(page,{setpoint_schedule_webhook:'save',setpoint_schedule_helper:'input_text.schedule',security:{allow_webhooks_for_non_admin:true}});await page.evaluate(()=>{window.NodaliaUtils.postHomeAssistantWebhook=()=>new Promise(resolve=>window.ccWebhook=resolve);});await card.locator('[data-climate-action="schedule-open"]').press('Enter');await card.locator('[data-climate-action="schedule-save"]').press('Enter');await expect.poll(()=>page.evaluate(()=>typeof window.ccWebhook)).toBe('function');await page.evaluate(()=>{window.ccHass={...window.ccHass,connection:{},user:{id:'second',is_admin:false}};window.ccCard.hass=window.ccHass;window.ccWebhook(true);});expect(await calls(page)).toEqual([]);expect(await page.evaluate(()=>window.ccCard._scheduleComposerOpen)).toBe(false);await clean(page);
});
test('Climate detachment clears native frames, timers, gestures and pending override feedback through reconnect',async({page})=>{
 await mount(page);await page.clock.install();await page.evaluate(()=>{window.NodaliaBackend.clearClimateOverride=()=>new Promise(resolve=>window.ccOverride=resolve);window.ccCard._clearEngineOverride();window.ccCard._scheduleEntranceAnimationReset(600);window.ccCard._restoreScheduleAgendaScrollState(20);window.ccCard._queueTemperatureCommit(23,{render:false});window.ccCard.remove();document.querySelector('#fixture').append(window.ccCard);window.ccOverride({ok:true});});expect(await page.evaluate(()=>({timers:window.ccCard._timers.size,frames:window.ccCard._frames.size,busy:window.ccCard._engineOverrideBusy,draft:window.ccCard._draftTemperature.size,drag:window.ccCard._activeDialDrag}))).toEqual({timers:0,frames:0,busy:false,draft:0,drag:null});await page.clock.runFor(2000);expect(await calls(page)).toEqual([]);await clean(page);
});

test('Climate unavailable entities retire pending dial work and queued commits without commands',async({page})=>{
 const card=await mount(page);await page.clock.install();await card.locator('[data-climate-control="dial-hit"]').first().dispatchEvent('pointerdown',{pointerId:61,clientX:250,clientY:160,button:0,isPrimary:true});await page.evaluate(()=>{window.ccCard._queueTemperatureCommit(23,{render:false});window.ccHass.states['climate.one'].state='unavailable';window.ccCard.hass={...window.ccHass};});await page.clock.runFor(2000);expect(await page.evaluate(()=>({drag:window.ccCard._activeDialDrag,drafts:window.ccCard._draftTemperature.size,timers:window.ccCard._timers.size}))).toEqual({drag:null,drafts:0,timers:0});expect(await calls(page)).toEqual([]);await clean(page);
});
