import {expect,test} from '@playwright/test';
async function mount(page,config={}){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-cover-card'));await page.evaluate(config=>{const card=document.createElement('nodalia-cover-card');card.setConfig({entity:'cover.one',...config});window.coverCalls=[];const hass=window.makeHass({'cover.one':{state:'open',attributes:{current_position:50,current_tilt_position:25,supported_features:255}},'cover.two':{state:'closed',attributes:{current_position:0,supported_features:255}}});hass.callService=(...args)=>{window.coverCalls.push(args);return Promise.resolve();};window.coverHassFixture=hass;card.hass=hass;document.querySelector('#fixture').append(card);window.coverCardFixture=card;},config);return page.locator('nodalia-cover-card');}
for(const layout of ['compact','circular'])test(`Cover ${layout} cancels pointer drags without a command and shows the newest HA value`,async({page})=>{
 const card=await mount(page,{layout});await page.evaluate(layout=>{const card=window.coverCardFixture;const node=card.shadowRoot.querySelector(layout==='circular'?'.fan-card__circular-dial':'input[data-cover-control="position"]');const rect=node.getBoundingClientRect();node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:7,button:0,clientX:rect.right,clientY:rect.top+rect.height/2}));const hass=window.coverHassFixture;hass.states['cover.one']={...hass.states['cover.one'],attributes:{...hass.states['cover.one'].attributes,current_position:60}};card.hass=hass;window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7,clientX:rect.right,clientY:rect.top+rect.height/2}));window.dispatchEvent(new PointerEvent('pointerup',{pointerId:7,clientX:rect.right,clientY:rect.top+rect.height/2}));},layout);
 await expect(card.locator('[data-cover-chip="position"]')).toHaveText(layout==='circular'?['60%','60%']:['60%']);expect(await page.evaluate(()=>({calls:window.coverCalls,drag:window.coverCardFixture._activeSliderDrag,listeners:window.coverCardFixture._dragWindowListenersAttached}))).toEqual({calls:[],drag:null,listeners:false});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Cover reconfiguration abandons the old drag and clears consumed taps; service failures retain explicit targets',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));const card=await mount(page);
 await page.evaluate(()=>{const card=window.coverCardFixture,slider=card.shadowRoot.querySelector('input[data-cover-control="position"]'),rect=slider.getBoundingClientRect();slider.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:8,button:0,clientX:rect.right}));card._suppressNextCoverTap=true;card.setConfig({entity:'cover.two',tap_action:'service',tap_service:'cover.open_cover',tap_service_data:{position:0,flag:false},tap_service_target:{area_id:'living'},security:{allowed_services:['cover.open_cover']}});window.dispatchEvent(new PointerEvent('pointerup',{pointerId:8,clientX:rect.right}));window.coverHassFixture.callService=(...args)=>{window.coverCalls.push(args);return Promise.reject(new Error('offline'));};});
 expect(await page.evaluate(()=>window.coverCalls)).toEqual([]);await card.locator('button[data-cover-action="icon"]').click();expect(await page.evaluate(()=>window.coverCalls)).toEqual([['cover','open_cover',{position:0,flag:false},{area_id:'living'}]]);
 await page.evaluate(()=>{window.NodaliaUtils.invokeHomeAssistantService=undefined;window.coverHassFixture.callService=()=>{throw new Error('offline synchronously');};});await card.locator('button[data-cover-action="icon"]').press('Enter');expect(errors).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Cover touch cancellation and disconnect release fallback work; finite controls still commit normally after remount',async({page})=>{
 const card=await mount(page);const released=await page.evaluate(()=>{const card=window.coverCardFixture;card._hasPointerEvents=()=>false;const slider=card.shadowRoot.querySelector('input[data-cover-control="position"]'),rect=slider.getBoundingClientRect();card._startSliderDrag(slider,rect.right);window.dispatchEvent(new Event('touchcancel'));const cancelled={drag:card._activeSliderDrag,listeners:card._dragWindowListenersAttached};const schedule=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerButtonBounce(card.shadowRoot.querySelector('[data-cover-action="icon"]'));window.NodaliaUtils.scheduleDeferTimer=schedule;card._startSliderDrag(slider,rect.right);card.remove();const timers=card._fallbackAnimationTimers.size;document.querySelector('#fixture').append(card);const current=card.shadowRoot.querySelector('input[data-cover-control="position"]');card._applySliderValue(current,Infinity,{commit:true});return{cancelled,timers,drag:card._activeSliderDrag,calls:window.coverCalls};});
 expect(released).toEqual({cancelled:{drag:null,listeners:false},timers:0,drag:null,calls:[]});
 await page.evaluate(()=>{const slider=window.coverCardFixture.shadowRoot.querySelector('input[data-cover-control="position"]');slider.value='75';slider.dispatchEvent(new Event('change',{bubbles:true,composed:true}));});expect(await page.evaluate(()=>window.coverCalls)).toEqual([['cover','set_cover_position',{entity_id:'cover.one',position:75}]]);await expect(card.locator('[data-cover-chip="position"]')).toHaveText('75%');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Cover inherited icon URLs and navigation use body parameters while an explicit icon action wins',async({page})=>{
 const card=await mount(page,{tap_action:'url',tap_url:'https://ha.example/body',tap_new_tab:true});
 await page.evaluate(()=>{window.coverOpened=[];window.open=(...args)=>window.coverOpened.push(args);});await card.locator('button[data-cover-action="icon"]').click();
 await page.evaluate(()=>window.coverCardFixture.setConfig({entity:'cover.one',tap_action:'url',tap_url:'https://ha.example/body',icon_tap_action:'url',icon_tap_url:'https://ha.example/icon'}));await card.locator('button[data-cover-action="icon"]').click();
 expect(await page.evaluate(()=>window.coverOpened)).toEqual([['https://ha.example/body','_blank','noopener,noreferrer'],['https://ha.example/icon','_self','noopener,noreferrer']]);
 await page.evaluate(()=>window.coverCardFixture.setConfig({entity:'cover.one',tap_action:'navigate',navigation_path:'/lovelace/cover'}));await card.locator('button[data-cover-action="icon"]').click();await expect(page).toHaveURL(/\/lovelace\/cover$/);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
