import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-cover-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-cover-card').getConfigElement();editor.hass=window.makeHass({'cover.one':{state:'open'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.coverEditorFixture=editor;window.coverEditorChanges=[];editor.addEventListener('config-changed',event=>window.coverEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-cover-card-editor');}
test('Cover editor preserves unavailable entities, focus and YAML fields while rejecting malformed events and nested settings',async({page})=>{
 const editor=await mount(page,{entity:'cover.missing',custom_extension:{value:7},haptics:{scrolls:42},animations:null,security:null});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('cover.missing');await page.evaluate(()=>window.coverEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['cover.bad']}})));expect(await page.evaluate(()=>window.coverEditorChanges.at(-1))).toMatchObject({entity:'cover.missing',custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Blind');await page.evaluate(()=>window.coverEditorFixture.hass=window.makeHass({'cover.new':{state:'closed'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Blind');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Cover editor clears numeric overrides to defaults and retains separate body/icon actions and translucent styles',async({page})=>{
 const editor=await mount(page,{entity:'cover.one',tap_action:'more-info',icon_tap_action:'service',icon_tap_service:'cover.open_cover',hold_action:'navigate',hold_navigation_path:'/lovelace/home',icon_hold_action:'url',icon_hold_url:'https://ha.example',animations:{power_duration:900},styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.power_duration"]');await expect(duration).toHaveValue('900');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('600');const config=await page.evaluate(()=>window.coverEditorChanges.at(-1));expect(config).toMatchObject({tap_action:'more-info',icon_tap_action:'service',icon_tap_service:'cover.open_cover',hold_action:'navigate',hold_navigation_path:'/lovelace/home',icon_hold_action:'url',icon_hold_url:'https://ha.example',styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});expect(config.animations?.power_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
