import {expect,test} from '@playwright/test';
for(const domain of ['fan','humidifier']){
 async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(domain=>customElements.get(`nodalia-${domain}-card`),domain);await page.evaluate(async({domain,config})=>{const editor=await customElements.get(`nodalia-${domain}-card`).getConfigElement();editor.hass=window.makeHass({[`${domain}.one`]:{state:'on',attributes:{friendly_name:'Comfort',preset_modes:['Auto','Boost'],available_modes:['Auto','Sleep']}},'select.mode':{state:'Auto',attributes:{options:['Auto','Sleep']}},'select.speed':{state:'Low',attributes:{options:['Low','High']}}});editor.setConfig({entity:`${domain}.one`,...config});document.querySelector('#fixture').append(editor);window.comfortEditorFixture=editor;window.comfortEditorChanges=[];editor.addEventListener('config-changed',event=>window.comfortEditorChanges.push(event.detail.config));},{domain,config});return page.locator(`nodalia-${domain}-card-editor`);}
 test(`${domain} editor guards malformed settings and retains native mode visibility, YAML and focus`,async({page})=>{
  const editor=await mount(page,{haptics:{scrolls:42},animations:null,security:null,custom_extension:{value:7},...(domain==='humidifier'?{mode_entity:'select.mode',fan_mode_entity:'select.speed'}:{})});await editor.locator('label:has(input[data-mode-value="Auto"])').click();await expect(editor.locator('input[data-mode-value="Auto"]')).not.toBeChecked();let config=await page.evaluate(()=>window.comfortEditorChanges.at(-1));expect(config).toMatchObject({custom_extension:{value:7},[domain==='fan'?'hidden_preset_modes':'hidden_modes']:['Auto']});await editor.locator('label:has(input[data-mode-value="Auto"])').click();await expect(editor.locator('input[data-mode-value="Auto"]')).toBeChecked();config=await page.evaluate(()=>window.comfortEditorChanges.at(-1));expect(config[domain==='fan'?'hidden_preset_modes':'hidden_modes']).toBeUndefined();
  const name=editor.locator('input[data-field="name"]');await name.fill('Comfort');await page.evaluate(domain=>window.comfortEditorFixture.hass=window.makeHass({[`${domain}.two`]:{state:'off'}}),domain);await expect(name).toBeFocused();await expect(name).toHaveValue('Comfort');await expect(editor.locator('select[data-field="entity"]')).toHaveValue(`${domain}.one`);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
 });
 test(`${domain} service action editor mounts data textareas and preserves explicit targets and translucent styles`,async({page})=>{
  const editor=await mount(page,{tap_action:'service',tap_service:`${domain}.turn_on`,tap_service_data:{flag:false,count:0},tap_service_target:{area_id:'living'},hold_action:'service',hold_service:`${domain}.turn_off`,hold_service_data:{flag:false},security:{allowed_services:[`${domain}.turn_on`,`${domain}.turn_off`]},animations:{power_duration:900},styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});await editor.locator('[data-editor-toggle="tap_actions"]').click();const data=editor.locator('textarea[data-field="tap_service_data"]');await expect(data).toHaveValue('{"flag":false,"count":0}');await expect(editor.locator('textarea[data-field="hold_service_data"]')).toHaveValue('{"flag":false}');await data.fill('{"flag":false,"count":0,"extra":true}');await data.dispatchEvent('change');await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.power_duration"]');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('600');const config=await page.evaluate(()=>window.comfortEditorChanges.at(-1));expect(config).toMatchObject({tap_action:'service',tap_service_data:'{"flag":false,"count":0,"extra":true}',tap_service_target:'{"area_id":"living"}',hold_service_data:'{"flag":false}',styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});expect(config.animations?.power_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
 });
}
