import {expect,test} from '@playwright/test';
// Exercise real touch events in desktop engines as well as mobile Safari.
test.use({hasTouch:true});
async function mount(page,config={},states={}){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-fan-card'));
 await page.evaluate(({config,states})=>{
  window.fanCalls=[];window.fanHaptics=[];
  window.fanStates={'fan.one':{state:'on',attributes:{friendly_name:'Fan',percentage:50,percentage_step:5,preset_mode:'Low',preset_modes:['Low','High','Auto'],oscillating:false,supported_features:3}},'fan.two':{state:'on',attributes:{friendly_name:'Second',percentage:20,percentage_step:5}},...states};
  window.fanHass=window.createHassFixture({entities:window.fanStates,overrides:{callService(...args){window.fanCalls.push(args);return Promise.resolve();}}});
  const card=document.createElement('nodalia-fan-card');card.setConfig({entity:'fan.one',compact_layout_mode:'never',language:'en',animations:{enabled:false},...config});card.hass=window.fanHass;card.addEventListener('haptic',event=>window.fanHaptics.push(event.detail));document.querySelector('#fixture').append(card);window.fanCard=card;
 },{config,states});return page.locator('nodalia-fan-card');
}
test('Fan cancels linear/circular pointer and touch drags without sending a speed, including entity changes',async({page})=>{
 const card=await mount(page);
 const result=await page.evaluate(()=>{const card=window.fanCard;const slider=card.shadowRoot.querySelector('input[type="range"]');const rect=slider.getBoundingClientRect();card._startSliderDrag(slider,rect.left+rect.width*.8,null,7);window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7,clientX:rect.right}));return{calls:window.fanCalls.length,drag:card._activeSliderDrag,listeners:card._dragWindowListenersAttached,draft:card._draftPercentage.size};});expect(result).toEqual({calls:0,drag:null,listeners:false,draft:0});
 await page.evaluate(()=>{const card=window.fanCard;const slider=card.shadowRoot.querySelector('input[type="range"]');const rect=slider.getBoundingClientRect();card._startSliderDrag(slider,rect.left+rect.width*.7,null,8);card.setConfig({entity:'fan.two',compact_layout_mode:'never',animations:{enabled:false}});card.hass=window.fanHass;window.dispatchEvent(new PointerEvent('pointerup',{pointerId:8,clientX:rect.right}));});expect(await page.evaluate(()=>window.fanCalls)).toEqual([]);await expect(card.locator('input[type="range"]')).toHaveValue('20');
 await page.evaluate(()=>{const card=window.fanCard;card.setConfig({entity:'fan.one',layout:'circular',animations:{enabled:false}});card.hass=window.fanHass;const dial=card.shadowRoot.querySelector('.fan-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,9);window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:9,clientX:rect.left,clientY:rect.top}));});expect(await page.evaluate(()=>({calls:window.fanCalls.length,drag:window.fanCard._activeSliderDrag,draft:window.fanCard._draftPercentage.size}))).toEqual({calls:0,drag:null,draft:0});
 await page.evaluate(()=>{const card=window.fanCard;const dial=card.shadowRoot.querySelector('.fan-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,null);card._onWindowTouchEnd(new TouchEvent('touchcancel'));});expect(await page.evaluate(()=>window.fanCalls)).toEqual([]);
 await page.evaluate(()=>{const card=window.fanCard;const dial=card.shadowRoot.querySelector('.fan-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,null);card._onWindowTouchStartCapture(new TouchEvent('touchstart'));});expect(await page.evaluate(()=>({calls:window.fanCalls.length,drag:window.fanCard._activeSliderDrag,draft:window.fanCard._draftPercentage.size}))).toEqual({calls:0,drag:null,draft:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Fan keeps optimistic toggle and visual-settle deadlines across unchanged HA updates',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 await mount(page);await page.evaluate(()=>window.fanCard._toggleFan(window.fanCard._getState()));expect(await page.evaluate(()=>window.fanCard._optimisticToggle.expectedState)).toBe('off');
 await page.clock.fastForward(3000);await page.evaluate(()=>window.fanCard.hass=window.fanHass);await page.clock.fastForward(199);expect(await page.evaluate(()=>window.fanCard._optimisticToggle.expectedState)).toBe('off');await page.clock.fastForward(1);expect(await page.evaluate(()=>window.fanCard._optimisticToggle)).toBe(null);
 await page.evaluate(()=>{window.fanStates['fan.one'].state='off';window.fanCard.hass=window.createHassFixture({entities:window.fanStates,overrides:{callService:window.fanHass.callService}});window.fanCard._toggleFan(window.fanCard._getState());window.fanStates['fan.one'].state='on';window.fanStates['fan.one'].attributes.percentage=0;window.fanCard.hass=window.createHassFixture({entities:window.fanStates,overrides:{callService:window.fanHass.callService}});});expect(await page.evaluate(()=>window.fanCard._getPercentage(window.fanCard._getState()))).toBe(50);
 await page.clock.fastForward(400);await page.evaluate(()=>window.fanCard.hass={...window.fanCard._hass});await page.clock.fastForward(19);expect(await page.evaluate(()=>window.fanCard._optimisticVisualSettle)).not.toBe(null);await page.clock.fastForward(1);expect(await page.evaluate(()=>window.fanCard._optimisticVisualSettle)).toBe(null);expect(await page.evaluate(()=>window.fanCard._getPercentage(window.fanCard._getState()))).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Fan owns fallback and panel animation work, resets detached interactions and guards stored memory',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 await mount(page,{animations:{enabled:true}});
 const cleanup=await page.evaluate(()=>{const card=window.fanCard;card._setPresetPanelVisibility(true);const panel=card.shadowRoot.querySelector('.fan-card__preset-panel-shell');panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));const finished=card._panelAnimationCancels.size;card._setPresetPanelVisibility(false);card._setPresetPanelVisibility(true);const original=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerButtonBounce(card.shadowRoot.querySelector('button'));window.NodaliaUtils.scheduleDeferTimer=original;const scheduled=card._fallbackTimers.size;card._suppressNextFanTap=true;card.remove();panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));return{finished,scheduled,timers:card._fallbackTimers.size,listeners:card._panelAnimationCancels.size,tap:card._suppressNextFanTap,frame:card._resizeFrame};});expect(cleanup.finished).toBe(0);expect(cleanup.scheduled).toBeGreaterThan(0);expect(cleanup.timers).toBe(0);expect(cleanup.listeners).toBe(0);expect(cleanup.tap).toBe(false);expect(cleanup.frame).toBe(0);
 const memory=await page.evaluate(()=>{const key='nodalia-fan-card:last-visual-state:v1';const card=window.fanCard;const results=[];for(const value of ['null','[]','false','{"fan.one":{"attributes":[]}}','{"fan.one":{"attributes":{"percentage":0},"last_changed":3}}']){localStorage.setItem(key,value);results.push(card._getStoredFanSnapshot('fan.one'));}return results;});expect(memory.slice(0,4)).toEqual([null,null,null,null]);expect(memory[4].attributes.percentage).toBe(0);expect(typeof memory[4].last_changed).toBe('string');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Fan keyboard actions retain target/data values, catch HA failures and respect disabled slider haptics',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));const card=await mount(page,{tap_action:'service',tap_service:'fan.set_percentage',tap_service_data:{percentage:0,flag:false},tap_service_target:{area_id:'living'},security:{allowed_services:['fan.set_percentage']},haptics:{scrolls:{percentage:false}}});
 await card.locator('ha-card[data-fan-action="body"]').press('Enter');expect(await page.evaluate(()=>window.fanCalls.at(-1))).toEqual(['fan','set_percentage',{percentage:0,flag:false},{area_id:'living'}]);
 await page.evaluate(()=>{window.fanHaptics=[];const slider=window.fanCard.shadowRoot.querySelector('input[type="range"]');window.fanCard._applySliderValue(slider,70,{commit:false});window.fanCard._applySliderValue(slider,75,{commit:true});});expect(await page.evaluate(()=>window.fanHaptics)).toEqual([]);
 await page.evaluate(()=>{window.fanCard._hass.callService=()=>Promise.reject(new Error('offline'));window.fanCard._setFanState('turn_on');window.fanCard._callConfiguredService('fan.set_percentage','fan.one',{percentage:0,flag:false},{area_id:'living'});});await page.evaluate(()=>{window.fanCard._hass.callService=()=>{throw new Error('sync offline');};window.fanCard._setFanState('turn_off');window.fanCard._callConfiguredService('fan.set_percentage');});expect(errors).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
