import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-fav-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-fav-card').getConfigElement();editor.hass=window.makeHass({'alarm_control_panel.home':{state:'disarmed',attributes:{friendly_name:'Home'}},'input_text.pin':{state:'0123'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.favEditorFixture=editor;window.favEditorEmitted=[];editor.addEventListener('config-changed',event=>window.favEditorEmitted.push(event.detail.config));},config);return page.locator('nodalia-fav-card-editor');}
test('Fav editor retains alarm PIN/helper and YAML extensions while toggling information-only actions',async({page})=>{
 const editor=await mount(page,{entity:'alarm_control_panel.home',entity_mode:'alarm_control_panel',alarm_code:'0123',alarm_code_entity:'input_text.pin',custom_extension:{value:7}});await expect(editor.locator('input[data-field="alarm_code"]')).toHaveValue('0123');await expect(editor.locator('select[data-field="alarm_code_entity"]')).toHaveValue('input_text.pin');await editor.locator('[data-editor-toggle="tap_actions"]').click();const info=editor.locator('input[data-field="__info_only"]');await info.check({force:true});expect(await page.evaluate(()=>window.favEditorEmitted.at(-1))).toMatchObject({tap_action:'none',alarm_code:'0123',alarm_code_entity:'input_text.pin',custom_extension:{value:7}});await info.uncheck({force:true});expect(await page.evaluate(()=>window.favEditorEmitted.at(-1).tap_action)).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Fav fallback picker retains an unavailable selected entity and guards malformed events while focus survives HA metadata refresh',async({page})=>{
 const editor=await mount(page,{entity:'sensor.missing',haptics:42,security:null});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('sensor.missing');await page.evaluate(()=>{window.favEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['sensor.invalid']}}));});expect(await page.evaluate(()=>window.favEditorEmitted.at(-1).entity)).toBe('sensor.missing');
 const name=editor.locator('input[data-field="name"]');await name.fill('Favourite');await page.evaluate(()=>{window.favEditorFixture.hass=window.makeHass({'sensor.new':{state:'1',attributes:{friendly_name:'New sensor'}}});});await expect(name).toBeFocused();await expect(name).toHaveValue('Favourite');await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.padding"]')).toHaveValue('10px 12px');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
