import {expect,test} from '@playwright/test';
async function mount(page,config={}){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-circular-gauge-card'));await page.evaluate(config=>{const card=document.createElement('nodalia-circular-gauge-card');card.setConfig({entity:'sensor.one',min:0,max:100,language:'en',animations:{content_duration:140},...config});card.hass=window.makeHass({'sensor.one':{state:'10',attributes:{unit_of_measurement:'W'}}});document.querySelector('#fixture').append(card);window.gaugeLifecycleCard=card;},config);return page.locator('nodalia-circular-gauge-card');}
test('Gauge live updates keep the original entrance deadline and finalize the latest progress',async({page})=>{
 const card=await mount(page);const result=await page.evaluate(()=>{const card=window.gaugeLifecycleCard;const deadline=card._entranceAnimationResetTimer;for(const value of [20,30,50,80])card.hass=window.makeHass({'sensor.one':{state:String(value),attributes:{unit_of_measurement:'W'}}});return{deadline,stable:deadline===card._entranceAnimationResetTimer,ratio:card._lastGaugeVisualState.ratio};});expect(result.deadline).toBeGreaterThan(0);expect(result.stable).toBe(true);expect(result.ratio).toBe(0.8);
 await expect.poll(()=>page.evaluate(()=>window.gaugeLifecycleCard._animateContentOnNextRender)).toBe(false);await expect(card.locator('.gauge-card__dial')).not.toHaveClass(/entrance-progress/);await expect(card.locator('.gauge-card__value')).toHaveText('80 W');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Gauge disconnect, remount and missing-entity reconfiguration release owned frames and fallback timers',async({page})=>{
 await mount(page);const state=await page.evaluate(()=>{const card=window.gaugeLifecycleCard;const schedule=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerContentBounce(card.shadowRoot.querySelector('.gauge-card__content'));window.NodaliaUtils.scheduleDeferTimer=schedule;const pending=card._fallbackAnimationTimers.size;card.remove();const detached={frame:card._gaugeVisualFrame,entrance:card._entranceAnimationResetTimer,fallback:card._fallbackAnimationTimers.size,visual:card._lastGaugeVisualState};document.querySelector('#fixture').append(card);const remounted=card._entranceAnimationResetTimer>0;card.setConfig({entity:'sensor.missing'});return{pending,detached,remounted,missing:{frame:card._gaugeVisualFrame,entrance:card._entranceAnimationResetTimer,fallback:card._fallbackAnimationTimers.size}};});expect(state).toEqual({pending:1,detached:{frame:0,entrance:0,fallback:0,visual:null},remounted:true,missing:{frame:0,entrance:0,fallback:0}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Gauge blank sizing stays automatic, explicit zero stays compact and malformed settings do not block keyboard actions',async({page})=>{
 const card=await mount(page,{grid_options:{rows:'',columns:''},haptics:null,animations:null});expect(await page.evaluate(()=>({rows:window.gaugeLifecycleCard._getConfiguredGridRows(),columns:window.gaugeLifecycleCard._getConfiguredGridColumns(),level:window.gaugeLifecycleCard._getCompactLevel()}))).toEqual({rows:null,columns:null,level:'default'});
 await page.evaluate(()=>{const card=window.gaugeLifecycleCard;window.gaugeMoreInfo=[];card.addEventListener('hass-more-info',event=>window.gaugeMoreInfo.push(event.detail));card.setConfig({entity:'sensor.one',grid_options:{rows:0,columns:7},haptics:{enabled:true,fallback_vibrate:true},animations:{enabled:false}});Object.defineProperty(navigator,'vibrate',{configurable:true,value:()=>{throw new Error('unsupported');}});});expect(await page.evaluate(()=>window.gaugeLifecycleCard._getCompactLevel())).toBe('compact');await card.locator('[data-gauge-action="primary"]').press('Enter');expect(await page.evaluate(()=>window.gaugeMoreInfo)).toEqual([{entityId:'sensor.one'}]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
