import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-circular-gauge-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-circular-gauge-card').getConfigElement();editor.hass=window.makeHass({'sensor.one':{state:'0',attributes:{friendly_name:'Power'}},'input_number.one':{state:'0'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.gaugeEditorFixture=editor;window.gaugeEditorChanges=[];editor.addEventListener('config-changed',event=>window.gaugeEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-circular-gauge-card-editor');}
test('Gauge editor retains unavailable numeric entities, YAML fields and focus while guarding malformed settings and picker payloads',async({page})=>{
 const editor=await mount(page,{entity:'sensor.missing',haptics:null,animations:42,grid_options:7,custom_extension:{value:7}});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('sensor.missing');
 await page.evaluate(()=>window.gaugeEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['sensor.bad']}})));expect(await page.evaluate(()=>window.gaugeEditorChanges.at(-1))).toMatchObject({entity:'sensor.missing',custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Energy');await page.evaluate(()=>window.gaugeEditorFixture.hass=window.makeHass({'sensor.two':{state:'2'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Energy');await editor.locator('[data-editor-toggle="animations"]').click();await expect(editor.locator('input[data-field="animations.dial_duration"]')).toHaveValue('220');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Gauge editor distinguishes explicit zero from automatic bounds and restores cleared animation defaults without losing translucent colours',async({page})=>{
 const editor=await mount(page,{entity:'sensor.one',min:-10,max:100,decimals:2,grid_options:{rows:3,columns:4},tap_action:'none',animations:{dial_duration:900},styles:{gauge:{background:'rgba(10, 20, 30, 0.3)'}}});
 for(const field of ['min','decimals']){const input=editor.locator(`input[data-field="${field}"]`);await input.fill('0');await input.dispatchEvent('change');}let config=await page.evaluate(()=>window.gaugeEditorChanges.at(-1));expect(config).toMatchObject({min:0,decimals:0,max:100});
 for(const field of ['min','grid_options.rows']){const input=editor.locator(`input[data-field="${field}"]`);await input.fill('');await input.dispatchEvent('change');await expect(input).toHaveValue('');}
 await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.dial_duration"]');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('220');config=await page.evaluate(()=>window.gaugeEditorChanges.at(-1));expect(config).toMatchObject({max:100,decimals:0,grid_options:{columns:4},tap_action:'none',styles:{gauge:{background:'rgba(10, 20, 30, 0.3)'}}});expect(config.min).toBeUndefined();expect(config.grid_options.rows).toBeUndefined();expect(config.animations?.dial_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
