import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-graph-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-graph-card').getConfigElement();editor.hass=window.makeHass({'sensor.one':{state:'20',attributes:{friendly_name:'Bedroom'}},'sensor.two':{state:'21',attributes:{friendly_name:'Hall'}},'number.level':{state:'0'},'light.one':{state:'on'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.graphEditorFixture=editor;window.graphEditorChanges=[];editor.addEventListener('config-changed',event=>window.graphEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-graph-card-editor');}
test('Graph editor keeps blank series, legacy entities and paired names/colors through HA feedback and reordering',async({page})=>{
 const editor=await mount(page,{entity:'sensor.missing',name:'Graph',custom_extension:{enabled:false,count:0}});await expect(editor.locator('select[data-field="entities.0.entity"]')).toHaveValue('sensor.missing');await expect(editor.locator('select[data-field="entities.0.entity"] option[value="light.one"]')).toHaveCount(0);await editor.locator('[data-action="add-series"]').click();await expect(editor.locator('.series-editor-card')).toHaveCount(2);await page.evaluate(()=>window.graphEditorFixture.setConfig(window.graphEditorChanges.at(-1)));await expect(editor.locator('.series-editor-card')).toHaveCount(2);await editor.locator('input[data-field="entities.1.name"]').fill('Hall');await editor.locator('input[data-field="entities.1.name"]').dispatchEvent('change');await editor.locator('select[data-field="entities.1.entity"]').selectOption('sensor.two');await editor.locator('[data-action="move-series-up"][data-index="1"]').click();let config=await page.evaluate(()=>window.graphEditorChanges.at(-1));expect(config.entity).toBeUndefined();expect(config.entities[0]).toMatchObject({entity:'sensor.two',name:'Hall',color:'#42a5f5'});expect(config.entities[1].entity).toBe('sensor.missing');expect(config.custom_extension).toEqual({enabled:false,count:0});await editor.locator('[data-action="remove-series"][data-index="1"]').click();config=await page.evaluate(()=>window.graphEditorChanges.at(-1));expect(config.entities).toHaveLength(1);expect(config.entities[0]).toMatchObject({entity:'sensor.two',name:'Hall',color:'#42a5f5'});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Graph editor rejects invalid series paths/indices and retains malformed settings, missing selections and focused drafts',async({page})=>{
 const editor=await mount(page,{entities:[{entity:'sensor.missing',name:'Room',color:'#ffaa00'}],haptics:null,animations:42,custom_extension:{flag:false}});const original=await page.evaluate(()=>JSON.stringify(window.graphEditorFixture._config.entities));await page.evaluate(()=>{const e=window.graphEditorFixture;for(const path of ['entities.99999999.entity','entities.-1.entity','entities.0.unknown','entities.0.__proto__.polluted'])e._setFieldValue(path,'Bad');for(const index of ['-1','0.5','','bad','999999']){const button=document.createElement('button');Object.assign(button.dataset,{action:'remove-series',index});e.shadowRoot.append(button);button.click();button.remove();}});expect(await page.evaluate(()=>JSON.stringify(window.graphEditorFixture._config.entities))).toBe(original);const name=editor.locator('input[data-field="entities.0.name"]');await name.fill('New name');await page.evaluate(()=>window.graphEditorFixture.hass=window.makeHass({'sensor.changed':{state:'22'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('New name');await name.dispatchEvent('change');expect(await page.evaluate(()=>window.graphEditorChanges.at(-1).custom_extension)).toEqual({flag:false});await editor.locator('[data-editor-toggle="animations"]').click();await expect(editor.locator('input[data-field="animations.hover_duration"]')).toHaveValue('180');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Graph editor retains real zero ranges, restores cleared defaults and preserves translucent styles and action controls',async({page})=>{
 const editor=await mount(page,{entities:[{entity:'sensor.one',color:'#ffaa00'}],min:0,max:50,hours_to_show:12,points:120,styles:{card:{background:'rgba(10, 20, 30, 0.3)'}}});await expect(editor.locator('input[data-field="min"]')).toHaveValue('0');const hours=editor.locator('input[data-field="hours_to_show"]');await hours.fill('');await hours.dispatchEvent('change');await expect(hours).toHaveValue('24');await editor.locator('[data-editor-toggle="tap_actions"]').click();await editor.locator('select[data-field="tap_action"]').selectOption('none');const config=await page.evaluate(()=>window.graphEditorChanges.at(-1));expect(config.min).toBe(0);expect(config.max).toBe(50);expect(config.hours_to_show).toBeUndefined();expect(config.tap_action).toBe('none');expect(config.styles.card.background).toBe('rgba(10, 20, 30, 0.3)');await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.background"][type="color"]')).toHaveAttribute('data-alpha','0.3');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
