import {expect,test} from '@playwright/test';
// Exercise native touch cancellation in desktop engines too.
test.use({hasTouch:true});
async function mount(page,config={},states={}){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-humidifier-card'));
 await page.evaluate(({config,states})=>{
  window.humidifierCalls=[];window.humidifierHaptics=[];
  window.humidifierStates={'humidifier.one':{state:'on',attributes:{friendly_name:'Humidifier',humidity:50,min_humidity:0,max_humidity:100,mode:'Low',available_modes:['Low','High','Auto'],supported_features:1}},'select.fan':{state:'Quiet',attributes:{options:['Quiet','Boost']}},'select.mode':{state:'Low',attributes:{options:['Low','High']}},'humidifier.two':{state:'on',attributes:{friendly_name:'Second',humidity:20,min_humidity:0,max_humidity:100}},...states};
  window.humidifierHass=window.createHassFixture({entities:window.humidifierStates,overrides:{callService(...args){window.humidifierCalls.push(args);return Promise.resolve();}}});
  const card=document.createElement('nodalia-humidifier-card');card.setConfig({entity:'humidifier.one',fan_mode_entity:'select.fan',compact_layout_mode:'never',language:'en',animations:{enabled:false},...config});card.hass=window.humidifierHass;card.addEventListener('haptic',event=>window.humidifierHaptics.push(event.detail));document.querySelector('#fixture').append(card);window.humidifierCard=card;
 },{config,states});return page.locator('nodalia-humidifier-card');
}
test('Humidifier cancels linear/circular pointer and touch drags without sending a speed, including entity changes',async({page})=>{
 const card=await mount(page);
 const result=await page.evaluate(()=>{const card=window.humidifierCard;const slider=card.shadowRoot.querySelector('input[type="range"]');const rect=slider.getBoundingClientRect();card._startSliderDrag(slider,rect.left+rect.width*.8,null,7);window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7,clientX:rect.right}));return{calls:window.humidifierCalls.length,drag:card._activeSliderDrag,listeners:card._dragWindowListenersAttached,draft:card._draftHumidity.size};});expect(result).toEqual({calls:0,drag:null,listeners:false,draft:0});
 await page.evaluate(()=>{const card=window.humidifierCard;const slider=card.shadowRoot.querySelector('input[type="range"]');const rect=slider.getBoundingClientRect();card._startSliderDrag(slider,rect.left+rect.width*.7,null,8);card.setConfig({entity:'humidifier.two',compact_layout_mode:'never',animations:{enabled:false}});card.hass=window.humidifierHass;window.dispatchEvent(new PointerEvent('pointerup',{pointerId:8,clientX:rect.right}));});expect(await page.evaluate(()=>window.humidifierCalls)).toEqual([]);await expect(card.locator('input[type="range"]')).toHaveValue('20');
 await page.evaluate(()=>{const card=window.humidifierCard;card.setConfig({entity:'humidifier.one',layout:'circular',animations:{enabled:false}});card.hass=window.humidifierHass;const dial=card.shadowRoot.querySelector('.humidifier-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,9);window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:9,clientX:rect.left,clientY:rect.top}));});expect(await page.evaluate(()=>({calls:window.humidifierCalls.length,drag:window.humidifierCard._activeSliderDrag,draft:window.humidifierCard._draftHumidity.size}))).toEqual({calls:0,drag:null,draft:0});
 await page.evaluate(()=>{const card=window.humidifierCard;const dial=card.shadowRoot.querySelector('.humidifier-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,null);card._onWindowTouchEnd(new TouchEvent('touchcancel'));});expect(await page.evaluate(()=>window.humidifierCalls)).toEqual([]);
 await page.evaluate(()=>{const card=window.humidifierCard;const dial=card.shadowRoot.querySelector('.humidifier-card__circular-dial');const rect=dial.getBoundingClientRect();card._startCircularDialDrag(dial,rect.right,rect.top+rect.height*.5,null,null);card._onWindowTouchStartCapture(new TouchEvent('touchstart'));});expect(await page.evaluate(()=>({calls:window.humidifierCalls.length,drag:window.humidifierCard._activeSliderDrag,draft:window.humidifierCard._draftHumidity.size}))).toEqual({calls:0,drag:null,draft:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Humidifier keeps optimistic toggle and visual-settle deadlines across unchanged HA updates',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 await mount(page);await page.evaluate(()=>window.humidifierCard._toggleHumidifier(window.humidifierCard._getState()));expect(await page.evaluate(()=>window.humidifierCard._optimisticToggle.expectedState)).toBe('off');
 await page.clock.fastForward(3000);await page.evaluate(()=>window.humidifierCard.hass=window.humidifierHass);await page.clock.fastForward(199);expect(await page.evaluate(()=>window.humidifierCard._optimisticToggle.expectedState)).toBe('off');await page.clock.fastForward(1);expect(await page.evaluate(()=>window.humidifierCard._optimisticToggle)).toBe(null);
 await page.evaluate(()=>{window.humidifierStates['humidifier.one'].state='off';window.humidifierCard.hass=window.createHassFixture({entities:window.humidifierStates,overrides:{callService:window.humidifierHass.callService}});window.humidifierCard._toggleHumidifier(window.humidifierCard._getState());window.humidifierStates['humidifier.one'].state='on';window.humidifierStates['humidifier.one'].attributes.humidity=0;window.humidifierCard.hass=window.createHassFixture({entities:window.humidifierStates,overrides:{callService:window.humidifierHass.callService}});});expect(await page.evaluate(()=>window.humidifierCard._getTargetHumidity(window.humidifierCard._getState()))).toBe(50);
 await page.clock.fastForward(400);await page.evaluate(()=>window.humidifierCard.hass={...window.humidifierCard._hass});await page.clock.fastForward(19);expect(await page.evaluate(()=>window.humidifierCard._optimisticVisualSettle)).not.toBe(null);await page.clock.fastForward(1);expect(await page.evaluate(()=>window.humidifierCard._optimisticVisualSettle)).toBe(null);expect(await page.evaluate(()=>window.humidifierCard._getTargetHumidity(window.humidifierCard._getState()))).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Humidifier owns fallback and panel animation work, resets detached interactions and guards stored memory',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 await mount(page,{animations:{enabled:true}});
 const cleanup=await page.evaluate(()=>{const card=window.humidifierCard;card._setVisiblePanelKey('mode');const panel=card.shadowRoot.querySelector('.humidifier-card__panel-shell');panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));const finished=card._panelAnimationCancels.size;card._setVisiblePanelKey('');card._setVisiblePanelKey('mode');card._triggerRenderedButtonBounce('button');const frames=card._bounceFrames.size;const original=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerButtonBounce(card.shadowRoot.querySelector('button'));window.NodaliaUtils.scheduleDeferTimer=original;const scheduled=card._fallbackTimers.size;card._suppressNextHumidifierTap=true;card.remove();panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));return{finished,scheduled,frames,remainingFrames:card._bounceFrames.size,timers:card._fallbackTimers.size,listeners:card._panelAnimationCancels.size,tap:card._suppressNextHumidifierTap,frame:card._resizeFrame};});expect(cleanup.finished).toBe(0);expect(cleanup.frames).toBeGreaterThan(0);expect(cleanup.remainingFrames).toBe(0);expect(cleanup.scheduled).toBeGreaterThan(0);expect(cleanup.timers).toBe(0);expect(cleanup.listeners).toBe(0);expect(cleanup.tap).toBe(false);expect(cleanup.frame).toBe(0);
 const memory=await page.evaluate(()=>{const key='nodalia-humidifier-card:last-visual-state:v1';const card=window.humidifierCard;const results=[];for(const value of ['null','[]','false','{"humidifier.one":{"attributes":[]}}','{"humidifier.one":{"attributes":{"humidity":0},"last_changed":3}}']){localStorage.setItem(key,value);results.push(card._getStoredHumidifierSnapshot('humidifier.one'));}return results;});expect(memory.slice(0,4)).toEqual([null,null,null,null]);expect(memory[4].attributes.humidity).toBe(0);expect(typeof memory[4].last_changed).toBe('string');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Humidifier keyboard actions retain target/data values, catch HA failures and respect disabled slider haptics',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));const card=await mount(page,{tap_action:'service',tap_service:'humidifier.set_humidity',tap_service_data:{humidity:0,flag:false},tap_service_target:{area_id:'living'},security:{allowed_services:['humidifier.set_humidity']},haptics:{scrolls:{humidity:false}}});
 await card.locator('ha-card[data-humidifier-action="body"]').press('Enter');expect(await page.evaluate(()=>window.humidifierCalls.at(-1))).toEqual(['humidifier','set_humidity',{humidity:0,flag:false},{area_id:'living'}]);
 await page.evaluate(()=>{window.humidifierHaptics=[];const slider=window.humidifierCard.shadowRoot.querySelector('input[type="range"]');window.humidifierCard._applySliderValue(slider,70,{commit:false});window.humidifierCard._applySliderValue(slider,75,{commit:true});});expect(await page.evaluate(()=>window.humidifierHaptics)).toEqual([]);
 await page.evaluate(()=>{window.humidifierCard._hass.callService=()=>Promise.reject(new Error('offline'));window.humidifierCard._setHumidifierService('turn_on');window.humidifierCard._callConfiguredService('humidifier.set_humidity','humidifier.one',{humidity:0,flag:false},{area_id:'living'});});await page.evaluate(()=>{window.humidifierCard._hass.callService=()=>{throw new Error('sync offline');};window.humidifierCard._setHumidifierService('turn_off');window.humidifierCard._callConfiguredService('humidifier.set_humidity');});expect(errors).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Humidifier keeps keyboard action focus across consumed state updates and responsive rerenders',async({page})=>{
 const card=await mount(page,{tap_action:'service',tap_service:'humidifier.set_humidity',tap_service_data:{humidity:0},security:{allowed_services:['humidifier.set_humidity']}});
 const body=card.locator('ha-card[data-humidifier-action="body"]');await body.focus();
 await page.evaluate(()=>{const card=window.humidifierCard;card._hass.states['humidifier.one'].attributes.humidity=60;card.hass={...card._hass};});
 await expect(body).toBeFocused();await body.press('Enter');expect(await page.evaluate(()=>window.humidifierCalls.at(-1))).toEqual(['humidifier','set_humidity',{humidity:0,entity_id:'humidifier.one'}]);
 const slider=card.locator('input[type="range"]');await slider.focus();await page.evaluate(()=>window.humidifierCard._render());await expect(slider).toBeFocused();
 const mode=card.locator('[data-humidifier-action="toggle-mode-panel"]');await mode.focus();await page.evaluate(()=>window.humidifierCard._render());await expect(mode).toBeFocused();
 expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Humidifier mode switches reject obsolete animation callbacks and preserve external helpers and missing values',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 const card=await mount(page,{mode_entity:'select.mode',fan_mode_entity:'select.fan',animations:{enabled:true},hidden_modes:['High']});
 const transition=await page.evaluate(()=>{
  const card=window.humidifierCard;card._setVisiblePanelKey('mode');const old=card.shadowRoot.querySelector('.humidifier-card__panel-shell');old.firstElementChild.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));const childEventPending=card._panelAnimationCancels.size;
  card._setVisiblePanelKey('fan');card._setVisiblePanelKey('mode');old.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));const current=card.shadowRoot.querySelector('.humidifier-card__panel-shell');current.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));current.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));
  return{childEventPending,panels:card.shadowRoot.querySelectorAll('.humidifier-card__panel-shell').length,key:current.dataset.panelKey,entering:current.classList.contains('humidifier-card__panel-shell--entering'),listeners:card._panelAnimationCancels.size};
 });expect(transition).toEqual({childEventPending:1,panels:1,key:'mode',entering:false,listeners:0});
 await page.clock.fastForward(1000);await expect(card.locator('.humidifier-card__panel-shell')).toHaveCount(1);await expect(card.locator('[data-humidifier-action="mode"]')).toHaveCount(1);
 await page.evaluate(()=>{window.humidifierCard._commitMode('Low');window.humidifierCard._commitFanMode('Boost');});expect(await page.evaluate(()=>window.humidifierCalls)).toEqual([['select','select_option',{entity_id:'select.mode',option:'Low'}],['select','select_option',{entity_id:'select.fan',option:'Boost'}]]);
 const numeric=await page.evaluate(()=>{const card=window.humidifierCard;const state=attributes=>({...card._getActualState(),attributes});return{missing:card._supportsTargetHumidity(state({humidity:null,target_humidity:'',min_humidity:null,max_humidity:null})),zero:card._supportsTargetHumidity(state({humidity:0})),target:card._getTargetHumidity(state({humidity:null,target_humidity:63})),range:card._getHumidityRange(state({min_humidity:null,max_humidity:70})),defaultTarget:card._getTargetHumidity(state({humidity:null,target_humidity:null}))};});expect(numeric).toEqual({missing:false,zero:true,target:63,range:{min:30,max:80},defaultTarget:55});
 await page.evaluate(()=>{window.humidifierStates['humidifier.one'].attributes.device_class='dehumidifier';window.humidifierCard.hass=window.createHassFixture({entities:window.humidifierStates});window.humidifierCard._setVisiblePanelKey('fan');window.humidifierCard.setConfig({entity:'humidifier.two',animations:{enabled:false}});});await expect(card.locator('.humidifier-card__panel-shell')).toHaveCount(0);expect(await page.evaluate(()=>window.humidifierCard._panelAnimationCancels.size)).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
