import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-insignia-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-insignia-card').getConfigElement();editor.hass=window.makeHass({'sensor.one':{state:'1',attributes:{friendly_name:'One'}},'sensor.two':{state:'2',attributes:{friendly_name:'Two'}}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.insigniaEditorFixture=editor;window.insigniaEditorEmitted=[];editor.addEventListener('config-changed',event=>window.insigniaEditorEmitted.push(event.detail.config));},config);return page.locator('nodalia-insignia-card-editor');}
async function selectEntity(page,value){await page.evaluate(value=>{window.insigniaEditorFixture.shadowRoot.querySelector('[data-field="entity"] input').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value}}));},value);}
test('Insignia editor updates automatic names on entity changes while retaining a custom name and YAML extensions',async({page})=>{
 const editor=await mount(page,{entity:'sensor.one',custom_extension:{value:7}});await expect(editor.locator('input[data-field="name"]')).toHaveValue('One');await selectEntity(page,'sensor.two');await expect(editor.locator('input[data-field="name"]')).toHaveValue('Two');expect(await page.evaluate(()=>window.insigniaEditorEmitted.at(-1))).toMatchObject({entity:'sensor.two',name:'Two',custom_extension:{value:7}});
 await page.evaluate(()=>window.insigniaEditorFixture.setConfig({entity:'sensor.two',name:'Custom'}));await selectEntity(page,'sensor.one');await expect(editor.locator('input[data-field="name"]')).toHaveValue('Custom');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Insignia editor guards malformed picker and nested group data and preserves focus on a HA refresh',async({page})=>{
 const editor=await mount(page,{entity:'sensor.one',tap_action:'service',styles:{card:null,icon:[],tint:'invalid'},haptics:42,security:'invalid'});await selectEntity(page,['sensor.two']);expect(await page.evaluate(()=>window.insigniaEditorEmitted.at(-1).entity)).toBe('sensor.one');
 const name=editor.locator('input[data-field="name"]');await name.fill('Kitchen');await page.evaluate(()=>{window.insigniaEditorFixture.hass=window.makeHass({'sensor.one':{state:'3',attributes:{friendly_name:'Updated'}}});});await expect(name).toBeFocused();await expect(name).toHaveValue('Kitchen');
 await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.padding"]')).toHaveValue('4px 8px');await editor.locator('[data-editor-toggle="tap_actions"]').click();await expect(editor.locator('input[data-field="security.strict_service_actions"]')).toBeChecked();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
