import {expect,test} from '@playwright/test';
test('Insignia refreshes picture, real-zero units and semantic tint when those attributes change',async({page})=>{
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-insignia-card'));await page.evaluate(()=>{const card=document.createElement('nodalia-insignia-card');card.setConfig({entity:'sensor.metric',use_entity_picture:true});card.hass=window.makeHass({'sensor.metric':{state:'0',attributes:{friendly_name:'Metric',unit_of_measurement:'°C',device_class:'temperature'}}});document.querySelector('#fixture').append(card);window.insigniaStateFixture=card;});
 const card=page.locator('nodalia-insignia-card');await expect(card.locator('.insignia-card__value')).toHaveText('0 °C');await expect(card.locator('img')).toHaveCount(0);
 const picture='data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22/%3E';await page.evaluate(picture=>{window.insigniaStateFixture.hass=window.makeHass({'sensor.metric':{state:'0',attributes:{friendly_name:'Metric',unit_of_measurement:'%',device_class:'humidity',entity_picture:picture}}});},picture);
 await expect(card.locator('.insignia-card__value')).toHaveText('0 %');await expect(card.locator('img')).toHaveAttribute('src',picture);expect(await page.evaluate(()=>window.insigniaStateFixture.shadowRoot.querySelector('style').textContent)).toContain('#4da3ff');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Insignia handles rejected/synchronous service calls, validates service JSON and resets consumed taps on reconnect',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-insignia-card'));
 await page.evaluate(()=>{const card=document.createElement('nodalia-insignia-card');card.setConfig({entity:'sensor.one',tap_action:'service',tap_service:'light.turn_on',tap_service_data:'[1,2]',security:{allowed_services:['light.turn_on']}});const hass=window.makeHass({'sensor.one':{state:'1'}});window.insigniaCalls=[];hass.callService=(domain,service,data)=>{window.insigniaCalls.push({domain,service,data});if(window.insigniaCalls.length===1)throw new Error('offline');if(window.insigniaCalls.length===2)return Promise.reject(new Error('rejected'));return Promise.resolve();};card.hass=hass;document.querySelector('#fixture').append(card);window.insigniaServiceFixture=card;});
 const card=page.locator('nodalia-insignia-card'),button=card.locator('[data-insignia-action="primary"]');await button.click();await button.focus();await page.keyboard.press('Enter');expect(await page.evaluate(()=>window.insigniaCalls)).toEqual([{domain:'light',service:'turn_on',data:{}},{domain:'light',service:'turn_on',data:{}}]);
 await page.evaluate(()=>{const card=window.insigniaServiceFixture;card._suppressNextInsigniaTap=true;card.remove();document.querySelector('#fixture').append(card);});await button.click();expect(await page.evaluate(()=>window.insigniaCalls.length)).toBe(3);expect(errors).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
