import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-light-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-light-card').getConfigElement();editor.hass=window.makeHass({'light.one':{state:'on',attributes:{friendly_name:'Light',supported_color_modes:['rgb','color_temp']}}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.lightEditorFixture=editor;window.lightEditorChanges=[];editor.addEventListener('config-changed',event=>window.lightEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-light-card-editor');}
test('Light editor guards malformed settings and picker payloads and retains missing entities, YAML and focus',async({page})=>{
 const editor=await mount(page,{entity:'light.missing',haptics:{scrolls:42},animations:null,security:null,custom_extension:{value:7}});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('light.missing');await page.evaluate(()=>window.lightEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['light.bad']}})));expect(await page.evaluate(()=>window.lightEditorChanges.at(-1))).toMatchObject({entity:'light.missing',custom_extension:{value:7}});const name=editor.locator('input[data-field="name"]');await name.fill('Terrace');await page.evaluate(()=>window.lightEditorFixture.hass=window.makeHass({'light.two':{state:'off'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Terrace');await expect(editor.locator('select[data-field="entity"]')).toHaveValue('light.missing');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Light editor preserves brightness bounds and named colour presets and restores cleared animation defaults',async({page})=>{
 const editor=await mount(page,{entity:'light.one',quick_brightness:[10,35,65,100],color_presets:[{label:'Warm',color:'#ffaa00'},{label:'Night',color:'#0000ff'}],animations:{power_duration:900},styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});const brightness=editor.locator('input[data-field="quick_brightness"]');await brightness.fill('0, ,35.4,120,bad');await brightness.dispatchEvent('change');await expect(brightness).toHaveValue('1, 35, 100');const label=editor.locator('input[data-field="color_presets.0.label"]');await label.fill('Evening');await label.dispatchEvent('change');await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.power_duration"]');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('600');let config=await page.evaluate(()=>window.lightEditorChanges.at(-1));expect(config).toMatchObject({quick_brightness:[1,35,100],color_presets:[{label:'Evening',color:'#ffaa00'},{label:'Night',color:'#0000ff'}],styles:{control:{accent_background:'rgba(10, 20, 30, 0.3)'}}});expect(config.animations?.power_duration).toBeUndefined();await brightness.fill('');await brightness.dispatchEvent('change');await expect(brightness).toHaveValue('10, 35, 65, 100');config=await page.evaluate(()=>window.lightEditorChanges.at(-1));expect(config.quick_brightness).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Light service editors preserve independent body/icon actions, explicit targets and false and zero data',async({page})=>{
 const editor=await mount(page,{entity:'light.one',tap_action:'service',tap_service:'light.turn_on',tap_service_data:{flag:false,count:0},tap_service_target:{area_id:'living'},icon_tap_action:'service',icon_tap_service:'light.turn_off',icon_tap_service_data:{flag:false},icon_hold_action:'service',icon_hold_service:'light.turn_on',icon_hold_service_data:{brightness:0},security:{allowed_services:['light.turn_on','light.turn_off']}});await editor.locator('[data-editor-toggle="tap_actions"]').click();const data=editor.locator('textarea[data-field="tap_service_data"]');await expect(data).toHaveValue('{"flag":false,"count":0}');await expect(editor.locator('textarea[data-field="icon_tap_service_data"]')).toHaveValue('{"flag":false}');await expect(editor.locator('textarea[data-field="icon_hold_service_data"]')).toHaveValue('{"brightness":0}');await data.fill('{"flag":false,"count":0,"extra":true}');await data.dispatchEvent('change');const config=await page.evaluate(()=>window.lightEditorChanges.at(-1));expect(config).toMatchObject({tap_action:'service',tap_service_data:'{"flag":false,"count":0,"extra":true}',tap_service_target:'{"area_id":"living"}',icon_tap_action:'service',icon_tap_service_data:'{"flag":false}',icon_hold_action:'service',icon_hold_service_data:'{"brightness":0}'});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
