import {expect,test} from '@playwright/test';
async function mount(page,{deferred=false,tv=false,playing=false}={}) {
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-media-player'));
 await page.evaluate(({deferred,tv,playing})=>{
  window.mpCommands=[];window.mpRequests=[];window.mpInfo=[];
  window.mpConfig={show:true,animations:{enabled:false},layout:{fixed:false,show_desktop:true,mode:'standard'},artwork:{dynamic_colors:false},security:{strict_service_actions:true,allowed_service_domains:['switch']},players:[{entity:'media_player.one',label:'Speaker',show:true,tv_mode:tv,browse_path:'/media-browser/browser'},{entity:'media_player.two',label:'Other',show:true}]};
  window.mpRoot={title:'Library',media_class:'directory',children:[{title:'Album',media_class:'album',media_content_type:'album',media_content_id:'album',can_expand:true,can_play:true},{title:'Track',media_class:'music',media_content_type:'music',media_content_id:'track',can_play:true},{title:'Unsafe image',media_class:'music',media_content_type:'music',media_content_id:'bad',can_play:true,thumbnail:'javascript:alert(1)'}]};
  const hass=window.createHassFixture({entities:{'media_player.one':{state:playing?'playing':'paused',attributes:{friendly_name:'Speaker',media_title:'Track',media_content_id:'track-one',media_duration:120,media_position:20,volume_level:0.5,supported_features:131074,source:'Plex',source_list:['Plex','HDMI 1']}},'media_player.two':{state:'paused',attributes:{friendly_name:'Other',media_title:'Other track',media_duration:120,media_position:40,volume_level:0}}},overrides:{connection:{},user:{id:'first',is_admin:true},callService(domain,service,data,target){if(!this.states)throw new Error('Lost HA receiver');const entry={domain,service,data,target,receiver:this};window.mpCommands.push(entry);return window.mpDeferService?new Promise(resolve=>entry.resolve=resolve):Promise.resolve();},callWS(message){if(!this.states)throw new Error('Lost HA receiver');const entry={message,receiver:this};window.mpRequests.push(entry);return deferred?new Promise((resolve,reject)=>Object.assign(entry,{resolve,reject})):Promise.resolve(message.media_content_id?{...window.mpRoot,title:'Album',children:window.mpRoot.children.slice(1)}:window.mpRoot);}}});
  window.mpHass=hass;const card=document.createElement('nodalia-media-player');card.setConfig(window.mpConfig);card.hass=hass;card.addEventListener('hass-more-info',event=>window.mpInfo.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.mpCard=card;
 },{deferred,tv,playing});return page.locator('nodalia-media-player');
}
test('Media Player keyboard seeks and retains transport focus through metadata and paused position updates',async({page})=>{
 const card=await mount(page);const track=card.locator('[data-media-progress="seek"]');await track.focus();await track.press('ArrowRight');await track.press('Home');await track.press('End');expect(await page.evaluate(()=>window.mpCommands.map(row=>row.data.seek_position))).toEqual([25,0,120]);
 const next=card.locator('[data-media-control="next"]');await next.focus();await next.press('Enter');await page.evaluate(()=>{window.mpFill=window.mpCard.shadowRoot.querySelector('.media-player__progress-fill');window.mpHass.states['media_player.one'].attributes.media_position=60;window.mpCard.hass={...window.mpHass};});expect(await page.evaluate(()=>({same:window.mpFill===window.mpCard.shadowRoot.querySelector('.media-player__progress-fill'),width:window.mpFill.style.width}))).toEqual({same:true,width:'50%'});await expect(next).toBeFocused();
 await page.evaluate(()=>{window.mpHass.states['media_player.one'].attributes.media_title='Updated';window.mpCard.hass={...window.mpHass};});await expect(card.locator('.media-player__title')).toHaveText('Updated');await expect(next).toBeFocused();
 await page.evaluate(()=>{window.mpCard._hass.callService=()=>Promise.reject(new Error('offline'));window.mpCard._handleMediaControl('next','media_player.one');});await page.evaluate(()=>{window.mpCard._hass.callService=()=>{throw new Error('sync offline');};window.mpCard._handleMediaControl('previous','media_player.one');});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player native pointer cancellation, blur and a track change cancel seek without a service',async({page})=>{
 const card=await mount(page);const track=card.locator('[data-media-progress="seek"]');
 async function start(){await track.evaluate(node=>{const r=node.getBoundingClientRect();node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:7,button:0,clientX:r.left+r.width*0.8}));});expect(await page.evaluate(()=>window.mpCard._activeProgressDrag!==null)).toBe(true);}
 await start();await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7})));expect(await page.evaluate(()=>window.mpCard._activeProgressDrag)).toBe(null);
 await start();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect(await page.evaluate(()=>window.mpCard._activeProgressDrag)).toBe(null);
 await start();await page.evaluate(()=>{window.mpHass.states['media_player.one'].attributes.media_content_id='track-two';window.mpCard.hass={...window.mpHass};window.dispatchEvent(new PointerEvent('pointerup',{pointerId:7,clientX:500}));});expect(await page.evaluate(()=>window.mpCommands.length)).toBe(0);expect(await page.evaluate(()=>window.mpCard._activeProgressDrag)).toBe(null);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player volume drag cancellation restores actual zero and never commits on detach',async({page})=>{
 const card=await mount(page,{tv:true});await card.locator('[data-media-control="toggle-volume-panel"]').click();const slider=card.locator('[data-media-slider="volume"]');await slider.evaluate(node=>{const r=node.getBoundingClientRect();node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:8,button:0,clientX:r.left+r.width*0.9}));});expect(await page.evaluate(()=>window.mpCard._activeSliderDrag!==null)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:8})));await expect(slider).toHaveValue('50');expect(await page.evaluate(()=>window.mpCommands.length)).toBe(0);
 await slider.evaluate(node=>{const r=node.getBoundingClientRect();node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:9,button:0,clientX:r.left}));});await page.evaluate(()=>{window.mpCard.remove();window.dispatchEvent(new PointerEvent('pointerup',{pointerId:9,clientX:0}));document.querySelector('#fixture').append(window.mpCard);window.mpHass.states['media_player.one'].attributes.volume_level=0;window.mpCard.hass={...window.mpHass};});expect(await page.evaluate(()=>({drag:window.mpCard._activeSliderDrag,draft:window.mpCard._draftVolume.size,commands:window.mpCommands.length}))).toEqual({drag:null,draft:0,commands:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player browser uses native keyboard focus, sanitizes thumbnails and restores its browse button',async({page})=>{
 const card=await mount(page);const browse=card.locator('[data-media-control="browse-media"]');await browse.focus();await browse.press('Enter');const panel=card.locator('.media-browser-panel');const back=panel.locator('[data-media-browser-back]');await expect(back).toBeFocused();const play=panel.locator('[data-media-browser-action="play"][data-media-content-id="track"]');await play.focus();await play.press('Tab');await expect(panel.locator('[data-media-content-id="bad"]')).toBeFocused();await panel.locator('[data-media-content-id="bad"]').press('Tab');await expect(back).toBeFocused();await play.focus();await page.evaluate(()=>{window.mpHass.states['media_player.one'].attributes.media_title='Updated';window.mpCard.hass={...window.mpHass};});await expect(play).toBeFocused();expect(await panel.locator('img').count()).toBe(0);
 await panel.locator('[data-media-browser-action="browse"][data-media-content-id="album"]').press('Enter');await expect(panel.locator('.media-browser__title')).toHaveText('Album');await back.press('Enter');await expect(panel.locator('.media-browser__title')).toHaveText('Library');await play.press('Enter');await expect(panel).toHaveCount(0);await expect(browse).toBeFocused();expect(await page.evaluate(()=>{const {domain,service,data}=window.mpCommands.at(-1);return {domain,service,data};})).toEqual({domain:'media_player',service:'play_media',data:{entity_id:'media_player.one',media_content_id:'track',media_content_type:'music'}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player abandons deferred browser results and fallback navigation across users, configuration and reconnect',async({page})=>{
 const card=await mount(page,{deferred:true});const browse=card.locator('[data-media-control="browse-media"]');await browse.click();await page.evaluate(()=>{window.mpHass={...window.mpHass,connection:{},user:{id:'second',is_admin:true}};window.mpCard.hass=window.mpHass;window.mpRequests[0].reject(new Error('Old user'));});await expect(card.locator('.media-browser-panel')).toHaveCount(0);expect(await page.evaluate(()=>location.pathname)).toBe('/tests/fixtures/browser.html');
 await browse.click();await page.evaluate(()=>{window.mpCard.setConfig(window.mpConfig);window.mpRequests[1].resolve(window.mpRoot);});await expect(card.locator('.media-browser-panel')).toHaveCount(0);await browse.click();await page.evaluate(()=>{window.mpCard.remove();document.querySelector('#fixture').append(window.mpCard);window.mpRequests[2].resolve(window.mpRoot);});await expect(card.locator('.media-browser-panel')).toHaveCount(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player retires stepped TV volume work on a new HA context and supersedes rapid commits',async({page})=>{
 await mount(page,{tv:true});await page.evaluate(()=>{window.mpDeferService=true;window.mpCard._commitPlayerVolume('media_player.one',100);});expect(await page.evaluate(()=>window.mpCommands.length)).toBe(1);await page.evaluate(()=>{window.mpCard._commitPlayerVolume('media_player.one',0);window.mpCommands[0].resolve();});expect(await page.evaluate(()=>window.mpCommands.length)).toBe(2);expect(await page.evaluate(()=>window.mpCommands.map(row=>row.service))).toEqual(['volume_up','volume_down']);
 await page.evaluate(()=>{window.mpHass={...window.mpHass,connection:{},user:{id:'second',is_admin:true}};window.mpCard.hass=window.mpHass;window.mpCommands[1].resolve();});await expect.poll(()=>page.evaluate(()=>window.mpCard._volumeSteps.size)).toBe(0);expect(await page.evaluate(()=>({calls:window.mpCommands.length,waits:window.mpCard._volumeWaits.size,draft:window.mpCard._draftVolume.size}))).toEqual({calls:2,waits:0,draft:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player owns artwork preloads, private cover history and timer work through context changes',async({page})=>{
 await mount(page,{playing:true});await page.clock.install();await page.evaluate(()=>{window.mpImages=[];window.Image=class{set src(value){this.url=value;window.mpImages.push(this);}};window.mpCard._artworkController.remember('/old.jpg',8,'media_player.one');window.mpOldPromise=window.mpCard._preloadArtworkUrl('/pending.jpg');window.mpOldLoad=window.mpImages[0].onload;window.mpCard._onResize();window.mpHass={...window.mpHass,connection:{},user:{id:'second',is_admin:true}};window.mpCard.hass=window.mpHass;window.mpNewPromise=window.mpCard._preloadArtworkUrl('/pending.jpg');window.mpOldLoad();});expect(await page.evaluate(()=>({pending:window.mpCard._pendingArtworkPreloads.size,ready:window.mpCard._readyArtworkUrls.size,recent:window.mpCard._artworkController.recentFor('media_player.one')}))).toEqual({pending:1,ready:0,recent:[]});expect(await page.evaluate(()=>window.mpOldPromise)).toBe(false);await page.evaluate(()=>window.mpImages[1].onload());expect(await page.evaluate(()=>window.mpNewPromise)).toBe(true);
 await page.evaluate(()=>{window.mpCard._onResize();window.mpCard.remove();});expect(await page.evaluate(()=>({ticker:window.mpCard._mediaTicker,resize:window.mpCard._resizeSyncTimer,entrance:window.mpCard._entranceAnimationResetTimer,frame:window.mpCard._layoutFrame,pending:window.mpCard._pendingArtworkPreloads.size,cancels:window.mpCard._artworkPreloadCancels.size}))).toEqual({ticker:null,resize:0,entrance:0,frame:0,pending:0,cancels:0});await page.clock.runFor(2000);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Media Player custom power actions keep service targets and false/zero data inside the configured allowlist',async({page})=>{
 const card=await mount(page,{tv:true});await page.evaluate(()=>window.mpCard.setConfig({...window.mpConfig,players:[{...window.mpConfig.players[0],power_action_on:{action:'call-service',service:'switch.turn_on',service_data:'{"enabled":false,"brightness":0}',target:{area_id:'room'}}}]}));await card.locator('[data-media-control="power-toggle"]').press('Enter');expect(await page.evaluate(()=>{const {domain,service,data,target}=window.mpCommands.at(-1);return {domain,service,data,target};})).toEqual({domain:'switch',service:'turn_on',data:{enabled:false,brightness:0},target:{area_id:'room'}});
 await page.evaluate(()=>window.mpCard.setConfig({...window.mpConfig,players:[{...window.mpConfig.players[0],power_action_on:{action:'call-service',service:'light.turn_on',service_data:{brightness:0}}}]}));await card.locator('[data-media-control="power-toggle"]').press('Enter');expect(await page.evaluate(()=>window.mpCommands.length)).toBe(1);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
