import {expect,test} from '@playwright/test';
async function mount(page,{deferred=false,playing=false}={}) {
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-navigation-bar'));
 await page.evaluate(({deferred,playing})=>{
  window.navRequests=[];window.navCommands=[];window.navInfo=[];
  window.navConfig={animations:{enabled:false},layout:{fixed:false,show_desktop:true},security:{allowed_service_domains:['switch']},routes:[{path:'/lovelace/home',label:'Home',icon:'mdi:home',badge:{entity:'sensor.badge',attribute:'count',show_zero:true}},{label:'More',icon:'mdi:dots-horizontal',popup:[{label:'First',icon:'mdi:one',tap_action:{action:'call-service',service:'switch.turn_on',service_data:{enabled:false,brightness:0},target:{area_id:'room'}}},{label:'Second',icon:'mdi:two',tap_action:{action:'more-info',entity:'switch.lamp'}}]},{label:'Private',icon:'mdi:lock',users:['first'],tap_action:{action:'more-info',entity:'switch.lamp'}}],media_player:{show:true,show_desktop:true,album_cover_background:false,players:[{entity:'media_player.one',label:'Speaker',browse_path:'/media-browser/browser'},{entity:'media_player.two',label:'Other'}]}};
  window.navRoot={title:'Library',media_class:'directory',children:[{title:'Album',media_class:'album',media_content_type:'album',media_content_id:'album',can_expand:true,can_play:true},{title:'Track',media_class:'music',media_content_type:'music',media_content_id:'track',can_play:true},{title:'Bad thumbnail',media_class:'music',media_content_type:'music',media_content_id:'bad',can_play:true,thumbnail:'javascript:alert(1)'}]};
  const hass=window.createHassFixture({entities:{'sensor.badge':{state:'1',attributes:{count:1}},'switch.lamp':{state:'off',attributes:{}},'media_player.one':{state:playing?'playing':'paused',attributes:{friendly_name:'Speaker',media_title:'Track',media_duration:120,media_position:20,volume_level:0.5}},'media_player.two':{state:'paused',attributes:{friendly_name:'Other',media_duration:120,media_position:40,volume_level:0}}},overrides:{connection:{},user:{id:'first',is_admin:true},callService(domain,service,data,target){window.navCommands.push({domain,service,data,target});return Promise.resolve();},callWS(message){if(!this.states)throw new Error('Lost HA receiver');const entry={message,connection:this.connection};window.navRequests.push(entry);return deferred?new Promise((resolve,reject)=>Object.assign(entry,{resolve,reject})):Promise.resolve(message.media_content_id?{...window.navRoot,title:'Album',children:window.navRoot.children.slice(1)}:window.navRoot);}}});
  window.navHass=hass;const card=document.createElement('nodalia-navigation-bar');card.setConfig(window.navConfig);card.hass=hass;card.addEventListener('hass-more-info',event=>window.navInfo.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.navCard=card;
 },{deferred,playing});return page.locator('nodalia-navigation-bar');
}
async function expand(card) {await card.locator('[data-media-toggle="expand"]').click();await expect(card.locator('.media-player-card')).toBeVisible();}
test('Navigation modal keyboard focus wraps and survives HA refresh before returning to its route',async({page})=>{
 const card=await mount(page);const route=card.locator('.nav-item[data-route-index="1"]');await route.focus();await route.press('Enter');const first=card.locator('[data-popup-item-index="0"]');const last=card.locator('[data-popup-item-index="1"]');await expect(first).toBeFocused();
 await first.press('Shift+Tab');await expect(last).toBeFocused();await last.press('Tab');await expect(first).toBeFocused();await first.press('Tab');await expect(last).toBeFocused();
 await page.evaluate(()=>{window.navHass.states['sensor.badge'].attributes.count=2;window.navCard.hass={...window.navHass};});await expect(last).toBeFocused();await last.press('Escape');await expect(card.locator('.popup-panel')).toHaveCount(0);await expect(route).toBeFocused();
 await route.press('Enter');await expect(first).toBeFocused();await first.press('Enter');expect(await page.evaluate(()=>window.navCommands[0])).toMatchObject({domain:'switch',service:'turn_on',data:{enabled:false,brightness:0},target:{area_id:'room'}});await expect(route).toBeFocused();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Navigation media browser retains focus through native browse/play and returns to its control',async({page})=>{
 const card=await mount(page);await expand(card);const browse=card.locator('[data-media-control="browse-media"]');await browse.focus();await browse.press('Enter');const panel=card.locator('.media-browser-panel');const back=panel.locator('[data-media-browser-back]');await expect(back).toBeFocused();
 const play=panel.locator('[data-media-browser-action="play"][data-media-content-id="track"]');await play.focus();await play.press('Tab');await expect(panel.locator('[data-media-content-id="bad"]')).toBeFocused();await panel.locator('[data-media-content-id="bad"]').press('Tab');await expect(back).toBeFocused();
 await play.focus();await page.evaluate(()=>{window.navHass.states['sensor.badge'].attributes.count=3;window.navCard.hass={...window.navHass};});await expect(play).toBeFocused();expect(await panel.locator('img').count()).toBe(0);
 await panel.locator('[data-media-browser-action="browse"][data-media-content-id="album"]').press('Enter');await expect(panel.locator('.media-browser__title')).toHaveText('Album');await back.press('Enter');await expect(panel.locator('.media-browser__title')).toHaveText('Library');
 await play.press('Enter');await expect(panel).toHaveCount(0);await expect(browse).toBeFocused();expect(await page.evaluate(()=>window.navCommands.at(-1))).toMatchObject({domain:'media_player',service:'play_media',data:{entity_id:'media_player.one',media_content_id:'track',media_content_type:'music'}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Navigation discards deferred browsing across users, configuration and reconnect without stale fallback navigation',async({page})=>{
 const card=await mount(page,{deferred:true});await expand(card);await card.locator('[data-media-control="browse-media"]').click();await expect.poll(()=>page.evaluate(()=>window.navRequests.length)).toBe(1);
 await page.evaluate(()=>{window.navHass={...window.navHass,connection:{},user:{id:'second',is_admin:true}};window.navCard.hass=window.navHass;window.navRequests[0].reject(new Error('Old connection'));});await expect(card.locator('.media-browser-panel')).toHaveCount(0);await expect(card.locator('.nav-item')).toHaveCount(2);expect(await page.evaluate(()=>location.pathname)).toBe('/tests/fixtures/browser.html');
 await expand(card);await card.locator('[data-media-control="browse-media"]').click();await page.evaluate(()=>{window.navCard.setConfig({...window.navConfig,routes:window.navConfig.routes.slice(0,2)});window.navRequests[1].resolve(window.navRoot);});await expect(card.locator('.media-browser-panel')).toHaveCount(0);
 await expand(card);await card.locator('[data-media-control="browse-media"]').click();await page.evaluate(()=>{window.navCard.remove();document.querySelector('#fixture').append(window.navCard);window.navRequests[2].resolve(window.navRoot);});await expect(card.locator('.media-browser-panel')).toHaveCount(0);expect(await page.evaluate(()=>window.navCard._mediaBrowserState)).toBe(null);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Navigation patches paused progress and rapid volume controls in place while retaining action focus',async({page})=>{
 const card=await mount(page);await expand(card);const volume=card.locator('[data-media-control="volume-up"]');await volume.focus();await volume.press('Enter');await volume.press('Enter');
 expect(await page.evaluate(()=>window.navCommands.map(row=>row.data.volume_level))).toEqual([0.58,0.6599999999999999]);
 await page.evaluate(()=>{window.navFill=window.navCard.shadowRoot.querySelector('.media-player__progress-fill');window.navHass.states['media_player.one'].attributes.media_position=60;window.navCard.hass={...window.navHass};});expect(await page.evaluate(()=>({same:window.navFill===window.navCard.shadowRoot.querySelector('.media-player__progress-fill'),width:window.navFill.style.width}))).toEqual({same:true,width:'50%'});await expect(volume).toBeFocused();
 const info=card.locator('[data-nav-media-info]');await info.focus();await info.press('Enter');expect(await page.evaluate(()=>window.navInfo)).toEqual(['media_player.one']);
 await page.evaluate(()=>{window.navHass.states['media_player.one'].attributes.device_class='tv';window.navCard.hass={...window.navHass};});await expect(info).toBeFocused();expect(await page.evaluate(()=>window.navCard._getPlayerDeviceType(window.navCard._getVisibleMediaPlayers()[0],window.navHass.states['media_player.one']))).toBe('tv');
 const numeric=await page.evaluate(()=>{const card=window.navCard,state=attributes=>({entity_id:'media_player.one',state:'paused',attributes});return {infiniteDuration:card._getMediaPlayerProgress(state({media_duration:Infinity})),invalidPosition:card._getMediaPlayerProgress(state({media_duration:120,media_position:NaN})),invalidVolume:card._supportsVolumeControl(state({volume_level:Infinity})),zeroVolume:card._supportsVolumeControl(state({volume_level:0}))};});expect(numeric).toEqual({infiniteDuration:null,invalidPosition:{duration:120,percent:0,position:0},invalidVolume:false,zeroVolume:true});
 await page.evaluate(()=>{window.navCard._hass.callService=()=>Promise.reject(new Error('offline'));window.navCard._handleMediaControl('next','media_player.one');});await page.evaluate(()=>{window.navCard._hass.callService=()=>{throw new Error('sync offline');};window.navCard._handleMediaControl('previous','media_player.one');});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Navigation releases timers, frame callbacks and modal work when detached or hidden',async({page})=>{
 const card=await mount(page,{playing:true});await page.clock.install();await expand(card);expect(await page.evaluate(()=>window.navCard._mediaTicker!==null)).toBe(true);await card.locator('.nav-item[data-route-index="1"]').click();
 await page.evaluate(()=>{window.navCard._onResize();window.navCard.remove();});expect(await page.evaluate(()=>({ticker:window.navCard._mediaTicker,position:window.navCard._popupPositionFrame,resize:window.navCard._resizeSyncTimer,entrance:window.navCard._dockEntranceResetFrame,popup:window.navCard._popupState,browser:window.navCard._mediaBrowserState}))).toEqual({ticker:null,position:null,resize:0,entrance:0,popup:null,browser:null});await page.clock.runFor(2000);
 await page.evaluate(()=>document.querySelector('#fixture').append(window.navCard));await expect(card.locator('.media-player-card')).toBeVisible();await page.evaluate(()=>{window.navCard.setConfig({...window.navConfig,layout:{fixed:false,show_desktop:false,mobile_breakpoint:1}});});await expect(card.locator('ha-card')).toHaveCount(0);expect(await page.evaluate(()=>window.navCard._mediaTicker)).toBe(null);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
