import {expect,test} from '@playwright/test';
test('News cancelled swipe keeps the current article and disconnection releases gesture state',async({page})=>{
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-news-card'));
 await page.evaluate(()=>{const card=document.createElement('nodalia-news-card');card.setConfig({entity:'sensor.news',remember_items:false});card.hass=window.makeHass({'sensor.news':{state:'ready',attributes:{items:[{title:'One',published:'2026-10-01T00:00:00Z'},{title:'Two',published:'2026-09-30T00:00:00Z'}]}}});document.querySelector('#fixture').append(card);window.newsLifecycleFixture=card;});
 const card=page.locator('nodalia-news-card');await expect(card.locator('.news-card__carousel-slide.is-active')).toContainText('One');
 await page.evaluate(()=>{const viewport=window.newsLifecycleFixture.shadowRoot.querySelector('.news-card__carousel-viewport');viewport.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:7,clientX:200,clientY:20,button:0}));window.dispatchEvent(new PointerEvent('pointermove',{pointerId:7,clientX:100,clientY:20}));window.dispatchEvent(new PointerEvent('pointercancel',{pointerId:7,clientX:100,clientY:20}));});
 await expect(card.locator('.news-card__carousel-slide.is-active')).toContainText('One');
 expect(await page.evaluate(()=>{const card=window.newsLifecycleFixture;const viewport=card.shadowRoot.querySelector('.news-card__carousel-viewport');viewport.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true,pointerId:8,clientX:200,clientY:20,button:0}));window.dispatchEvent(new PointerEvent('pointermove',{pointerId:8,clientX:100,clientY:20}));window.dispatchEvent(new PointerEvent('pointerup',{pointerId:8,clientX:100,clientY:20}));const suppressed=card._suppressArticleTap,scheduled=card._articleTapResetTimer!==0;card.remove();return{suppressed,scheduled,timer:card._articleTapResetTimer,swipe:card._magazineSwipeState,attached:card._magazineSwipeWindowAttached,afterSuppression:card._suppressArticleTap};})).toEqual({suppressed:true,scheduled:true,timer:0,swipe:null,attached:false,afterSuppression:false});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('News numeric editor clearing restores its default and keeps focus through HA updates',async({page})=>{
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-news-card'));
 await page.evaluate(async()=>{const editor=await customElements.get('nodalia-news-card').getConfigElement();editor.setConfig({entity:'sensor.news',max_items:3});editor.hass=window.makeHass({'sensor.news':{state:'ready',attributes:{friendly_name:'News'}}});document.querySelector('#fixture').append(editor);window.newsEditorFixture=editor;window.newsEditorEmitted=[];editor.addEventListener('config-changed',event=>window.newsEditorEmitted.push(event.detail.config));});
 const editor=page.locator('nodalia-news-card-editor'),limit=editor.locator('input[data-field="max_items"]');await limit.fill('');await limit.dispatchEvent('change');await expect(limit).toHaveValue('5');expect(await page.evaluate(()=>window.newsEditorEmitted.at(-1).max_items)).toBeUndefined();
 const title=editor.locator('input[data-field="title"]');await title.fill('Headline');await page.evaluate(()=>{window.newsEditorFixture.hass=window.makeHass({'sensor.news':{state:'ready',attributes:{friendly_name:'Updated feed'}}});});await expect(title).toBeFocused();await expect(title).toHaveValue('Headline');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
