import {expect,test} from '@playwright/test';
async function mount(page,config,pickers=false){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-notifications-card'));
 await page.evaluate(async({config,pickers})=>{if(pickers)for(const tag of ['ha-entity-picker','ha-icon-picker'])if(!customElements.get(tag))customElements.define(tag,class extends HTMLElement{constructor(){super();this.value='';this.hass=null;}});const editor=await customElements.get('nodalia-notifications-card').getConfigElement();editor.hass=window.createHassFixture({entities:{'sensor.one':{state:'0'},'sensor.two':{state:'20'},'calendar.one':{state:'on'},'media_player.one':{state:'playing'},'light.one':{state:'on'}},overrides:{user:{id:'one',is_admin:true},connection:{}}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.notificationEditorFixture=editor;window.notificationEditorChanges=[];editor.addEventListener('config-changed',event=>window.notificationEditorChanges.push(event.detail.config));},{config,pickers});
 return page.locator('nodalia-notifications-card-editor');
}
test('Notifications editor retains unfinished custom/external rows through HA feedback and paired data through reordering',async({page})=>{
 const editor=await mount(page,{custom_notifications:[{title:'First',entity:'sensor.one',icon:'mdi:thermometer',action_type:'service',service:'light.turn_on',service_data:{count:0,enabled:false},tap_action:{action:'url',url_path:'https://example.com',new_tab:false}},{title:'Second',entity:'sensor.two'}],custom_extension:{flag:false,count:0}});
 await expect(editor.locator('textarea[data-field="custom_notifications.0.service_data"]')).toHaveValue('{"count":0,"enabled":false}');
 await editor.locator('[data-editor-action="add-custom"]').click();await page.evaluate(()=>window.notificationEditorFixture.setConfig(window.notificationEditorChanges.at(-1)));
 await expect(editor.locator('input[data-field="custom_notifications.2.title"]')).toHaveCount(1);
 await editor.locator('input[data-field="custom_notifications.2.title"]').fill('Draft');await editor.locator('input[data-field="custom_notifications.2.title"]').dispatchEvent('change');
 await editor.locator('[data-editor-action="move-custom-up"][data-index="2"]').click();let config=await page.evaluate(()=>window.notificationEditorChanges.at(-1));expect(config.custom_notifications.map(row=>row.title)).toEqual(['First','Draft','Second']);expect(config.custom_notifications[0]).toMatchObject({entity:'sensor.one',icon:'mdi:thermometer',service_data:'{"count":0,"enabled":false}',tap_action:{action:'url',url_path:'https://example.com',new_tab:false}});expect(config.custom_extension).toEqual({flag:false,count:0});
 await editor.locator('[data-editor-action="add-external-alert"]').click();await page.evaluate(()=>window.notificationEditorFixture.setConfig(window.notificationEditorChanges.at(-1)));
 await expect(editor.locator('input[data-field="external_alerts.0.id"]')).toHaveCount(1);await editor.locator('input[data-field="external_alerts.0.id"]').fill('camera');await editor.locator('input[data-field="external_alerts.0.id"]').dispatchEvent('change');
 await page.evaluate(()=>window.notificationEditorFixture.setConfig(window.notificationEditorChanges.at(-1)));await expect(editor.locator('input[data-field="external_alerts.0.id"]')).toHaveValue('camera');
 await editor.locator('input[data-field="external_alerts.0.title"]').fill('Person detected');await editor.locator('input[data-field="external_alerts.0.title"]').dispatchEvent('change');config=await page.evaluate(()=>window.notificationEditorChanges.at(-1));expect(config.external_alerts[0]).toMatchObject({id:'camera',title:'Person detected'});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications editor rejects invalid row/list edits and refreshes native media selectors while keeping focus and zero thresholds',async({page})=>{
 const editor=await mount(page,{temperature_entities:['sensor.missing'],media_player_entities:['media_player.one'],custom_notifications:[{title:'First'}],external_alerts:[{id:'one',title:'Alert'}],thresholds:{battery_low:0},styles:{card:{background:'rgba(10, 20, 30, 0.3)'}}});
 const original=await page.evaluate(()=>JSON.stringify(window.notificationEditorFixture._config));
 await page.evaluate(()=>{const e=window.notificationEditorFixture;for(const path of ['custom_notifications.99999.title','custom_notifications.-1.title','external_alerts.99999.id','custom_notifications.0.unknown','smart_entity_overrides.-1.title'])e._setFieldValue(path,'Bad');for(const index of [-1,0.5,99999])e._setEntityListItem('temperature_entities',index,'sensor.two');for(const index of ['-1','0.5','','bad','99999'])for(const action of ['remove-custom','move-custom-up','move-custom-down','remove-external-alert','remove-entity-list-item']){const b=document.createElement('button');Object.assign(b.dataset,{editorAction:action,index,field:'temperature_entities'});e.shadowRoot.append(b);b.click();b.remove();}});
 expect(await page.evaluate(()=>JSON.stringify(window.notificationEditorFixture._config))).toBe(original);
 await editor.locator('[data-editor-toggle="connections"]').click();await expect(editor.locator('input[data-list-field="temperature_entities"][data-index="0"]')).toHaveValue('sensor.missing');
 const title=editor.locator('input[data-field="custom_notifications.0.title"]');await title.fill('Edited');await page.evaluate(()=>{window.oldMediaControl=window.notificationEditorFixture.shadowRoot.querySelector('input[data-list-field="media_player_entities"]');});
 await page.evaluate(()=>{const e=window.notificationEditorFixture;e.hass={...e._hass,states:{...e._hass.states,'media_player.new':{entity_id:'media_player.new',state:'paused',attributes:{}}}};});await expect(title).toBeFocused();await expect(title).toHaveValue('Edited');await title.dispatchEvent('change');expect(await page.evaluate(()=>window.oldMediaControl.isConnected)).toBe(false);await expect(editor.locator('input[data-list-field="media_player_entities"][data-index="0"]')).toHaveValue('media_player.one');
 const threshold=editor.locator('input[data-field="thresholds.battery_low"]');await expect(threshold).toHaveValue('0');await threshold.fill('');await threshold.dispatchEvent('change');await expect(threshold).toHaveValue('20');await editor.locator('[data-editor-toggle="styles"]').click();await expect(editor.locator('input[data-field="styles.card.background"][type="color"]')).toHaveAttribute('data-alpha','0.3');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications editor commits HA picker values and maps smart entity overrides by entity rather than row position',async({page})=>{
 const editor=await mount(page,{temperature_entities:['sensor.one','sensor.two'],smart_entity_overrides:[{entity:'sensor.two',title:'Second custom',mobile:'off'}],custom_notifications:[{title:'First'}]},true);
 await editor.locator('[data-editor-toggle="connections"]').click();expect(await page.evaluate(()=>{const p=window.notificationEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-list-field="temperature_entities"]');return {domains:p.includeDomains,sensor:p.entityFilter({entity_id:'sensor.one'}),light:p.entityFilter({entity_id:'light.one'})};})).toEqual({domains:['sensor'],sensor:true,light:false});await page.evaluate(()=>{const p=window.notificationEditorFixture.shadowRoot.querySelector('ha-entity-picker[data-list-field="temperature_entities"][data-index="2"]');p.dispatchEvent(new CustomEvent('value-changed',{detail:{value:'sensor.missing'},bubbles:true,composed:true}));});expect(await page.evaluate(()=>window.notificationEditorChanges.at(-1).temperature_entities)).toEqual(['sensor.one','sensor.two','sensor.missing']);
 await editor.locator('[data-editor-toggle="smart"]').click();const title=editor.locator('input[data-field="smart_entity_overrides.0.title"]');await title.fill('First custom');await title.dispatchEvent('change');let config=await page.evaluate(()=>window.notificationEditorChanges.at(-1));expect(config.smart_entity_overrides.find(row=>row.entity==='sensor.one').title).toBe('First custom');expect(config.smart_entity_overrides.find(row=>row.entity==='sensor.two')).toMatchObject({title:'Second custom',mobile:'off'});
 await page.evaluate(()=>{const p=window.notificationEditorFixture.shadowRoot.querySelector('ha-icon-picker[data-field="custom_notifications.0.icon"]');p.dispatchEvent(new CustomEvent('value-changed',{detail:{value:'mdi:star'},bubbles:true,composed:true}));});config=await page.evaluate(()=>window.notificationEditorChanges.at(-1));expect(config.custom_notifications[0].icon).toBe('mdi:star');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications editor discards abandoned Engine replies and background writes while retaining disabled profile synchronization',async({page})=>{
 await mount(page,{background_mobile:{enabled:true,webhook:'test',profile_id:'old'}});
 await expect.poll(()=>page.evaluate(()=>window.notificationEditorFixture._engineStatusInFlight)).toBe(false);
 const result=await page.evaluate(async()=>{
  const e=window.notificationEditorFixture,statusReplies=[],profiles=[],webhooks=[];
  window.NodaliaBackend={...window.NodaliaBackend,getEditorEngineStatus:()=>new Promise(resolve=>statusReplies.push(resolve)),status:async()=>({available:true,capabilities:['notifications_background']}),setNotificationProfile:async(_hass,profile,id)=>{profiles.push({profile,id});return{};}};
  window.NodaliaUtils.postHomeAssistantWebhook=async(...args)=>{webhooks.push(args);return true;};
  const first=e._refreshEngineStatus();e.hass={...e._hass,connection:{},user:{id:'two',is_admin:true}};const second=e._refreshEngineStatus();
  statusReplies[0]({available:true,caps:{notificationsBackground:true,notificationsInbox:true},version:'old'});await first;
  const abandoned=e._engineStatus;statusReplies[1]({available:false,caps:{notificationsBackground:false},version:'new'});await second;await Promise.resolve();
  let resolveNative;window.NodaliaBackend.status=()=>new Promise(resolve=>{resolveNative=resolve;});
  const pending=e._syncBackgroundMobileConfigFromEditor();e.setConfig({background_mobile:{enabled:false,profile_id:'new'}});resolveNative({available:true,capabilities:['notifications_background']});await pending;
  const staleProfiles=profiles.length,staleWebhooks=webhooks.length;
  window.NodaliaBackend.status=async()=>({available:true,capabilities:['notifications_background']});await e._syncBackgroundMobileConfigFromEditor();
  e.remove();statusReplies.at(-1)({available:true,caps:{notificationsBackground:true},version:'detached'});await Promise.resolve();await Promise.resolve();const applied=e._engineStatus?.version;
  return {abandoned,applied,staleProfiles,staleWebhooks,profiles,webhooks,generation:e._backgroundSyncGeneration,timer:e._backgroundMobileSyncTimer};
 });
 expect(result.abandoned).toBeNull();expect(result.applied).toBe('new');expect(result.staleProfiles).toBe(0);expect(result.staleWebhooks).toBe(0);expect(result.profiles).toHaveLength(1);expect(result.profiles[0]).toMatchObject({id:'new',profile:{enabled:false}});expect(result.timer).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Notifications editor keeps a queued profile sync when HA returns the emitted configuration',async({page})=>{
 const editor=await mount(page,{background_mobile:{enabled:true,profile_id:'home'},temperature_entities:['sensor.one']});
 await expect.poll(()=>page.evaluate(()=>window.notificationEditorFixture._engineStatusInFlight)).toBe(false);await page.clock.install();
 await page.evaluate(()=>{window.editorProfileWrites=[];window.NodaliaBackend={...window.NodaliaBackend,status:async()=>({available:true,capabilities:['notifications_background']}),setNotificationProfile:async(_hass,profile,id)=>{window.editorProfileWrites.push({profile,id});return{};}};});
 const threshold=editor.locator('input[data-field="thresholds.battery_low"]');await threshold.fill('25');await threshold.dispatchEvent('change');
 await page.evaluate(()=>window.notificationEditorFixture.setConfig(window.notificationEditorChanges.at(-1)));await page.clock.runFor(701);
 await expect.poll(()=>page.evaluate(()=>window.editorProfileWrites.length)).toBe(1);expect(await page.evaluate(()=>window.editorProfileWrites[0])).toMatchObject({id:'home',profile:{enabled:true,thresholds:{battery_low:25}}});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
