import {expect,test} from '@playwright/test';
async function mount(page,{calendar=false,weather=false,deferred=false,mobile=false}={}) {
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-notifications-card'));
 await page.evaluate(({calendar,weather,deferred,mobile})=>{
  window.noticeCalls=[];window.noticeQueries=[];window.noticeWS=[];window.noticeInfo=[];
  window.noticeConfig={language:'en',animations:{enabled:false},max_visible:1,storage_key:'lifecycle-fixture',smart_recommendations:false,calendar_entities:calendar?['calendar.one','calendar.two']:[],weather_entities:weather?['weather.one']:[],custom_notifications:[{title:'One',entity:'switch.one',action_type:'toggle',mobile:'push',severity:'warning'},{title:'Two',entity:'switch.one',action_type:'service',service:'switch.turn_on',service_data:'{"enabled":false,"brightness":0}',severity:'warning',mobile:'push'},{title:'Three',entity:'switch.one',action_type:'more-info',severity:'info'}],mobile_notifications:{enabled:mobile,services:['notify.phone'],min_severity:'warning',group_similar:false},security:{allowed_service_domains:['switch','homeassistant']}};
  window.noticeHass=window.createHassFixture({entities:{'switch.one':{state:'off',attributes:{friendly_name:'Switch'}},'weather.one':{state:'sunny',attributes:{forecast:[{datetime:'2026-10-02T13:00:00Z',condition:'rainy'}]}},'calendar.one':{state:'on'},'calendar.two':{state:'on'}},overrides:{connection:{},user:{id:'first',is_admin:true},callService(domain,service,data,target){window.noticeCalls.push({domain,service,data,target,user:this.user.id});return Promise.resolve();},callApi(method,path){const entry={method,path,user:this.user.id};window.noticeQueries.push(entry);return deferred?new Promise((resolve,reject)=>Object.assign(entry,{resolve,reject})):Promise.resolve([]);},callWS(message){const entry={message,user:this.user.id};window.noticeWS.push(entry);return deferred?new Promise((resolve,reject)=>Object.assign(entry,{resolve,reject})):Promise.resolve({response:{'weather.one':{forecast:[]}}});}}});
  const card=document.createElement('nodalia-notifications-card');card.setConfig(window.noticeConfig);card.hass=window.noticeHass;card.addEventListener('hass-more-info',event=>window.noticeInfo.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.noticeCard=card;
 },{calendar,weather,deferred,mobile});return page.locator('nodalia-notifications-card');
}
test('Notifications preserves native action focus during HA updates and handles action failures',async({page})=>{
 const card=await mount(page);await card.locator('[data-action="toggle-stack"]').press('Enter');await expect(card.locator('article')).toHaveCount(3);const first=card.locator("article").filter({hasText:"One"}).locator('[data-action="run-notification"]');await first.focus();await first.press('Enter');expect(await page.evaluate(()=>window.noticeCalls.find(row=>row.domain==='homeassistant'&&row.service==='toggle'))).toMatchObject({domain:'homeassistant',service:'toggle',data:{entity_id:'switch.one'}});
 await page.evaluate(()=>{window.noticeHass.states['switch.one'].attributes.friendly_name='Updated switch';window.noticeCard.hass={...window.noticeHass};});await expect(first).toBeFocused();await card.locator("article").filter({hasText:"Two"}).locator('[data-action="run-notification"]').press('Space');expect(await page.evaluate(()=>window.noticeCalls.findLast(row=>row.domain==='switch'&&row.service==='turn_on'))).toMatchObject({domain:'switch',service:'turn_on',data:{enabled:false,brightness:0,entity_id:'switch.one'}});await card.locator("article").filter({hasText:"Three"}).locator('[data-action="run-notification"]').press('Enter');expect(await page.evaluate(()=>window.noticeInfo)).toEqual(['switch.one']);
 await page.evaluate(()=>{window.noticeCard._hass.callService=()=>Promise.reject(new Error('offline'));});await first.press('Enter');await page.evaluate(()=>{window.noticeCard._hass.callService=()=>{throw new Error('sync offline');};});await first.press('Enter');await card.locator('[data-action="dismiss"]').first().press('Enter');await expect(card.locator('article')).toHaveCount(2);await expect(card.locator('[data-action="dismiss"]').first()).toBeFocused();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications owns calendar batches across connection, user, configuration and reconnect',async({page})=>{
 const card=await mount(page,{calendar:true,deferred:true});await expect.poll(()=>page.evaluate(()=>window.noticeQueries.length)).toBe(1);
 await page.evaluate(()=>{window.noticeHass={...window.noticeHass,connection:{},user:{id:'second',is_admin:true}};window.noticeCard.hass=window.noticeHass;window.noticeQueries[0].resolve([{summary:'Private old event',start:new Date().toISOString()}]);});await expect.poll(()=>page.evaluate(()=>window.noticeQueries.length)).toBe(2);expect(await page.evaluate(()=>window.noticeCard._calendarEvents)).toEqual([]);expect(await page.evaluate(()=>window.noticeQueries.map(row=>row.user))).toEqual(['first','second']);
 await page.evaluate(()=>window.noticeQueries[1].resolve([]));await expect.poll(()=>page.evaluate(()=>window.noticeQueries.length)).toBe(3);await page.evaluate(()=>window.noticeQueries[2].resolve([]));await expect.poll(()=>page.evaluate(()=>window.noticeCard._calendarRefreshInFlight)).toBe(false);
 await page.evaluate(()=>{window.noticePending=window.noticeCard._refreshCalendarEvents();window.noticeCard.setConfig({...window.noticeConfig,calendar_entities:[]});window.noticeQueries[3].resolve([{summary:'Abandoned config',start:new Date().toISOString()}]);});await page.evaluate(()=>window.noticePending);expect(await page.evaluate(()=>window.noticeCard._calendarEvents)).toEqual([]);
 await page.evaluate(()=>{window.noticeCard.setConfig({...window.noticeConfig,calendar_entities:['calendar.one']});});await expect.poll(()=>page.evaluate(()=>window.noticeQueries.length)).toBe(5);await page.evaluate(()=>{window.noticeCard.remove();document.querySelector('#fixture').append(window.noticeCard);window.noticeQueries[4].reject(new Error('Old request'));});await expect.poll(()=>page.evaluate(()=>window.noticeQueries.length)).toBe(6);expect(await page.evaluate(()=>({loading:window.noticeCard._calendarRefreshInFlight,error:window.noticeCard._calendarError}))).toEqual({loading:true,error:''});await page.evaluate(()=>window.noticeQueries[5].resolve([]));await expect.poll(()=>page.evaluate(()=>window.noticeCard._calendarRefreshInFlight)).toBe(false);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications uses current forecast service responses and keeps authoritative empty forecasts',async({page})=>{
 await mount(page,{weather:true,deferred:true});await expect.poll(()=>page.evaluate(()=>window.noticeWS.length)).toBe(1);expect(await page.evaluate(()=>window.noticeWS[0].message)).toEqual({type:'call_service',domain:'weather',service:'get_forecasts',service_data:{type:'hourly'},target:{entity_id:'weather.one'},return_response:true});
 await page.evaluate(()=>window.noticeWS[0].resolve({response:{'weather.one':{forecast:[]}}}));await expect.poll(()=>page.evaluate(()=>window.noticeCard._weatherRefreshInFlight)).toBe(false);expect(await page.evaluate(()=>window.noticeCard._weatherForecasts)).toEqual({'weather.one':[]});expect(await page.evaluate(()=>window.noticeWS.length)).toBe(1);
 await page.evaluate(()=>{window.noticeForecastPending=window.noticeCard._refreshWeatherForecasts();window.noticeHass={...window.noticeHass,connection:{},user:{id:'second',is_admin:false}};window.noticeCard.hass=window.noticeHass;window.noticeWS[1].resolve({response:{'weather.one':{forecast:[{condition:'rainy'}]}}});});await page.evaluate(()=>window.noticeForecastPending);await expect.poll(()=>page.evaluate(()=>window.noticeWS.length)).toBe(3);expect(await page.evaluate(()=>window.noticeCard._weatherForecasts)).toEqual({});
 await page.evaluate(()=>window.noticeWS[2].reject(new Error('No hourly')));await expect.poll(()=>page.evaluate(()=>window.noticeWS.length)).toBe(4);expect(await page.evaluate(()=>window.noticeWS[3].message.service_data.type)).toBe('daily');await page.evaluate(()=>window.noticeWS[3].resolve({response:{'weather.one':{forecast:[{datetime:'2026-10-02T13:00:00Z',condition:'rainy'}]}}}));await expect.poll(()=>page.evaluate(()=>window.noticeCard._weatherRefreshInFlight)).toBe(false);expect(await page.evaluate(()=>window.noticeCard._weatherForecasts['weather.one'][0].condition)).toBe('rainy');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications discards retired Engine work and foreground delivery without writing the next context',async({page})=>{
 await mount(page);const result=await page.evaluate(async()=>{
  const card=window.noticeCard,profiles=[],webhooks=[],dismissed=[];let resolveStatus;window.NodaliaBackend={...window.NodaliaBackend,status:()=>new Promise(resolve=>{resolveStatus=resolve;}),setNotificationProfile:async(...args)=>{profiles.push(args);return{};},dismissNotification:async(...args)=>{dismissed.push(args);return{};}};window.NodaliaUtils.postHomeAssistantWebhook=async(...args)=>{webhooks.push(args);return true;};
  card.setConfig({...window.noticeConfig,background_mobile:{enabled:true,profile_id:'first',webhook:'test'}});const pending=card._syncBackgroundMobileConfig();card.hass={...window.noticeHass,connection:{},user:{id:'second',is_admin:true}};resolveStatus({available:true,capabilities:['notifications_background']});await pending;
  const profileCount=profiles.length,webhookCount=webhooks.length;card.setConfig({...window.noticeConfig,mobile_notifications:{enabled:true,services:['notify.phone'],min_severity:'warning'}});let resolveSend;card._hass.callService=(domain,service,data)=>{window.noticeCalls.push({domain,service,data});return new Promise(resolve=>{resolveSend=resolve;});};const items=card._getRawNotifications();const flush=card._flushMobileNotifications(items);await Promise.resolve();await Promise.resolve();card.hass={...card._hass,connection:{},user:{id:'third',is_admin:true},callService:()=>{throw new Error('Sent into new context');}};resolveSend();await flush;
  card._saveNativeDismissed('door:binary_sensor.one');const resolveDismiss=resolveStatus;card.setConfig(window.noticeConfig);resolveDismiss({available:true,capabilities:['notifications_shared_dismissals']});await Promise.resolve();await Promise.resolve();
  const sent=[...card._mobileSent];card.remove();return {profileCount,webhookCount,calls:window.noticeCalls.length,sent,dismissed: dismissed.length};
 });expect(result).toEqual({profileCount:0,webhookCount:0,calls:1,sent:[],dismissed:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications scopes remembered dismissals by server/user and releases all view timers on detach',async({page})=>{
 const card=await mount(page);await card.locator('[data-action="dismiss"]').first().click();const first=await page.evaluate(()=>window.noticeCard._getStorageKey());await page.evaluate(()=>{window.noticeCard.hass={...window.noticeHass,user:{id:'second',is_admin:true}};});expect(await page.evaluate(()=>window.noticeCard._getStorageKey())).not.toBe(first);expect(await page.evaluate(()=>window.noticeCard._dismissed.size)).toBe(0);
 await page.evaluate(()=>{window.noticeCard.hass=window.noticeHass;});expect(await page.evaluate(()=>window.noticeCard._dismissed.size)).toBe(1);await page.clock.install();await page.evaluate(()=>{const c=window.noticeCard;c.setConfig({...window.noticeConfig,animations:{enabled:true}});c._onViewportResize();c._onClick({composedPath:()=>[c.shadowRoot.querySelector('[data-action="toggle-stack"]')],preventDefault(){},stopPropagation(){}});c.remove();});await page.clock.runFor(2000);expect(await page.evaluate(()=>{const c=window.noticeCard;return [c._stackCollapseTimer,c._viewportResizeTimer,c._calendarRefreshTimer,c._weatherRefreshTimer,c._mobileNotifyTimer,c._quietHoursWakeTimer,c._backgroundMobileSyncTimer,c._entranceAnimationTimer,c._mobileNotifyQueue.length];})).toEqual([0,0,0,0,0,0,0,0,0]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Notifications keeps one foreground drain in flight during repeated HA feedback',async({page})=>{
 await mount(page,{mobile:true});await page.clock.install();await page.evaluate(()=>{window.noticeSendResolvers=[];window.noticeHass.callService=(domain,service,data)=>{window.noticeCalls.push({domain,service,data});return new Promise(resolve=>window.noticeSendResolvers.push(resolve));};});await page.clock.runFor(451);await expect.poll(()=>page.evaluate(()=>window.noticeCalls.length)).toBe(1);
 await page.evaluate(()=>{for(let i=0;i<4;i++){window.noticeHass.states['switch.one'].attributes.friendly_name='Feedback '+i;window.noticeCard.hass={...window.noticeHass};}});await page.clock.runFor(1000);expect(await page.evaluate(()=>window.noticeCalls.length)).toBe(1);expect(await page.evaluate(()=>window.noticeCard._mobileDraining)).toBe(true);
 await page.evaluate(()=>window.noticeSendResolvers[0]());await expect.poll(()=>page.evaluate(()=>window.noticeCalls.length)).toBe(2);await page.evaluate(()=>window.noticeSendResolvers[1]());await expect.poll(()=>page.evaluate(()=>window.noticeCard._mobileDraining)).toBe(false);await page.clock.runFor(1000);expect(await page.evaluate(()=>window.noticeCalls.length)).toBe(2);expect(await page.evaluate(()=>window.noticeCard._mobileSent.size)).toBe(2);await page.evaluate(()=>window.noticeCard.remove());expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Notifications tracks smart templates and refreshes calendar batches that cross local midnight',async({page})=>{
 await mount(page);await page.clock.install({time:await page.evaluate(()=>new Date(2026,9,25,23,59,59,900).getTime())});const results=await page.evaluate(async()=>{
  const c=window.noticeCard;c.setConfig({...window.noticeConfig,calendar_entities:['calendar.one'],smart_notifications:{hot:{title:'{sensor.other.state}'}},smart_entity_overrides:[{entity:'sensor.temperature',message:'{sensor.override.state}'}]});
  const tracked=c._getTrackedEntityIds();window.midnightQueries=[];window.noticeHass.callApi=(method,path)=>new Promise(resolve=>window.midnightQueries.push({path,resolve}));window.midnightPending=c._refreshCalendarEvents();return {tracked};
 });expect(results.tracked).toContain('sensor.other');expect(results.tracked).toContain('sensor.override');await page.clock.runFor(200);await page.evaluate(()=>window.midnightQueries[0].resolve([{summary:'Old day',start:new Date(2026,9,25,12).toISOString()}]));await page.evaluate(()=>window.midnightPending);await page.clock.runFor(1);await expect.poll(()=>page.evaluate(()=>window.midnightQueries.length)).toBe(2);expect(await page.evaluate(()=>window.noticeCard._calendarEvents)).toEqual([]);await page.evaluate(()=>{window.midnightQueries[1].resolve([]);window.noticeCard.remove();});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Notifications retains the latest queued Engine sync through same-context HA feedback',async({page})=>{
 await mount(page);await page.clock.install();await page.evaluate(()=>{
  window.noticeStatusResolvers=[];window.noticeProfiles=[];window.NodaliaBackend={...window.NodaliaBackend,listNotificationInbox:undefined,status:()=>new Promise(resolve=>window.noticeStatusResolvers.push(resolve)),setNotificationProfile:async(_hass,profile)=>{window.noticeProfiles.push(profile);return {profile,dismissed:[]};}};
  window.noticeCard.setConfig({...window.noticeConfig,language:'auto',background_mobile:{enabled:true,profile_id:'current'}});window.noticeSyncPending=window.noticeCard._syncBackgroundMobileConfig();window.noticeCard.hass={...window.noticeHass,locale:{language:'es'}};
 });await page.clock.runFor(500);expect(await page.evaluate(()=>window.noticeStatusResolvers.length)).toBe(1);await page.evaluate(()=>window.noticeStatusResolvers[0]({available:true,capabilities:['notifications_background']}));await page.evaluate(()=>window.noticeSyncPending);await page.clock.runFor(321);await expect.poll(()=>page.evaluate(()=>window.noticeStatusResolvers.length)).toBe(2);await page.evaluate(()=>window.noticeStatusResolvers[1]({available:true,capabilities:['notifications_background']}));await expect.poll(()=>page.evaluate(()=>window.noticeProfiles.length)).toBe(2);expect(await page.evaluate(()=>window.noticeProfiles.at(-1).language)).toBe('es');await page.evaluate(()=>window.noticeCard.remove());expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
