import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-person-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-person-card').getConfigElement();editor.hass=window.makeHass({'person.one':{state:'home',attributes:{friendly_name:'Person'}},'device_tracker.one':{state:'home'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.personEditorFixture=editor;window.personEditorChanges=[];editor.addEventListener('config-changed',event=>window.personEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-person-card-editor');}
test('Person editor keeps unavailable entities, YAML fields and focus while guarding malformed native events and settings',async({page})=>{
 const editor=await mount(page,{entity:'person.missing',custom_extension:{value:7},haptics:42,animations:null,security:null});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('person.missing');
 await page.evaluate(()=>{window.personEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['person.bad']}}));});expect(await page.evaluate(()=>window.personEditorChanges.at(-1))).toMatchObject({entity:'person.missing',custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Resident');await page.evaluate(()=>{window.personEditorFixture.hass=window.makeHass({'person.two':{state:'home'}});});await expect(name).toBeFocused();await expect(name).toHaveValue('Resident');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Person editor preserves separate tap/hold/double actions, service targets and translucent styles when animation overrides clear',async({page})=>{
 const editor=await mount(page,{entity:'person.one',tap_action:'service',tap_service:'light.turn_on',tap_service_data:{brightness:0,flag:false},tap_service_target:{area_id:'living'},hold_action:'navigate',hold_navigation_path:'/lovelace/home',double_tap_action:'url',double_tap_url:'https://ha.example',animations:{content_duration:850},styles:{avatar:{background:'rgba(10, 20, 30, 0.3)'}}});
 await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.content_duration"]');await expect(duration).toHaveValue('850');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('420');
 const config=await page.evaluate(()=>window.personEditorChanges.at(-1));expect(config).toMatchObject({tap_action:'service',tap_service:'light.turn_on',tap_service_data:'{"brightness":0,"flag":false}',tap_service_target:'{"area_id":"living"}',hold_action:'navigate',hold_navigation_path:'/lovelace/home',double_tap_action:'url',double_tap_url:'https://ha.example',styles:{avatar:{background:'rgba(10, 20, 30, 0.3)'}}});expect(config.animations?.content_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
