import {expect,test} from '@playwright/test';
async function mount(page,config={}){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-power-flow-card'));
 await page.evaluate(config=>{
  window.powerActions=[];window.powerConfig={entities:{grid:{entity:{consumption:'sensor.import',production:'sensor.export'}},solar:{entity:'sensor.solar'},battery:{entity:'sensor.battery'},home:{entity:'sensor.home'},individual:[{entity:'sensor.device',name:'Appliance'}]},consumption_chips:{day_entity:'sensor.day'},animations:{enabled:false},haptics:{enabled:false},...config};
  window.powerHass=window.createHassFixture({entities:{'sensor.import':{state:'1000',attributes:{unit_of_measurement:'W'}},'sensor.export':{state:'250',attributes:{unit_of_measurement:'W'}},'sensor.solar':{state:'2000',attributes:{unit_of_measurement:'W'}},'sensor.battery':{state:'0',attributes:{unit_of_measurement:'W',battery_level:100}},'sensor.home':{state:'2500',attributes:{unit_of_measurement:'W'}},'sensor.device':{state:'500',attributes:{unit_of_measurement:'W'}},'sensor.day':{state:'0',attributes:{unit_of_measurement:'kWh'}},'sensor.unused':{state:'0',attributes:{}}},overrides:{connection:{},user:{id:'first',is_admin:true}}});
  const card=document.createElement('nodalia-power-flow-card');card.setConfig(window.powerConfig);card.hass=window.powerHass;card.addEventListener('hass-more-info',event=>window.powerActions.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.powerCard=card;
 },config);return page.locator('nodalia-power-flow-card');
}
test('Power Flow distinguishes missing split readings, export-only readings and actual zero',async({page})=>{
 const card=await mount(page,{entities:{grid:{entity:{consumption:'sensor.import',production:'sensor.export'}}}});const value=card.locator('.power-flow-card__node--grid .power-flow-card__chip--value');await expect(value).toHaveText('750 W');
 for(const reading of ['unknown','unavailable','',null]){
  await page.evaluate(reading=>{if(reading===null)delete window.powerHass.states['sensor.export'];else window.powerHass.states['sensor.export'].state=reading;window.powerCard.hass=window.powerHass;},reading);
  await expect(value).toHaveText('-- W');await expect(card.locator('.power-flow-card__node--grid .power-flow-card__unavailable')).toHaveCount(1);
 }
 await page.evaluate(()=>{window.powerHass.states['sensor.export']={entity_id:'sensor.export',state:'0',attributes:{unit_of_measurement:'W'}};window.powerHass.states['sensor.import'].state='0';window.powerCard.hass=window.powerHass;});await expect(value).toHaveText('0 W');await expect(card.locator('.power-flow-card__node--grid .power-flow-card__unavailable')).toHaveCount(0);
 await page.evaluate(()=>{window.powerCard.setConfig({...window.powerConfig,entities:{...window.powerConfig.entities,grid:{export_entity:'sensor.export'}}});window.powerHass.states['sensor.export'].state='unknown';window.powerCard.hass=window.powerHass;});await expect(value).toHaveText('-- W');await page.evaluate(()=>{window.powerHass.states['sensor.export'].state='0';window.powerCard.hass=window.powerHass;});await expect(value).toHaveText('0 W');await page.evaluate(()=>{window.powerHass.states['sensor.export'].state='900';window.powerCard.hass=window.powerHass;});await expect(value).toContainText('900 W');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Power Flow retains native action focus and updates displayed attributes without timestamp changes',async({page})=>{
 const card=await mount(page);const chip=card.locator('ha-card [data-node-entity="sensor.day"]');await chip.focus();await chip.press('Enter');expect(await page.evaluate(()=>window.powerActions)).toEqual(['sensor.day']);
 await page.evaluate(()=>{window.powerHass.states['sensor.day'].attributes.unit_of_measurement='Wh';window.powerHass.states['sensor.day'].state='1250';window.powerCard.hass=window.powerHass;});await expect(chip).toBeFocused();await expect(chip).toContainText('1.3');
 await page.evaluate(()=>{window.powerHass.states['sensor.battery'].attributes.battery_level=20;window.powerHass.states['sensor.solar'].attributes.unit_of_measurement='kW';window.powerCard.hass=window.powerHass;});await expect(card.locator('.power-flow-card__node--battery .power-flow-card__bubble ha-icon')).toHaveAttribute('icon','mdi:battery');await expect(card.locator('.power-flow-card__node--solar .power-flow-card__chip--value')).toHaveText('2,000 kW');await expect(chip).toBeFocused();
 const markup=await card.evaluate(node=>node.shadowRoot.innerHTML);await page.evaluate(()=>{window.powerHass.states['sensor.unused'].state='1';window.powerCard.hass=window.powerHass;});expect(await card.evaluate(node=>node.shadowRoot.innerHTML)).toBe(markup);await chip.press('Space');expect(await page.evaluate(()=>window.powerActions)).toEqual(['sensor.day','sensor.day']);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Power Flow closes native device dialogs across config/user/detach and returns keyboard focus',async({page})=>{
 const card=await mount(page);const home=card.locator('ha-card .power-flow-card__bubble[data-node-action="home-popup"]');await home.focus();await home.press('Enter');const dialog=card.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog.locator('.power-flow-card__home-popup-icon-button[data-home-popup-action="close"]')).toBeFocused();const device=dialog.locator('[data-node-entity="sensor.device"]');await device.focus();await page.evaluate(()=>{window.powerHass.states['sensor.device'].state='600';window.powerCard.hass=window.powerHass;});await expect(device).toBeFocused();await expect(dialog.locator('.power-flow-card__home-popup-list')).toContainText('600');await device.press('Enter');expect(await page.evaluate(()=>window.powerActions)).toEqual(['sensor.device']);await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(home).toBeFocused();
 for(const kind of ['config','user','connection','detach']){
  await home.press('Enter');await expect(dialog).toBeVisible();await page.evaluate(kind=>{if(kind==='config')window.powerCard.setConfig(window.powerConfig);if(kind==='user'){window.powerHass.user.id+='x';window.powerCard.hass=window.powerHass;}if(kind==='connection'){window.powerHass.connection={};window.powerCard.hass=window.powerHass;}if(kind==='detach'){window.powerCard.remove();document.querySelector('#fixture').append(window.powerCard);}},kind);await expect(dialog).toHaveCount(0);await expect(card).not.toHaveAttribute('data-home-popup-open','');await home.focus();
 }
 expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Power Flow ignores retired viewport/frame callbacks and releases owned press/entrance work',async({page})=>{
 await page.addInitScript(()=>{
  const NativeObserver=window.IntersectionObserver;window.powerObservers=new Map();window.IntersectionObserver=function(callback,options){const observer=new NativeObserver(callback,options);window.powerObservers.set(observer,callback);return observer;};
  const request=window.requestAnimationFrame.bind(window);window.powerFrames=new Map();window.requestAnimationFrame=callback=>{const id=request(callback);window.powerFrames.set(id,callback);return id;};
 });
 const card=await mount(page,{animations:{enabled:true,content_duration:460,button_bounce_duration:320}});await page.evaluate(()=>{window.oldPowerObserver=window.powerCard._flowViewportObserver;window.oldPowerObserverCallback=window.powerObservers.get(window.oldPowerObserver);window.oldPowerFrame=window.powerFrames.get(window.powerCard._flowUnpauseRaf);window.powerCard.remove();document.querySelector('#fixture').append(window.powerCard);window.powerCard._flowViewportVisible=true;window.oldPowerObserverCallback([{isIntersecting:false}],window.oldPowerObserver);if(window.oldPowerFrame)window.oldPowerFrame(0);});expect(await card.evaluate(node=>node._flowViewportVisible)).toBe(true);
 await card.locator('.power-flow-card__node--solar .power-flow-card__bubble').press('Enter');expect(await card.evaluate(node=>node._animationWork.timers.size)).toBeGreaterThan(0);await page.evaluate(()=>{window.powerCard.remove();window.powerHass.states['sensor.solar'].state='3000';window.powerCard.hass=window.powerHass;});expect(await page.evaluate(()=>({timers:window.powerCard._animationWork.timers.size,entrance:window.powerCard._entranceAnimationResetTimer,observer:window.powerCard._flowViewportObserver,frame:window.powerCard._flowUnpauseRaf}))).toEqual({timers:0,entrance:0,observer:null,frame:0});await page.evaluate(()=>document.querySelector('#fixture').append(window.powerCard));await expect(card.locator('.power-flow-card__node--solar .power-flow-card__chip--value')).toHaveText('3 kW');
 await card.evaluate(node=>node.style.transform='translateY(10000px)');await expect(card.locator('ha-card')).toHaveClass(/power-flow-card--motion-paused/);expect(await card.locator('svg').first().evaluate(node=>node.animationsPaused?.())).toBe(true);await card.evaluate(node=>node.style.transform='');await expect(card.locator('ha-card')).not.toHaveClass(/power-flow-card--motion-paused/);await expect.poll(()=>card.locator('svg').first().evaluate(node=>node.animationsPaused?.())).toBe(false);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});

test('Power Flow card activation resolves a split home source to its actual entity id',async({page})=>{
 const card=await mount(page,{tap_action:'more-info',entities:{home:{entity:{consumption:'sensor.home',production:'sensor.export'}}}});
 const content=card.locator('.power-flow-card__content[data-card-action="primary"]');await content.focus();await content.press('Enter');
 expect(await page.evaluate(()=>window.powerActions)).toEqual(['sensor.home']);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
