import {expect,test} from '@playwright/test';
test.use({hasTouch:true});
async function mount(page,config={}){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-room-summary-card'));
 await page.evaluate(config=>{
  window.roomActions=[];window.roomServices=[];window.roomHaptics=[];
  window.roomConfig={name:'Living room',temperature:'sensor.temperature',lights:['light.one'],covers:['cover.one'],locks:['lock.front'],media_player:'media_player.one',animations:{enabled:false},haptics:{enabled:false},...config};
  window.roomHass=window.createHassFixture({entities:{'sensor.temperature':{state:'0',attributes:{unit_of_measurement:'°C'}},'light.one':{state:'on',last_updated:'2026-10-01T10:00:00Z',attributes:{friendly_name:'Lamp',brightness:100,supported_color_modes:['brightness']}},'cover.one':{state:'closed',attributes:{friendly_name:'Blind',current_position:0}},'lock.front':{state:'locked',attributes:{friendly_name:'Door'}},'media_player.one':{state:'paused',attributes:{friendly_name:'Speaker',media_title:'Track'}},'sensor.unused':{state:'0',attributes:{}}},overrides:{connection:{},user:{id:'first',is_admin:true},callService(domain,service,data,target){window.roomServices.push({domain,service,data,target});return window.roomRejectService?Promise.reject(new Error('Offline')):Promise.resolve();}}});
  const card=document.createElement('nodalia-room-summary-card');card.setConfig(window.roomConfig);card.hass=window.roomHass;card.addEventListener('hass-more-info',event=>window.roomActions.push(event.detail.entityId));card.addEventListener('haptic',event=>window.roomHaptics.push(event.detail));document.querySelector('#fixture').append(card);window.roomCard=card;
 },config);return page.locator('nodalia-room-summary-card');
}
test('Room Summary updates child metadata without remounting and isolates connection/user contexts',async({page})=>{
 const card=await mount(page);await card.locator('[data-room-action="nav:lights"]').click();const light=card.locator('nodalia-light-card');await expect(light.locator('.light-card__title')).toContainText('Lamp');await page.evaluate(()=>{window.roomLight=window.roomCard.shadowRoot.querySelector('nodalia-light-card');window.roomHass.states['light.one'].attributes.friendly_name='Renamed lamp';window.roomHass.states['light.one'].attributes.icon='mdi:floor-lamp';window.roomCard.hass={...window.roomHass};});await expect(light.locator('.light-card__icon ha-icon').first()).toHaveAttribute('icon','mdi:floor-lamp');expect(await page.evaluate(()=>window.roomLight===window.roomCard.shadowRoot.querySelector('nodalia-light-card'))).toBe(true);
 const signature=await page.evaluate(()=>window.roomCard._lastRenderSignature);await page.evaluate(()=>{window.roomHass.states['sensor.unused'].state='1';window.roomCard.hass={...window.roomHass};});expect(await page.evaluate(()=>window.roomCard._lastRenderSignature)).toBe(signature);expect(await light.evaluate(node=>node._hass.states['sensor.unused'].state)).toBe('1');
 await page.evaluate(()=>{window.roomHass.user.id='second';window.roomCard.hass=window.roomHass;});expect(await page.evaluate(()=>({oldConnected:window.roomLight.isConnected,same:window.roomLight===window.roomCard.shadowRoot.querySelector('nodalia-light-card')}))).toEqual({oldConnected:false,same:false});await page.evaluate(()=>{window.roomLight=window.roomCard.shadowRoot.querySelector('nodalia-light-card');window.roomHass.connection={};window.roomCard.hass=window.roomHass;});expect(await page.evaluate(()=>window.roomLight.isConnected)).toBe(false);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Room Summary parks only configured children, uses native Lock and home media, and resets removed panels',async({page})=>{
 const card=await mount(page);await expect(card.locator('nodalia-media-player')).toHaveCount(1);await expect(card.locator('[data-room-action="nav:media"]')).toHaveCount(0);await page.evaluate(()=>window.roomMedia=window.roomCard.shadowRoot.querySelector('nodalia-media-player'));await card.locator('[data-room-action="nav:security"]').click();await expect(card.locator('nodalia-lock-card')).toHaveCount(1);await expect(card.locator('nodalia-entity-card')).toHaveCount(0);expect(await page.evaluate(()=>window.roomMedia.isConnected)).toBe(false);await card.locator('[data-room-action="nav:home"]').click();expect(await page.evaluate(()=>window.roomMedia===window.roomCard.shadowRoot.querySelector('nodalia-media-player'))).toBe(true);
 await card.locator('[data-room-action="nav:lights"]').click();await card.locator('[data-room-action="nav:home"]').focus();await page.evaluate(()=>{window.roomOldCards=[...window.roomCard._hubEmbedCache.values()];window.roomCard.setConfig({name:'Empty room',lights:[],media_player:'',animations:{enabled:false}});});expect(await page.evaluate(()=>({panel:window.roomCard._activePanel,stash:window.roomCard._hubEmbedStash,old:window.roomOldCards.every(card=>!card.isConnected&&card.parentNode===null),cache:window.roomCard._hubEmbedCache.size}))).toEqual({panel:'home',stash:null,old:true,cache:0});await expect(card.locator('[data-room-action="primary"]')).toBeFocused();await page.evaluate(()=>{window.roomCard.remove();document.querySelector('#fixture').append(window.roomCard);});await expect(card.locator('.room-hub__room-title')).toHaveText('Empty room');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Room Summary retains native keyboard focus on refreshed navigation, metrics and cover controls',async({page})=>{
 const card=await mount(page);const nav=card.locator('[data-room-action="nav:covers"]');await nav.focus();await nav.press('Enter');await expect(card.locator('[data-room-action="nav:home"]')).toBeFocused();const close=card.locator('[data-room-action="cover:close_cover:cover.one"]');await close.focus();await page.evaluate(()=>{window.roomHass.states['cover.one'].attributes.friendly_name='Renamed blind';window.roomCard.hass={...window.roomHass};});await expect(close).toBeFocused();await expect(card.locator('.room-hub__device-name')).toHaveText('Renamed blind');await expect(card.locator('.room-hub__device-state')).toHaveText('0%');await close.press('Space');expect(await page.evaluate(()=>window.roomServices.at(-1))).toMatchObject({domain:'cover',service:'close_cover',data:{entity_id:'cover.one'}});
 const metric=card.locator('[data-room-action="more-info:sensor.temperature"]');await metric.focus();await page.evaluate(()=>{window.roomHass.states['sensor.temperature'].state='1';window.roomCard.hass={...window.roomHass};});await expect(metric).toBeFocused();await expect(metric).toContainText('1°C');await metric.press('Enter');expect(await page.evaluate(()=>window.roomActions)).toEqual(['sensor.temperature']);expect(await page.evaluate(()=>window.roomHaptics)).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Room Summary cancels holds on movement/config/context/auth/detach and keeps strict service targets',async({page})=>{
 const card=await mount(page,{hold_action:'more-info',tap_action:'service',tap_service:'script.room',tap_service_data:{enabled:false,count:0},tap_service_target:{area_id:'living'},security:{allowed_services:['script.room']}});const primary=card.locator('[data-room-action="primary"]');
 for(const kind of ['move','config','context','auth','detach']){await primary.dispatchEvent('pointerdown',{pointerId:3,button:0,clientX:20,clientY:20});if(kind==='move')await primary.dispatchEvent('pointermove',{pointerId:3,clientX:60,clientY:20});else await page.evaluate(kind=>{if(kind==='config')window.roomCard.setConfig(window.roomConfig);if(kind==='context'){window.roomHass.user.id+='x';window.roomCard.hass=window.roomHass;}if(kind==='auth'){window.roomHass.auth={};window.roomCard.hass=window.roomHass;}if(kind==='detach'){window.roomCard.remove();document.querySelector('#fixture').append(window.roomCard);}},kind);await page.waitForTimeout(550);}expect(await page.evaluate(()=>window.roomActions)).toEqual([]);
 await primary.dispatchEvent('pointerdown',{pointerId:4,button:0});await expect.poll(()=>page.evaluate(()=>window.roomActions)).toEqual(['sensor.temperature']);await primary.dispatchEvent('pointerup',{pointerId:4});await primary.dispatchEvent('click');expect(await page.evaluate(()=>window.roomServices.length)).toBe(0);await primary.press('Enter');expect(await page.evaluate(()=>window.roomServices.at(-1))).toMatchObject({domain:'script',service:'room',data:{enabled:false,count:0},target:{area_id:'living'}});
 await page.evaluate(()=>window.roomRejectService=true);await primary.click();expect(await page.evaluate(()=>window.roomHaptics)).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
