import {test,expect} from '@playwright/test';
async function mount(page){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>window.NodaliaUtils);await page.evaluate(()=>{const host=document.createElement('section');host.attachShadow({mode:'open'});host.shadowRoot.innerHTML='<button id="origin">Origin</button><div id="first"><button>A</button><button>B</button></div><div id="second"><button>C</button><button>D</button></div>';document.querySelector('#fixture').append(host);window.uHost=host;window.uCalls=[];});}
const clean=async page=>expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
test('Shared modal cleanup cannot release a replacement dialog and keyboard focus stays in its native shadow root',async({page})=>{
 await mount(page);await page.evaluate(()=>{const h=window.uHost;h.shadowRoot.querySelector('#origin').focus();window.uOldRelease=window.NodaliaUtils.bindModalFocus(h,h.shadowRoot.querySelector('#first'));window.uNewRelease=window.NodaliaUtils.bindModalFocus(h,h.shadowRoot.querySelector('#second'));window.uOldRelease();});const buttons=page.locator('#second button');await expect(buttons.first()).toBeFocused();await buttons.first().press('Shift+Tab');await expect(buttons.last()).toBeFocused();await buttons.last().press('Tab');await expect(buttons.first()).toBeFocused();await page.evaluate(()=>window.uNewRelease());await expect(page.locator('#origin')).toBeFocused();await clean(page);
});
test('Shared pointer holds cancel on blur and visibility changes and can reconnect without duplicate handlers',async({page})=>{
 await mount(page);await page.clock.install();await page.evaluate(()=>{window.uHoldRelease=window.NodaliaUtils.bindHostPointerHoldGesture(window.uHost,{resolveZone:()=> 'body',holdMs:500,onHold:zone=>window.uCalls.push(zone)});window.uHost.dispatchEvent(new PointerEvent('pointerdown',{pointerId:1,button:0,clientX:10,clientY:10}));window.dispatchEvent(new Event('blur'));});await page.clock.runFor(600);expect(await page.evaluate(()=>window.uCalls)).toEqual([]);
 await page.evaluate(()=>{window.uHost.dispatchEvent(new PointerEvent('pointerdown',{pointerId:2,button:0}));Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;});await page.clock.runFor(600);expect(await page.evaluate(()=>window.uCalls)).toEqual([]);await page.evaluate(()=>{window.uHoldRelease();window.uHoldRelease.reconnect();window.uHoldRelease.reconnect();window.uHost.dispatchEvent(new PointerEvent('pointerdown',{pointerId:3,button:0}));});await page.clock.runFor(600);expect(await page.evaluate(()=>window.uCalls)).toEqual(['body']);await page.evaluate(()=>window.uHoldRelease());await clean(page);
});
test('Shared pending single taps never issue an action after native host detachment',async({page})=>{
 await mount(page);await page.clock.install();await page.evaluate(()=>{window.NodaliaUtils.scheduleCardZoneTap(window.uHost,{doubleTapMs:250,onSingle:()=>window.uCalls.push('detached')});window.uHost.remove();});await page.clock.runFor(300);expect(await page.evaluate(()=>window.uCalls)).toEqual([]);await page.evaluate(()=>{document.querySelector('#fixture').append(window.uHost);window.NodaliaUtils.scheduleCardZoneTap(window.uHost,{doubleTapMs:250,onSingle:()=>window.uCalls.push('new')});});await page.clock.runFor(300);expect(await page.evaluate(()=>window.uCalls)).toEqual(['new']);await clean(page);
});
test('Shared editor layout frames coalesce and are cancelled before dialog closure or reattachment',async({page})=>{
 await mount(page);await page.clock.install();await page.evaluate(()=>{const pane=document.createElement('div');pane.className='element-editor';document.querySelector('#fixture').append(pane);pane.append(window.uHost);window.uPane=pane;window.NodaliaUtils.clampEditorDialogScroll(window.uHost);window.uFirstFrame=window.uHost._nodaliaEditorDialogLayoutFrame;window.NodaliaUtils.clampEditorDialogScroll(window.uHost);window.uSameFrame=window.uHost._nodaliaEditorDialogLayoutFrame===window.uFirstFrame;window.NodaliaUtils.releaseEditorDialogLayoutFix(window.uHost);window.uHost.remove();pane.append(window.uHost);});await page.clock.runFor(100);expect(await page.evaluate(()=>({same:window.uSameFrame,frame:window.uHost._nodaliaEditorDialogLayoutFrame,overflow:window.uPane.style.overflowY}))).toEqual({same:true,frame:0,overflow:''});await page.evaluate(()=>window.NodaliaUtils.clampEditorDialogScroll(window.uHost));await page.clock.runFor(100);expect(await page.evaluate(()=>window.uPane.style.overflowY)).toBe('auto');await page.evaluate(()=>{window.uPane.dispatchEvent(new Event('scroll'));window.NodaliaUtils.releaseEditorDialogLayoutFix(window.uHost);});expect(await page.evaluate(()=>({frame:window.uHost._nodaliaEditorDialogClampFrame,overflow:window.uPane.style.overflowY}))).toEqual({frame:0,overflow:''});await clean(page);
});
test('Shared native picker reuse delivers events only to current callbacks and preserves focus',async({page})=>{
 await mount(page);await page.evaluate(()=>{const picker=document.createElement('div');window.uHost.shadowRoot.append(picker);window.uPicker=picker;window.NodaliaUtils.mountIconPickerHost(picker,{value:'mdi:lock',onShadowInput:()=>window.uCalls.push('old')});window.uPickerChild=picker.firstElementChild;picker.firstElementChild.focus();window.NodaliaUtils.mountIconPickerHost(picker,{value:'mdi:lock-open',onShadowInput:()=>window.uCalls.push('new')});picker.firstElementChild.dispatchEvent(new Event('change'));});expect(await page.evaluate(()=>({same:window.uPicker.firstElementChild===window.uPickerChild,calls:window.uCalls,focused:window.uHost.shadowRoot.activeElement===window.uPickerChild}))).toEqual({same:true,calls:['new'],focused:true});await clean(page);
});
