import {expect,test} from '@playwright/test';
async function mount(page,config={}){
 await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-vacuum-card'));
 await page.evaluate(config=>{
  window.vacuumCalls=[];window.vacuumInfos=[];
  window.vacuumStates={'vacuum.one':{state:'docked',attributes:{friendly_name:'Robot',battery_level:50,fan_speed:'Balanced',fan_speed_list:['Quiet','Balanced','Turbo','Smart'],room_mapping:[{id:'1',name:'Living',cleaning_area_id:'1'},{id:'2',name:'Kitchen',cleaning_area_id:'2'}]}},'vacuum.two':{state:'docked',attributes:{friendly_name:'Second',battery_level:70}},'select.one_suction':{state:'Balanced',attributes:{options:['Quiet','Balanced','Turbo','Smart']}},'select.one_water':{state:'Low',attributes:{options:['Off','Low','High','Smart']}}};
  window.vacuumHass=window.createHassFixture({entities:window.vacuumStates,overrides:{callService(...args){window.vacuumCalls.push(args);return Promise.resolve();}}});
  const card=document.createElement('nodalia-vacuum-card');card.setConfig({entity:'vacuum.one',language:'en',compact_layout_mode:'never',suction_select_entity:'select.one_suction',mop_select_entity:'select.one_water',animations:{enabled:false},...config});card.hass=window.vacuumHass;card.addEventListener('hass-more-info',event=>window.vacuumInfos.push(event.detail.entityId));document.querySelector('#fixture').append(card);window.vacuumCard=card;
 },config);return page.locator('nodalia-vacuum-card');
}
test('Vacuum isolates optimistic modes, room selections and panels across robots and disconnection',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 const card=await mount(page);await card.locator('[data-vacuum-action="toggle-mode-panel"][data-mode-kind="suction"]').click();await card.locator('[data-value="Turbo"]').click();expect(await page.evaluate(()=>window.vacuumCard._pendingModeSelection.suction)).toBe('Turbo');
 await page.clock.fastForward(2000);await page.evaluate(()=>{const card=window.vacuumCard;card.setConfig({...card._config});card.hass=window.vacuumHass;});await page.clock.fastForward(499);expect(await page.evaluate(()=>window.vacuumCard._pendingModeSelection.suction)).toBe('Turbo');await page.clock.fastForward(1);expect(await page.evaluate(()=>window.vacuumCard._pendingModeSelection.suction)).toBe('');
 await card.locator('[data-vacuum-action="toggle-room-panel"]').click();await card.locator('[data-vacuum-action="toggle-room"]').first().click();expect(await page.evaluate(()=>window.vacuumCard._selectedCleaningAreas)).toEqual(['1']);
 await card.locator('[data-vacuum-action="primary"]').click();expect(await page.evaluate(()=>window.vacuumCalls.at(-1))).toEqual(['vacuum','clean_area',{entity_id:'vacuum.one',cleaning_area_id:['1']}]);
 await page.evaluate(()=>{const card=window.vacuumCard;card._setPendingModeSelection('suction','Quiet');card.setConfig({entity:'vacuum.two',compact_layout_mode:'never',animations:{enabled:false}});card.hass=window.vacuumHass;});expect(await page.evaluate(()=>({pending:window.vacuumCard._pendingModeSelection,rooms:window.vacuumCard._selectedCleaningAreas,panel:window.vacuumCard._activeModePanel,roomPanel:window.vacuumCard._roomPanelOpen}))).toEqual({pending:{suction:'',mop:''},rooms:[],panel:null,roomPanel:false});
 await page.evaluate(()=>{window.vacuumCard._setPendingModeSelection('suction','Turbo');window.vacuumCard._suppressNextVacuumTap=true;window.vacuumCard.remove();});expect(await page.evaluate(()=>({pending:window.vacuumCard._pendingModeSelection,timers:window.vacuumCard._pendingModeSelectionTimers,tap:window.vacuumCard._suppressNextVacuumTap,frame:window.vacuumCard._resizeFrame}))).toEqual({pending:{suction:'',mop:''},timers:{suction:0,mop:0},tap:false,frame:0});expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Vacuum panel transitions complete once and discard stale animation callbacks and fallback work',async({page})=>{
 await page.clock.install({time:new Date('2026-10-01T10:00:00Z')});await page.clock.pauseAt(new Date('2026-10-01T10:00:01Z'));
 const card=await mount(page,{animations:{enabled:true,panel_duration:800}});
 await page.evaluate(()=>{window.vacuumCard._setVisiblePanelKey('suction');const panel=window.vacuumCard.shadowRoot.querySelector('.vacuum-card__panel-shell');panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));window.vacuumCard._setVisiblePanelKey('mop');window.oldVacuumPanel=panel;window.vacuumCard._setVisiblePanelKey('room');panel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));});await expect(card.locator('.vacuum-card__panel-shell')).toHaveAttribute('data-panel-key','room');
 await page.clock.fastForward(1000);await expect(card.locator('.vacuum-card__panel-shell')).toHaveCount(1);await expect(card.locator('.vacuum-card__panel-shell')).toHaveAttribute('data-panel-key','room');
 const cleanup=await page.evaluate(()=>{const card=window.vacuumCard;card._setVisiblePanelKey('suction');const original=window.NodaliaUtils.scheduleDeferTimer;window.NodaliaUtils.scheduleDeferTimer=undefined;card._triggerButtonBounce(card.shadowRoot.querySelector('.vacuum-card__control'));card._scheduleLayoutRefresh(200);window.NodaliaUtils.scheduleDeferTimer=original;const scheduled=card._fallbackTimers.size;card.remove();window.oldVacuumPanel.dispatchEvent(new AnimationEvent('animationend',{bubbles:true}));return{scheduled,pending:card._fallbackTimers.size,listeners:card._panelAnimationCancels.size};});expect(cleanup.scheduled).toBeGreaterThan(0);expect(cleanup.pending).toBe(0);expect(cleanup.listeners).toBe(0);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Vacuum retains missing battery versus zero, guards registry/mapping data and catches service errors with keyboard controls',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));const card=await mount(page,{tap_action:'more_info',icon_tap_action:'more_info'});
 await card.locator('ha-card[data-vacuum-action="body_tap"]').press('Enter');await card.locator('.vacuum-card__icon-button').press(' ');expect(await page.evaluate(()=>window.vacuumInfos)).toEqual(['vacuum.one','vacuum.one']);
 await page.evaluate(()=>{window.vacuumStates['vacuum.one'].attributes.battery_level=null;window.vacuumHass=window.createHassFixture({entities:window.vacuumStates,overrides:{entities:'malformed'}});window.vacuumCard.hass=window.vacuumHass;});await expect(card.locator('.vacuum-card__chip--battery')).toHaveCount(0);
 await page.evaluate(()=>{window.vacuumStates['vacuum.one'].attributes.battery_level=0;window.vacuumStates['vacuum.one'].attributes.room_mapping=[null,3,'bad',{id:'0',name:'Zero',cleaning_area_id:0}];window.vacuumCard.hass=window.createHassFixture({entities:window.vacuumStates});});await expect(card.locator('.vacuum-card__chip--battery')).toHaveText('0%');expect(await page.evaluate(()=>window.vacuumCard._getRoomMappings(window.vacuumCard._getState()))).toEqual([{cleaningAreaId:'0',id:'0',name:'Zero'}]);
 await page.evaluate(()=>{window.vacuumCard._hass.callService=()=>Promise.reject(new Error('offline'));window.vacuumCard._callService('start',{repeat:0,flag:false});window.vacuumCard._callSelectOption('select.one_suction','Quiet');});
 await page.evaluate(()=>{window.vacuumCard._hass.callService=()=>{throw new Error('sync offline');};window.vacuumCard._callService('locate');window.vacuumCard._callSelectOption('select.one_water','Low');});expect(errors).toEqual([]);expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
