import {expect,test} from '@playwright/test';
async function mount(page,config){await page.goto('/tests/fixtures/browser.html');await page.waitForFunction(()=>customElements.get('nodalia-weather-card'));await page.evaluate(async config=>{const editor=await customElements.get('nodalia-weather-card').getConfigElement();editor.hass=window.makeHass({'weather.one':{state:'sunny',attributes:{friendly_name:'Outside'}},'binary_sensor.alert':{state:'off'}});editor.setConfig(config);document.querySelector('#fixture').append(editor);window.weatherEditorFixture=editor;window.weatherEditorChanges=[];editor.addEventListener('config-changed',event=>window.weatherEditorChanges.push(event.detail.config));},config);return page.locator('nodalia-weather-card-editor');}
test('Weather editor guards nested settings and picker payloads while keeping missing entities, YAML fields and focus',async({page})=>{
 const editor=await mount(page,{entity:'weather.missing',meteoalarm_entity:'binary_sensor.missing',show_meteoalarm_chip:true,haptics:null,animations:42,custom_extension:{value:7}});await expect(editor.locator('select[data-field="entity"]')).toHaveValue('weather.missing');await expect(editor.locator('select[data-field="meteoalarm_entity"]')).toHaveValue('binary_sensor.missing');
 await page.evaluate(()=>window.weatherEditorFixture.shadowRoot.querySelector('select[data-field="entity"]').dispatchEvent(new CustomEvent('value-changed',{bubbles:true,composed:true,detail:{value:['weather.bad']}})));expect(await page.evaluate(()=>window.weatherEditorChanges.at(-1))).toMatchObject({entity:'weather.missing',custom_extension:{value:7}});
 const name=editor.locator('input[data-field="name"]');await name.fill('Terrace');await page.evaluate(()=>window.weatherEditorFixture.hass=window.makeHass({'weather.two':{state:'cloudy'}}));await expect(name).toBeFocused();await expect(name).toHaveValue('Terrace');await editor.locator('[data-editor-toggle="animations"]').click();await expect(editor.locator('input[data-field="animations.content_duration"]')).toHaveValue('420');expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
test('Weather editor restores cleared forecast and animation defaults while retaining units, actions and translucent styles',async({page})=>{
 const editor=await mount(page,{entity:'weather.one',unit_system:'imperial',temperature_unit:'fahrenheit',wind_speed_unit:'mph',show_forecast_details:true,forecast_view:'chart',forecast_type:'daily',forecast_chart_color_enabled:true,forecast_chart_color_mode:'condition',forecast_slots_daily:9,tap_action:'none',hold_action:'more-info',double_tap_action:'more-info',animations:{content_duration:850},styles:{icon:{background:'rgba(10, 20, 30, 0.3)'}}});
 const slots=editor.locator('input[data-field="forecast_slots_daily"]');await expect(slots).toHaveValue('9');await slots.fill('');await slots.dispatchEvent('change');await expect(slots).toHaveValue('5');await editor.locator('[data-editor-toggle="animations"]').click();const duration=editor.locator('input[data-field="animations.content_duration"]');await expect(duration).toHaveValue('850');await duration.fill('');await duration.dispatchEvent('change');await expect(duration).toHaveValue('420');
 const config=await page.evaluate(()=>window.weatherEditorChanges.at(-1));expect(config).toMatchObject({unit_system:'imperial',temperature_unit:'fahrenheit',wind_speed_unit:'mph',forecast_view:'chart',forecast_type:'daily',forecast_chart_color_enabled:true,forecast_chart_color_mode:'condition',tap_action:'none',double_tap_action:'more-info',styles:{icon:{background:'rgba(10, 20, 30, 0.3)'}}});expect(config.forecast_slots_daily).toBeUndefined();expect(config.animations?.content_duration).toBeUndefined();expect(await page.evaluate(()=>window.bundleErrors)).toEqual([]);
});
