import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "nodalia-*.js",
      "scripts/**/*.mjs",
      "tests/**/*.mjs",
      "src/cards/climate/climate-card.ts",
      "src/cards/climate/climate-editor.ts",
      "src/cards/media-player/media-player-card.ts",
      "src/cards/media-player/media-player-editor.ts",
      "src/cards/media-player/media-player-helpers.ts",
      "src/cards/light/light-card.ts",
      "src/cards/light/light-editor.ts",
      "src/cards/light/light-helpers.ts",
      "src/cards/fan/fan-card.ts",
      "src/cards/fan/fan-editor.ts",
      "src/cards/fan/fan-helpers.ts",
      "src/cards/humidifier/humidifier-card.ts",
      "src/cards/humidifier/humidifier-editor.ts",
      "src/cards/humidifier/humidifier-helpers.ts",
      "src/cards/cover/cover-card.ts",
      "src/cards/cover/cover-editor.ts",
      "src/cards/cover/cover-helpers.ts",
      "src/cards/alarm-panel/alarm-panel-card.ts",
      "src/cards/alarm-panel/alarm-panel-editor.ts",
      "src/cards/alarm-panel/alarm-panel-helpers.ts",
      "src/cards/vacuum/vacuum-card.ts",
      "src/cards/vacuum/vacuum-editor.ts",
      "src/cards/vacuum/vacuum-helpers.ts",
      "src/cards/entity/entity-card.ts",
      "src/cards/entity/entity-editor.ts",
      "src/cards/entity/entity-helpers.ts",
      "src/cards/fav/fav-card.ts",
      "src/cards/fav/fav-editor.ts",
      "src/cards/fav/fav-helpers.ts",
      "src/cards/person/person-card.ts",
      "src/cards/person/person-editor.ts",
      "src/cards/person/person-helpers.ts",
      "src/cards/camera/camera-card.ts",
      "src/cards/camera/camera-editor.ts",
      "src/cards/camera/camera-helpers.ts",
      "src/cards/circular-gauge/circular-gauge-card.ts",
      "src/cards/circular-gauge/circular-gauge-editor.ts",
      "src/cards/circular-gauge/circular-gauge-helpers.ts",
      "src/cards/insignia/insignia-card.ts",
      "src/cards/insignia/insignia-editor.ts",
      "src/cards/insignia/insignia-helpers.ts",
      "src/cards/scenes/scenes-card.ts",
      "src/cards/scenes/scenes-editor.ts",
      "src/cards/scenes/scenes-helpers.ts",
      "src/cards/news/news-card.ts",
      "src/cards/news/news-editor.ts",
      "src/cards/news/news-helpers.ts",
      "src/cards/weather/weather-card.ts",
      "src/cards/weather/weather-editor.ts",
      "src/cards/weather/weather-helpers.ts",
      "src/cards/graph/graph-card.ts",
      "src/cards/graph/graph-editor.ts",
      "src/cards/graph/graph-helpers.ts",
      "src/cards/calendar/calendar-card.ts",
      "src/cards/calendar/calendar-editor.ts",
      "src/cards/calendar/calendar-helpers.ts",
      "src/cards/power-flow/power-flow-card.ts",
      "src/cards/power-flow/power-flow-editor.ts",
      "src/cards/power-flow/power-flow-helpers.ts",
      "src/cards/notifications/notifications-card.ts",
      "src/cards/notifications/notifications-editor.ts",
      "src/cards/notifications/notifications-helpers.ts",
      "src/cards/navigation/navigation-card.ts",
      "src/cards/navigation/navigation-editor.ts",
      "src/cards/navigation/navigation-helpers.ts",
      "src/cards/room-summary/room-summary-card.ts",
      "src/cards/room-summary/room-summary-editor.ts",
      "src/cards/room-summary/room-summary-helpers.ts",
      "src/cards/advance-vacuum/advance-vacuum-card.ts",
      "src/cards/advance-vacuum/advance-vacuum-editor.ts",
      "src/cards/advance-vacuum/advance-vacuum-helpers.ts",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.ts"],
    rules: {
      "no-undef": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["error", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      }],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/ban-ts-comment": ["error", {
        "ts-nocheck": "allow-with-description",
        "minimumDescriptionLength": 10,
      }],
      "no-console": "off",
    },
  },
);
