import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {buildSync} from 'esbuild';
const box={URL};box.window=box;box.location={origin:'https://ha.example'};vm.createContext(box);vm.runInContext(fs.readFileSync('nodalia-utils.js','utf8'),box);vm.runInContext(buildSync({entryPoints:['src/cards/advance-vacuum/advance-vacuum-helpers.ts'],bundle:true,write:false,format:'iife',globalName:'api'}).outputFiles[0].text,box);const api=box.api;
const plain=v=>JSON.parse(JSON.stringify(v));
const configBox={window:box};vm.createContext(configBox);vm.runInContext(buildSync({entryPoints:['src/cards/advance-vacuum/advance-vacuum-config.ts'],bundle:true,write:false,format:'iife',globalName:'api'}).outputFiles[0].text,configBox);const configApi=configBox.api;
const corners=[{x:0,y:0},{x:10,y:0},{x:0,y:10},{x:10,y:10}],mapped=corners.map(({x,y})=>({x:2*x+5,y:3*y+7}));
function close(actual,expected){assert.ok(Math.abs(actual.x-expected.x)<1e-7);assert.ok(Math.abs(actual.y-expected.y)<1e-7);}
test('Advanced Vacuum coordinates reject missing/nonfinite values and retain valid zero/comma numbers',()=>{
 for(const value of ['',null,undefined,false,{},[],Infinity]){assert.equal(api.parseNumber(value),null);assert.equal(api.parsePoint([value,1]),null);assert.equal(api.parseZoneRect([value,1,2,3]),null);}assert.equal(api.parseNumber('1,5'),1.5);assert.deepEqual(plain(api.parsePoint([0,'0'])),{x:0,y:0});assert.deepEqual(plain(api.parseZoneRect({x:0,y:0,width:10,height:20})),{x1:0,y1:0,x2:10,y2:20});assert.equal(api.parseZoneRect({width:10,height:20}),null);
});
test('Advanced Vacuum polygon geometry supports valid outlines, boundaries and invalid/overflow inputs',()=>{
 const polygon=api.parsePolygon([0,0,10,10]);assert.equal(api.polygonArea(polygon),100);assert.deepEqual(plain(api.centroid(polygon)),{x:5,y:5});assert.deepEqual(plain(api.polygonBounds(polygon)),{minX:0,maxX:10,minY:0,maxY:10,width:10,height:10});assert.equal(api.pointInPolygon({x:10,y:5},polygon),true);assert.equal(api.pointInPolygon({x:11,y:5},polygon),false);assert.equal(api.rectIntersectionArea({left:0,right:10,top:0,bottom:10},{left:5,right:15,top:5,bottom:15}),25);assert.equal(api.rectIntersectionArea({left:null},{}),0);assert.equal(api.polygonArea([{x:1e308,y:1e308},{x:-1e308,y:1e308},{x:0,y:-1e308}]),0);assert.equal(api.parseOutlines([null,false]).length,0);
});
test('Advanced Vacuum calibration preserves affine/projective transforms and inverse mapping',()=>{
 for(const count of [3,4]){const converter=new api.CoordinatesConverter(corners.slice(0,count).map((vacuum,index)=>({vacuum,map:mapped[index]})));assert.equal(converter.calibrated,true);assert.equal(converter.mode,count===3?'affine':'projective');close(converter.vacuumToMap(4,6),{x:13,y:25});close(converter.mapToVacuum(13,25),{x:4,y:6});}
 const matrix=api.invert3x3([2,0,5,0,3,7,0,0,1]);close(api.applyHomography(matrix,13,25),{x:4,y:6});assert.deepEqual(plain(api.solveLinearSystem([[2,1],[1,3]],[5,7])),[1.6,1.8]);
});
test('Advanced Vacuum calibration rejects ragged/singular/nonfinite matrices and malformed correspondences',()=>{
 for(const [matrix,vector] of [[[[1]],[]],[[[1,2],[3]],[1,2]],[[[Infinity]],[1]],[[[1,1],[2,2]],[1,2]]])assert.equal(api.solveLinearSystem(matrix,vector),null);assert.equal(api.invert3x3([1,2]),null);assert.equal(api.createAffineMatrix([null,...corners.slice(0,2)],mapped),null);const malformed=new api.CoordinatesConverter([null,...corners.slice(0,3).map((vacuum,index)=>({vacuum,map:mapped[index]}))]);assert.equal(malformed.calibrated,false);assert.deepEqual(plain(malformed.vacuumToMap(2,3)),{x:2,y:3});assert.deepEqual(plain(api.applyHomography([1,0,0,0,1,0,0,0,0],2,3)),{x:2,y:3});
});
test('Advanced Vacuum session codecs keep encoded identities/zones and reject missing coordinates',()=>{
 const ids=['Room,one','Kitchen & dining','Ático'];assert.deepEqual(plain(api.decodeSharedSessionList(api.encodeSharedSessionList(ids))),ids);const zones=[[0,0,100,200],[300,400,500,600]];assert.deepEqual(plain(api.decodeSharedSessionZones(api.encodeSharedSessionZones(zones))),[{x1:0,y1:0,x2:100,y2:200},{x1:300,y1:400,x2:500,y2:600}]);assert.equal(api.decodeSharedSessionZones('1::2:3;bad').length,0);assert.equal(api.appendQueryParam('/local/map?a=1#floor','nodalia_ts','new'),'/local/map?a=1&nodalia_ts=new#floor');assert.equal(api.appendQueryParam('/local/map?nodalia_ts=old#floor','nodalia_ts','new'),'/local/map?nodalia_ts=new#floor');assert.equal(api.stripMapCacheBuster('/local/map?nodalia_ts=old#floor'),'/local/map#floor');
});
test('Advanced Vacuum map/legacy selection records are narrowed and labels/icons remain strings',()=>{
 const rooms=api.resolveRoomSegments({room_segments:[null,{id:'one',label:{text:'Kitchen',offset_y:4},icon:{name:'mdi:chef-hat',x:5,y:5},outlines:[[0,0,10,10]]}]});assert.equal(rooms[0].label,'Kitchen');assert.equal(rooms[0].icon,'mdi:chef-hat');assert.equal(rooms[0].labelOffsetY,4);const hass={states:{'camera.map':{attributes:{rooms:{one:{name:'Kitchen',outlines:[[0,0,10,10]],pos_x:'',pos_y:''},bad:null}}}}};const inferred=api.resolveRoomsFromMapState(hass,'camera.map');assert.deepEqual(plain(inferred[0].iconPoint),{x:5,y:5});assert.equal(api.resolveGotoPoints({goto_points:[null,{id:'one',position:[0,0]}]}).length,1);assert.equal(api.resolvePredefinedZones({predefined_zones:[null,{id:'bad',zones:[[null,0,10,10]]}]}).length,0);assert.equal(api.resolveHeaderIcons({icons:[null,{icon:'mdi:home'}]}).length,1);
});
test('Advanced Vacuum normalized config/style/editor helpers preserve extensions and safe defaults',()=>{
 const config=configApi.normalizeConfig({room_tracking:null,custom_menu:[],security:{allow_webhooks_for_non_admin:'true'},routines:[null,'script.clean'],vacuum_mqtt_topic:'robot///',extension:{keep:true}});assert.equal(config.room_tracking.auto_detect,true);assert.equal(config.security.allow_webhooks_for_non_admin,false);assert.equal(config.routines[0].entity,'script.clean');assert.equal(config.vacuum_mqtt_topic,'robot');assert.equal(config.extension.keep,true);const styles=api.getSafeStyles({card:{padding:'1px; color: red',background:'color(display-p3 1 0 0 / .2)'}});assert.equal(styles.card.padding,'16px');assert.equal(styles.card.background,'color(display-p3 1 0 0 / .2)');assert.equal(api.getByPath(Object.create({nested:{value:1}}),'nested.value'),undefined);assert.equal(api.isHelperRelatedToConfiguredVacuum({candidateId:'sensor.roborock_s8_pro_room',objectId:'roborock_s8',vacuumObjectIds:['roborock_s8','roborock_s8_pro']}),false);
});
