import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {findGeneratedInitializer} from './helpers/generated-literals.mjs';import {RUNTIME_ENTRIES} from '../scripts/build-src-cards.mjs';
const editor=fs.readFileSync(new URL('../nodalia-editor-ui.js',import.meta.url),'utf8'),runtime=fs.readFileSync(new URL('../nodalia-i18n.js',import.meta.url),'utf8');
function load(source=editor){const box={window:null};box.window=box;vm.createContext(box);vm.runInContext(runtime,box);vm.runInContext(source,box);return box.NodaliaI18n;}
function replaceData(name,value){const node=findGeneratedInitializer(editor,name);return editor.slice(0,node.getStart())+JSON.stringify(JSON.stringify(value))+editor.slice(node.getEnd());}
test('Editor lookup is generated from checked source and keeps separate lazy row and catalog caches',()=>{assert.equal(RUNTIME_ENTRIES.find(item=>item.outfile==='nodalia-editor-ui.js')?.entry,'src/shared/editor-i18n-runtime.ts');assert.match(editor,/Generated from src\/shared\/editor-i18n-runtime.ts/);const api=load();assert.equal(api.editorUiMaps,null);assert.equal(api.editorCatalog,null);assert.equal(api.editorStr(null,'en','Activar animaciones'),'Enable animations');const maps=api.editorUiMaps;assert.ok(maps.en);assert.equal(api.editorCatalog,null);const key='ed.calendar.visible_range';assert.notEqual(api.editorStr(null,'en',key),key);const catalog=api.editorCatalog;api.editorStr(null,'fr',key);api.editorStr(null,'es','MUSICA');assert.equal(api.editorUiMaps,maps);assert.equal(api.editorCatalog,catalog);assert.equal(Object.keys(maps).length,12);assert.equal(Object.keys(catalog).length,12);});
test('Malformed generated rows fail at the unknown JSON boundary instead of becoming unchecked labels',()=>{for(const value of [null,{},[null],[[0]],[[{}]]]){const api=load(replaceData('ROWS_JSON',value));assert.throws(()=>api.editorStr(null,'en','Activar animaciones'),/Invalid editor translation data/);}});
test('Malformed generated catalog languages, keys and labels fail at the unknown JSON boundary',()=>{for(const value of [null,{langs:[1],keys:['ed.key'],values:[['label']]},{langs:['en'],keys:[null],values:[['label']]},{langs:['en'],keys:['ed.key'],values:[[{}]]}]){const api=load(replaceData('EDITOR_CATALOG_JSON',value));assert.throws(()=>api.editorStr(null,'en','ed.key'),/Invalid editor translation data/);}});

test('Editor lookup uses the current language resolver after Home Assistant changes it',()=>{const api=load();api.resolveLanguage=()=>"es";assert.equal(api.editorStr(null,'auto','Activar animaciones'),'Activar animaciones');api.resolveLanguage=()=>"en";assert.equal(api.editorStr(null,'auto','Activar animaciones'),'Enable animations');});
