import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {buildSync} from 'esbuild';
function load(){const box={URL,Date,console:{warn(){}}};box.window=box;vm.createContext(box);for(const file of ['nodalia-utils.js','nodalia-notifications-mobile-policy.js'])vm.runInContext(fs.readFileSync(file,'utf8'),box);vm.runInContext(buildSync({entryPoints:['src/cards/notifications/notifications-helpers.ts'],bundle:true,write:false,format:'iife',globalName:'api'}).outputFiles[0].text,box);return box;}
const box=load(),api=box.api,plain=v=>JSON.parse(JSON.stringify(v));
const entity=(state,attributes={})=>({entity_id:'sensor.temperature',state,attributes});
test('Notification measurements distinguish missing values from actual zero, including forecasts and thresholds',()=>{
 for(const raw of [null,undefined,'',' ',true,{},[],Infinity]){assert.equal(api.numericState(entity(raw)),null);assert.equal(api.formatNumber(raw,'°C'),'');assert.equal(api.forecastNumber({temperature:raw},['temperature']),null);assert.equal(api.finiteNumber(raw,25),25);}
 assert.equal(api.numericState(entity('0')),0);assert.equal(api.formatNumber(0,'°C'),'0°C');assert.equal(api.forecastNumber({temperature:'',native_temperature:0},['temperature','native_temperature']),0);
 const hass={states:{'sensor.temperature':entity('',{unit_of_measurement:'°C'})}};assert.equal(api.formatNotificationTemplate('Value:{sensor.temperature}',hass),'Value:');assert.equal(api.customNotificationTemplateValues(hass,{entity:'sensor.temperature',value:null}).threshold,'');hass.states['sensor.temperature'].state='0';assert.equal(api.formatNotificationTemplate('Value:{sensor.temperature}',hass),'Value:0°C');
 assert.equal(api.getBackgroundMobileConfigPayload({thresholds:{hot_temperature:'',cold_temperature:0}}).thresholds.hot_temperature,27);assert.equal(api.getBackgroundMobileConfigPayload({thresholds:{cold_temperature:0}}).thresholds.cold_temperature,0);
});
test('Notification registry boundaries resolve array/object areas and device assignments without trusting malformed rows',()=>{
 const hass={states:{'sensor.temperature':entity('21',{friendly_name:'Kitchen temperature'})},areas:[null,false,{area_id:'kitchen',name:'Kitchen'}],entities:{'sensor.temperature':{device_id:'one'}},devices:[null,{id:'one',area_id:'kitchen'}]};assert.equal(api.entityAreaName(hass,'sensor.temperature'),'Kitchen');assert.equal(api.entityAreaKey(hass,'sensor.temperature'),'kitchen');assert.deepEqual(plain(api.entityMatchTokens(hass,'sensor.temperature')),['kitchen']);
 hass.entities=null;hass.devices='bad';assert.equal(api.entityAreaName(hass,'sensor.temperature'),'Kitchen');hass.areas={kitchen:{name:'Cocina'}};hass.states['sensor.temperature'].attributes.area_id='kitchen';assert.equal(api.entityAreaName(hass,'sensor.temperature'),'Cocina');assert.equal(api.deviceRegistryEntry(hass,'one'),null);
});
test('Notification editor array paths filter empty segments and never mutate inherited branches',()=>{
 const target={};api.setByPath(target,'.custom..0.title.','Title');assert.deepEqual(plain(target),{custom:[{title:'Title'}]});assert.equal(api.getByPath(target,'custom.0.title'),'Title');api.deleteByPath(target,'custom.0.title');assert.deepEqual(plain(target),{custom:[{}]});const prototype={nested:{title:'Existing'}};const inherited=Object.create(prototype);assert.equal(api.getByPath(inherited,'nested.title'),undefined);api.setByPath(inherited,'nested.title','New');assert.equal(prototype.nested.title,'Existing');api.deleteByPath(inherited,'__proto__.nested.title');assert.equal(prototype.nested.title,'Existing');assert.equal(api.getByPath(inherited,'constructor.prototype'),undefined);assert.equal(api.compactConfig([]),undefined);assert.deepEqual(plain(api.compactConfig({keep:null,omit:'',rows:[null,'',{},0]})),{keep:null,rows:[0]});
});
test('Notification dates reject impossible days while preserving local midnight and calendar/forecast containers',()=>{
 for(const date of ['2026-02-29','2026-04-31','2026-13-01'])assert.equal(api.calendarEventDate(date),null);const leap=api.calendarEventDate({date:'2024-02-29'});assert.equal(leap.getDate(),29);assert.equal(leap.getHours(),0);assert.equal(api.formatTime(new Date(NaN)),'');const row={datetime:'2026-10-01T00:00:00Z',condition:'rainy'};assert.deepEqual(plain(api.normalizeCalendarFetchResult({events:[null,[],row]})),[row]);assert.deepEqual(plain(api.normalizeWeatherForecastResult({'weather.home':{forecast:[false,row]}},'weather.home')),[row]);assert.equal(api.forecastLooksRainy({precipitation:null,rain:0.5}),true);assert.equal(api.forecastLooksRainy({precipitation:0}),false);
});
test('Background notification profiles preserve explicit policies, valid chunks and unknown responses',async()=>{
 const config={language:'es-ES',background_mobile:{enabled:true,profile_id:'home',chunk_size:120},mobile_notifications:{enabled:true},smart_entity_overrides:[{entity:'sensor.temperature',mobile:'off'}]};const payload=api.getBackgroundMobileConfigPayload(config);assert.equal(payload.language,'es');assert.equal(payload.overrides['sensor.temperature'].mobile,'off');const chunks=api.buildBackgroundMobileWebhookPayload(config,null,{enabled:false});assert.equal(chunks.chunks.every(chunk=>chunk.length<=120),true);assert.equal(JSON.parse(chunks.chunks.join('')).enabled,false);
 const hass={states:{},user:{is_admin:true}};box.NodaliaBackend={status:async()=>({available:true,capabilities:['notifications_background']}),setNotificationProfile:async()=>null,getNotificationProfile:async()=>({profile:{enabled:true,notify:{enabled:true}},dismissed:['one']})};const synced=await api.syncBackgroundMobileNative(hass,config);assert.equal(synced.synced,true);assert.deepEqual(plain(synced.dismissed),[]);hass.user.is_admin=false;assert.equal((await api.syncBackgroundMobileNative(hass,config)).signature,'active:home');box.NodaliaBackend.getNotificationProfile=async()=>{throw Error('temporary');};const failed=await api.syncBackgroundMobileNative(hass,config);assert.equal(failed.available,true);assert.equal(failed.transient,true);
});
test('Notification external alert injection and legacy fallback accept only usable targets and handle transport failure',async()=>{
 assert.equal(api.pushExternalAlerts(null,[]),false);const received=[],target={_ingestRuntimeExternalAlerts(alerts){received.push(alerts);}};assert.equal(api.pushExternalAlerts(target,[{title:'Hello'}]),true);assert.equal(received.length,1);assert.equal(await api.setLegacyBackgroundMobileFallback({states:{}},true),true);const id='input_boolean.nodalia_background_mobile_notifications',calls=[],hass={states:{[id]:entity('off')},callService:(...args)=>{calls.push(args);return Promise.resolve();}};assert.equal(await api.setLegacyBackgroundMobileFallback(hass,true),true);assert.equal(calls[0][1],'turn_on');hass.callService=()=>Promise.reject(Error('unavailable'));assert.equal(await api.setLegacyBackgroundMobileFallback(hass,true),false);
});
