blank_issues_enabled: false

contact_links:
  - name: 💬 Discussions
    url: https://github.com/danielmigueltejedor/nodalia-cards/discussions
    about: Ask questions, share ideas or discuss Nodalia Cards.

  - name: 🧪 Alpha / Beta feedback
    url: https://github.com/danielmigueltejedor/nodalia-cards/discussions/categories/alpha-beta-feedback
    about: Share feedback about alpha or beta builds.

  - name: 📚 Documentation
    url: https://github.com/danielmigueltejedor/nodalia-cards#readme
    about: Read installation instructions and examples.
