export const CARD_TAG = "nodalia-navigation-bar";
export const EDITOR_TAG = "nodalia-navigation-bar-editor";
export const CARD_VERSION = "2.3.0-alpha.38";
export const HAPTIC_PATTERNS = {
  selection: 8,
  light: 10,
  medium: 16,
  heavy: 24,
  success: [10, 40, 10],
  warning: [20, 50, 12],
  failure: [12, 40, 12, 40, 18],
};
export const MUSIC_ASSISTANT_BROWSER_EXCLUDE_PATTERNS = [
  "ai generated",
  "ai-generated",
  "image",
  "image upload",
  "generated images",
  "camera",
  "cameras",
  "dlna",
  "dlna server",
  "dlna servers",
  "frigate",
  "my media",
  "text to speech",
  "tts",
  "xbox game media",
  "xbox",
  "imagenes generadas",
  "images",
  "imagenes",
];
export const MUSIC_ASSISTANT_DIRECTORY_ICON_RULES = [
  {
    patterns: [
      "artists",
      "artistas",
      "artistes",
      "артисты",
      "artiști",
      "艺术家",
      "καλλιτέχνες",
    ],
    icon: "mdi:account-music",
  },
  {
    patterns: [
      "albums",
      "albumes",
      "álbumes",
      "álbums",
      "albuns",
      "альбомы",
      "专辑",
      "άλμπουμ",
    ],
    icon: "mdi:album",
  },
  {
    patterns: [
      "tracks",
      "songs",
      "canciones",
      "temas",
      "pistas",
      "faixas",
      "músicas",
      "треки",
      "曲目",
      "κομμάτια",
      "piese",
    ],
    icon: "mdi:music-note",
  },
  {
    patterns: [
      "playlists",
      "listas",
      "listas de reproduccion",
      "listas de reproducción",
      "listas de reprodução",
      "плейлисты",
      "播放列表",
      "liste de redare",
      "λίστες αναπαραγωγής",
    ],
    icon: "mdi:playlist-music",
  },
  {
    patterns: [
      "radio stations",
      "radios",
      "emisoras",
      "stations",
      "estações",
      "радио",
      "радиостанции",
      "广播电台",
      "stații radio",
      "ραδιοφωνικοί",
    ],
    icon: "mdi:radio",
  },
  { patterns: ["podcasts", "подкасты", "播客", "podcasturi"], icon: "mdi:podcast" },
  {
    patterns: ["audiobooks", "audiolibros", "audiolivros", "аудиокниги", "有声书", "cărți audio", "ακουστικά βιβλία"],
    icon: "mdi:book-music",
  },
  {
    patterns: ["genres", "generos", "géneros", "жанры", "流派", "genuri", "είδη"],
    icon: "mdi:shape",
  },
  {
    patterns: [
      "favorites",
      "favourites",
      "favoritos",
      "избранное",
      "收藏",
      "favorite",
      "αγαπημένα",
    ],
    icon: "mdi:heart",
  },
  {
    patterns: [
      "recent",
      "recently",
      "recientes",
      "recentemente",
      "недавно",
      "最近",
      "πρόσφατα",
      "redări recente",
    ],
    icon: "mdi:history",
  },
  {
    patterns: [
      "search",
      "buscar",
      "busqueda",
      "búsqueda",
      "pesquisar",
      "поиск",
      "搜索",
      "căutare",
      "αναζήτηση",
    ],
    icon: "mdi:magnify",
  },
];
