import { STORAGE_KEY } from "./notifications-constants";

export const DEFAULT_CONFIG = {
  title: "Notifications",
  language: "auto",
  icon: "mdi:bell-badge-outline",
  empty_title: "All quiet",
  empty_message: "You have no current alerts",
  max_visible: 1,
  refresh_interval: 300,
  storage_key: STORAGE_KEY,
  dismissed_entity: "",
  calendar_entities: [],
  vacuum_entities: [],
  vacuum_error_entities: [],
  fan_entities: [],
  climate_entities: [],
  humidifier_entities: [],
  media_player_entities: [],
  weather_entities: [],
  motion_entities: [],
  door_entities: [],
  window_entities: [],
  temperature_entities: [],
  humidity_entities: [],
  outdoor_temperature_entities: [],
  outdoor_humidity_entities: [],
  battery_entities: [],
  humidifier_fill_entities: [],
  humidifier_full_entities: [],
  ink_entities: [],
  custom_notifications: [],
  smart_entity_overrides: [],
  presence_entity: "",
  mobile_context: {
    only_when_away: false,
    only_when_home: false,
    quiet_hours: {
      enabled: false,
      start: "23:00",
      end: "08:00",
      allow_critical: true,
    },
  },
  external_alerts: [],
  thresholds: {
    hot_temperature: 27,
    cold_temperature: 17,
    humidity_high: 70,
    humidity_low: 30,
    rain_probability: 50,
    rain_lookahead_hours: 6,
    media_absence_minutes: 10,
    battery_low: 20,
    humidifier_fill_low: 20,
    humidifier_fill_full: 90,
    ink_low: 15,
  },
  smart_recommendations: true,
  smart_notifications: {
    hot: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    cold: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    humidity_high: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    humidity_low: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    rain: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    media_left_on: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    battery_low: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    humidifier_fill_low: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    humidifier_fill_full: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
    ink_low: { title: "", message: "", tint_color: "", url: "", action_label: "", tap_action: { action: "none" } },
  },
  mobile_notifications: {
    enabled: false,
    entities: [],
    services: [],
    min_severity: "warning",
    critical_alerts: false,
    default_policy: "auto",
    cooldown_minutes: 30,
    group_similar: true,
  },
  background_mobile: {
    enabled: false,
    profile_id: "default",
    webhook: "",
    chunk_size: 240,
  },
  security: {
    strict_service_actions: true,
    allowed_services: [],
    allowed_service_domains: [],
    allow_webhooks_for_non_admin: false,
  },
  haptics: {
    enabled: true,
    style: "medium",
    fallback_vibrate: false,
  },
  animations: {
    enabled: true,
    content_duration: 420,
    button_bounce_duration: 320,
  },
  styles: {
    card: {
      background: "var(--ha-card-background, var(--card-background-color, rgba(32, 34, 42, 0.94)))",
      border: "1px solid var(--divider-color)",
      border_radius: "var(--nodalia-card-border-radius, 28px)",
      box_shadow: "var(--ha-card-box-shadow)",
      padding: "18px",
      gap: "14px",
    },
    icon: {
      background: "color-mix(in srgb, var(--primary-color) 18%, transparent)",
      color: "var(--primary-color)",
      size: "54px",
    },
    title_size: "22px",
    item_radius: "var(--nodalia-card-border-radius, 28px)",
    accent: "var(--primary-color)",
  },
};
